var buttonLabels = [
  "Ok",
  "Okay",
  "Yes",
  "Accept",
  "Activate",
  "Enable",
  "Register",
  "Action",
  "Correct",
  "Go",
  "Start",
  "Begin",
  "Enact",
  "Use",
  "Process",
  "Calculate",
  "Compute",
  "Button",
  "Choose",
  "Launch",
  "Load",
  "Reload",
  "Add",
  "Join"
];

var technologies = [
  "3D displays",
  "3D optical data storage",
  "3D printing",
  "3D-TV",
  "4G cellular networking",
  "5G broadband",
  "abortion",
  "actuators",
  "adaptive optics",
  "Advanced Tactical Lasers",
  "aerogels",
  "aeroscraft",
  "aesthetic medicine",
  "agricultural robotics",
  "agricultural science",
  "airborne wind turbines",
  "aircraft flight control systems",
  "airless tires",
  "alternative fuel vehicles",
  "aluminium",
  "ambient intelligence",
  "amorphous metals",
  "analogue electronics",
  "Android",
  "animal husbandry",
  "answer machines",
  "Anti-gravity technology",
  "antimatter weapons",
  "arcologies",
  "artificial brains",
  "Artificial gravity systems",
  "artificial intelligence",
  "artificial Passengers",
  "artificial photosynthesis",
  "asteroid mining",
  "atmospheric carbon dioxide removal",
  "Atomtronics",
  "augmented reality",
  "automated guided vehicles",
  "autonomous buildings",
  "autonomous cars",
  "autonomous research robots",
  "autonomous robotics",
  "autonomous underwater vehicles",
  "autostereoscopic displays",
  "backpack helicopters",
  "banotechnology",
  "barcodes",
  "batteries",
  "bead washing machines",
  "beam-powered propulsion",
  "behavior-based robotics",
  "bio-printing",
  "BioBricks",
  "biofuels",
  "biological immortality",
  "biometrics",
  "biomimetics",
  "bionic contact lenses",
  "bioplastics",
  "bioremediation",
  "bioshelter",
  "Biosphere 2",
  "birth control",
  "Bitcoin",
  "Blu-ray Discs",
  "body implants",
  "brain implants",
  "brain transplantation",
  "brain-computer interfaces",
  "brain–computer interfaces",
  "BrainGate",
  "BrightSource Energy",
  "broadband",
  "cameras",
  "camouflage",
  "carbon fiber",
  "carbon nanotube field-effect transistors",
  "carbon nanotubes",
  "carbon neutral fuels",
  "caseless ammunition",
  "catalysts",
  "chimneys",
  "cinemas",
  "claytronics",
  "cloaking devices",
  "cloaks of invisibility",
  "closed ecological systems",
  "cloud robotics",
  "coatings",
  "cochlear implants",
  "cognitive radio",
  "coilguns",
  "colonization of the moon",
  "composite materials",
  "compressed air vehicles",
  "computer interfaces",
  "computer vision",
  "computer-generated holography",
  "computer-generated imagery",
  "concentrated solar power",
  "conductive polymers",
  "Contour Crafting",
  "contraception",
  "control systems",
  "cooling towers",
  "CPUs",
  "CRT displays",
  "cryogenics",
  "cryonics",
  "cryoprotectants",
  "cryptocurrencies",
  "cyborgs",
  "D-Shape",
  "data storage",
  "datacenters",
  "de-extinction",
  "dedicated short-range communications",
  "delivery drones",
  "dense plasma focus",
  "DESERTEC",
  "designer babies",
  "digital currencies",
  "digital image processing",
  "digital scent technology",
  "directed energy weapons",
  "distributed computing",
  "domed cities",
  "driverless cars",
  "drones",
  "dry ice",
  "e-democracy",
  "e-learning",
  "e-paper",
  "e-textiles",
  "electric cars",
  "electric double-layer capacitors",
  "electric vehicles",
  "electro hydrodynamic propulsion",
  "electroencephalography",
  "electrohydrodynamics",
  "electrolasers",
  "electromagnetic weapons",
  "electronic computing",
  "electronic countermeasures",
  "electronic devices",
  "electronics",
  "electrorheological fluid",
  "electrothermal-chemical technology",
  "energy harvesting",
  "ethnic bioweapons",
  "Exascale computing",
  "expendable launch systems",
  "EyeTap",
  "femtotechnology",
  "Ferro Liquid Displays",
  "ferroelectric RAM",
  "Field Emission Displays",
  "fishing",
  "flexible electronics",
  "flexible organic light-emitting diodes",
  "fluidic flight controls",
  "flying cars",
  "flywheel energy storage",
  "flywheels",
  "force fields",
  "fossil fuels",
  "fourth-generation optical discs",
  "full-genome sequencing",
  "fullerene",
  "fusion power",
  "fusion rockets",
  "fusion torch recycling",
  "gene doping",
  "gene therapy",
  "generation IV reactors",
  "genetic engineering",
  "genetically-modified foods",
  "geodesic domes",
  "glass",
  "GNU Radio",
  "Google Glass",
  "graphene",
  "graphics processing units",
  "gravitomagnetic fields",
  "green bullets",
  "greenhouses",
  "grid energy storage",
  "ground effect trains",
  "gynoid",
  "gyroscopes",
  "hand transplantation",
  "haptic suits",
  "hard disk drives",
  "head-mounted displays",
  "heads-up displays",
  "heat sinks",
  "High Altitude Platforms",
  "high temperature superconductivity",
  "high-capacity accumulators",
  "high-temperature superconductivity",
  "high-temperature superfluidity",
  "holographic data storage",
  "holographic displays",
  "holographic TV",
  "holography",
  "home fuel cells",
  "hoverboards",
  "hovercraft",
  "human enhancement",
  "human-computer interaction",
  "hydrogen vehicles",
  "hypereutectic alloys",
  "Hypereutectic pistons",
  "Hyperloop",
  "hypersonic transport",
  "IEEE 802.16m spectrum",
  "iGEM",
  "Immersive virtual reality",
  "in vitro meat",
  "incubators",
  "industrial agriculture",
  "inflatable space habitat",
  "insulin pump implants",
  "integrated circuits",
  "intelligent environments",
  "intelligent transportation systems",
  "interactive TV",
  "interferometric modulator display",
  "interstellar travel",
  "ion thrusters",
  "iSmell",
  "Jacquard weaving",
  "jet engines",
  "jet packs",
  "kevlar",
  "KiteGen",
  "laser propulsion",
  "laser TVs",
  "laser video displays",
  "Laser Weapon Systems",
  "laser weapons",
  "LCD screens",
  "Li-Fi",
  "life extension",
  "light field displays",
  "Lightweight Small Arms Technologies",
  "Lithium iron phosphate batteries",
  "Lithium-air batteries",
  "Lithium-ion batteries",
  "Lithium–sulfur batteries",
  "LiTraCon",
  "logistics",
  "LTE-advanced cellular networking",
  "machine translation",
  "machine vision",
  "Maglev trains",
  "magnetic levitation",
  "magnetic refrigeration",
  "magnetic tape data storage",
  "magnetoresistive random-access memory",
  "magnetorheological damper",
  "magnetorheological fluid",
  "male contraception",
  "mass drivers",
  "medical tricorders",
  "memristors",
  "mesh networks",
  "metal foam",
  "metamaterial cloaking",
  "metamaterials",
  "micro air vehicles",
  "microscopes",
  "millipede memory",
  "mind uploading",
  "miniaturized satellites",
  "missile defense",
  "mobile broadband",
  "mobile collaboration",
  "mobile TV",
  "molecular assemblers",
  "molecular electronics",
  "molecular nanotechnology",
  "molten salt batteries",
  "molten salt reactors",
  "movies",
  "MRAM",
  "MRI scanners",
  "multi-agent systems",
  "multi-function structures",
  "muon-catalyzed fusion",
  "nanoelectromechanical systems",
  "nanomaterials",
  "nanomedicines",
  "nanorobotics",
  "nanosensors",
  "nanowire batteries",
  "nantennas",
  "neural networks",
  "neuroinformatics",
  "neuroprosthetics",
  "nootropics",
  "NRAM",
  "nuclear fission power",
  "nuclear pulse propulsion",
  "ocean thermal energy conversion",
  "oil consumption",
  "OLED displays",
  "Oncolytic Viruses",
  "open data",
  "optical computing",
  "optical data storage",
  "optical storage",
  "optics",
  "organ printing",
  "organ transplantation",
  "organic light-emitting transistors",
  "organic solar cells",
  "pacemakers",
  "paralysis",
  "particle beam weapons",
  "particle swarm optimization",
  "passive houses",
  "pattern recognition",
  "personal genomics",
  "personal rapid transit",
  "personalized medicine",
  "pervasive computing",
  "phase-change memory",
  "phased-array optics",
  "photovoltaics",
  "picotechnology",
  "plant and fungus breeding",
  "plantibodies",
  "plasma stealth",
  "plasma weapons",
  "plasma windows",
  "powered exoskeletons",
  "precision agriculture",
  "programmable logic",
  "programmable matter",
  "programmable metallization cells",
  "prostheses",
  "prosthetics",
  "pure fusion weapons",
  "quadcopters",
  "quantum clocks",
  "quantum computing",
  "quantum cryptography",
  "quantum dot display",
  "quantum dot lasers",
  "quantum dots",
  "racetrack memory",
  "radar-absorbent material",
  "railguns",
  "rapid prototyping",
  "reconfigurable computing",
  "regenerative braking",
  "regenerative medicine",
  "renewable energy",
  "Reprogenetics",
  "research in the natural sciences",
  "resonant inductive coupling",
  "retinal implants",
  "reusable launch systems",
  "ReWalk",
  "RF and microwave filters",
  "RFID",
  "robotic surgery",
  "robots",
  "same-sex procreation",
  "screenless displays",
  "seawater greenhouses",
  "self healing material",
  "self-checkout",
  "self-reconfiguring modular robots",
  "Semantic Web Services",
  "Shanghai's Maglev Train",
  "shock absorbers",
  "signal processing",
  "Silicene",
  "Silicon–air battery",
  "simulated reality",
  "skin cell guns",
  "Sky Hook",
  "Skyrmion",
  "smart cities",
  "smart meters",
  "smartglasses",
  "smartphones",
  "smartstores",
  "Smell-O-Vision",
  "software-defined antenna",
  "software-defined radio",
  "solar cells",
  "solar roadways",
  "solar sails",
  "solar updraft tower",
  "sonic weapons",
  "space colonies",
  "space colonization",
  "space elevators",
  "space fountains",
  "space travel",
  "space-based solar power",
  "spaceplanes",
  "SpaceX's reusable launch system development program",
  "speech recognition",
  "Spintronics",
  "Star Trek Replicators",
  "stealth aircraft",
  "stealth technology",
  "steel",
  "stem cell treatments",
  "stereoscopic displays",
  "Strategies for Engineered Negligible Senescence",
  "subvocal recognition",
  "super-plastic alloys",
  "superalloys",
  "supercomputers",
  "superfluidity",
  "superplasticity",
  "supersonic transport",
  "surgical anaesthesia",
  "suspended animation",
  "swarm intelligence",
  "swarm robotics",
  "swept-volume displays",
  "synthetic biology",
  "synthetic diamond",
  "synthetic genomics",
  "T-RAM",
  "Talimogene laherparepvec",
  "telescopic pixel displays",
  "television",
  "Telework",
  "terraforming",
  "the Adaptive Compliant Wing",
  "the Aérotrain",
  "the AeroVironment Global Observer",
  "the AeroVironment Nano Hummingbird",
  "the artificial uterus",
  "the automobile",
  "the BAE Systems Demon",
  "the Bloom Energy Server",
  "the Blue Brain Project",
  "the CityCar",
  "the Concorde",
  "the Corporate Semantic Web",
  "the Duke Hospital PRT",
  "The Eden Project",
  "the electric car",
  "the electrical grid",
  "the electronic nose",
  "the Europe Gate",
  "the Google driverless car",
  "the High Energy Liquid Laser Area Defense System",
  "the holodeck",
  "the Hovertrain",
  "the HTC Evo 3D",
  "the Human Brain Project",
  "the Human Universal Load Carrier",
  "the Hydrogen economy",
  "the Hypertelescopes",
  "the internal combustion engine",
  "the Internet of Things",
  "the LOPES exoskeleton",
  "the MIT Car",
  "the Moller M400 Skycar",
  "the Nintendo 3DS",
  "the Nokia Morph",
  "the Oculus Rift",
  "the Physical Internet",
  "the pulse detonation engine",
  "the RepRap Project",
  "the Scramjet",
  "the Semantic Web Stack",
  "the Semantic Web",
  "the smart grid",
  "the Space Vest",
  "the SuperSmart Grid",
  "the technological singularity",
  "the Thorium fuel cycle",
  "the Tweel",
  "the Universal Software Radio Peripheral spec",
  "the Urban Aeronautics X-Hawk",
  "the Vactrain",
  "the Virgin Earth Challenge",
  "the Virtusphere",
  "the Vortex ring gun",
  "the wheel",
  "thermal copper pillar bumps",
  "thermoelectric power generation",
  "three-dimensional integrated circuits",
  "time-multiplexed optical shutters",
  "tires",
  "tissue engineering",
  "tooth regeneration",
  "transhumanism",
  "tricorders",
  "Tupolev Tu-144",
  "ultra high definition holographic discs",
  "unmanned aerial vehicles",
  "unmanned combat air vehicles",
  "unmanned ground vehicles",
  "unmanned space vehicles",
  "unmanned surface vehicles",
  "unmanned underwater vehicles",
  "unmanned vehicles",
  "utility fogs",
  "V-tex",
  "vertical farming",
  "video games",
  "viral videos",
  "virotherapy",
  "virtual reality",
  "virtual retinal displays",
  "visual prostheses",
  "vitrification",
  "volumetric displays",
  "Von Neumann universal constructors",
  "Vortex engines",
  "washing machines",
  "wearable computers",
  "Web 2.0",
  "Web 3.0",
  "Windows Holographic",
  "wireless energy transfer",
  "wireless long-range electric shock weapons",
  "WiTricity",
  "X-ray machines",
  "zero-energy buildings"
];

var inspirationWorkSlogans = [
  "Be so good they can't ignore you",
  "Success is no accident",
  "Love what you do",
  "Stay positive and happy",
  "Be happy now",
  "Sweat, determination, and hard work",
  "Stay true to yourself",
  "Never give up",
  "Keep your dreams alive",
  "Work like you don't need the money",
  "Work hard",
  "Stay positive",
  "Follow your passion",
  "Work hard, be kind",
  "It's commitment",
  "Strive",
  "Keep going",
  "Hard work means working hard",
  "There is no substitute for hard work",
  "Teamwork",
  "We're in this together",
  "No one ever drowned in sweat",
  "Let passion drive you",
  "Hard work helps",
  "Don't wish it was easier",
  "Embrace the pain, inherit the gain",
  "Everything yields to dilligence",
  "Together everyone achieves more",
  "There is no elevator to success",
  "One person can make a difference",
  "Make the days count",
  "Nothing worth having comes easy",
  "Work hard, stay humble",
  "The harder you work, the luckier you get",
  "Keep calm and work hard",
  "Work hard, be patient",
  "There is joy in work",
  "Hard work beats talent",
  "Do it the right way every day",
  "Let success make the noise"
];


var inspirationalQuotes = [
"The best preparation for tomorrow is doing your best today.",
"We must let go of the life we have planned, so as to accept the one that is waiting for us.",
"The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
"I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it.",
"Put your heart, mind, and soul into even your smallest acts. This is the secret of success.",
"Happiness is not something you postpone for the future; it is something you design for the present.",
"My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style.",
"Today I choose life. Every morning when I wake up I can choose joy, happiness, negativity, pain... To feel the freedom that comes from being able to continue to make mistakes and choices - today I choose to feel life, not to deny my humanity but embrace it.",
"Keep your face always toward the sunshine - and shadows will fall behind you.",
"Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
"Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.",
"Nothing is impossible, the word itself says 'I'm possible'!",
"What we think, we become.",
"Let us remember: One book, one pen, one child, and one teacher can change the world.",
"What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.",
"Let us sacrifice our today so that our children can have a better tomorrow.",
"As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them.",
"Someone is sitting in the shade today because someone planted a tree a long time ago.",
"Believe you can and you're halfway there.",
"Try to be a rainbow in someone's cloud.",
"We know what we are, but know not what we may be.",
"Change your thoughts and you change your world.",
"Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
"Perfection is not attainable, but if we chase perfection we can catch excellence.",
"It is during our darkest moments that we must focus to see the light.",
"Be not entangled in this world of days and nights; Thou hast another time and space as well.",
"Space is an inspirational concept that allows you to dream big.",
"Reach for the stars.",
"A place for everything, everything in its place.",
"The authentic self is the soul made visible.",
"From its brilliancy everything is illuminated.",
"A concerted effort to preserve our heritage is a vital link to our cultural, educational, aesthetic, inspirational, and economic legacies - all of the things that quite literally make us who we are.",
"I've been known to write 10 pages a day for 10 days running before I take a breath. I am not a disciplined writer. I'm one of those people who laughingly call themselves inspirational writers, which basically means someone who has no control over their own creative process.",
"The books that help you most are those which make you think that most. The hardest way of learning is that of easy reading; but a great book that comes from a great thinker is a ship of thought, deep freighted with truth and beauty.",
"Tears are often the telescope by which men see far into heaven.",
"You are always free to change your mind and choose a different future, or a different past.",
"If the world seems cold to you, kindle fires to warm it.",
"I hope that at the end of the seven years, people will say that I have been of some inspirational value to them at home in terms of inclusiveness and abroad, I look forward to representing Ireland.",
"We convince by our presence.",
"Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend. Non-being is the greatest joy.",
"We have it in our power to begin the world over again.",
"Nurture your minds with great thoughts. To believe in the heroic makes heroes.",
"The meaning I picked, the one that changed my life: Overcome fear, behold wonder.",
"If there were no night, we would not appreciate the day, nor could we see the stars and the vastness of the heavens. We must partake of the bitter with the sweet. There is a divine purpose in the adversities we encounter every day. They prepare, they purge, they purify, and thus they bless.",
"Inspirational leaders need to have a winning mentality in order to inspire respect. It is hard to trust in the leadership of someone who is half-hearted about their purpose, or only sporadic in focus or enthusiasm.",
"I believe in living today. Not in yesterday, nor in tomorrow.",
"Cherish your visions and your dreams as they are the children of your soul, the blueprints of your ultimate achievements.",
"In oneself lies the whole world and if you know how to look and learn, the door is there and the key is in your hand. Nobody on earth can give you either the key or the door to open, except yourself.",
"The undertaking of a new action brings new strength.",
"I am so fresh in soul and spirit that life gushes and bubbles around me in a thousand springs.",
"It is always the simple that produces the marvelous.",
"A human being has so many skins inside, covering the depths of the heart. We know so many things, but we don't know ourselves! Why, thirty or forty skins or hides, as thick and hard as an ox's or bear's, cover the soul. Go into your own ground and learn to know yourself there.",
"Your heart is full of fertile seeds, waiting to sprout.",
"The handicap of deafness is not in the ear; it is in the mind.",
"Look at a football field. It looks like a big movie screen. This is theatre. Football combines the strategy of chess. It's part ballet. It's part battleground, part playground. We clarify, amplify and glorify the game with our footage, the narration and that music, and in the end create an inspirational piece of footage.",
"Barack Obama's inspirational whoosh to the presidency in 2008 was unusual. Most campaigns are less exhilarating; indeed, they are downright disappointing - until someone wins.",
"God loves to help him who strives to help himself.",
"What were once only hopes for the future have now come to pass; it is almost exactly 13 years since the overwhelming majority of people in Ireland and Northern Ireland voted in favour of the agreement signed on Good Friday 1998, paving the way for Northern Ireland to become the exciting and inspirational place that it is today.",
"A man has to learn that he cannot command things, but that he can command himself; that he cannot coerce the wills of others, but that he can mold and master his own will: and things serve him who serves Truth; people seek guidance of him who is master of himself.",
"The truth is on the march and nothing will stop it.",
"The ideal life is in our blood and never will be still.",
"Every heart that has beat strongly and cheerfully has left a hopeful impulse behind it in the world, and bettered the tradition of mankind.",
"I believe there's an inner power that makes winners or losers. And the winners are the ones who really listen to the truth of their hearts.",
"It is only in sorrow bad weather masters us; in joy we face the storm and defy it.",
"Lord, grant that I may always desire more than I can accomplish.",
"Create each day anew.",
"Countless as the sands of the sea are human passions.",
"Plant thy foot firmly in the prints which His foot has made before thee.",
"The only thing that ultimately matters is to eat an ice-cream cone, play a slide trombone, plant a small tree, good God, now you're free.",
"I will always desire to play with Bruce Springsteen. He's the most inspirational, most dedicated, most committed and most focused artist I've ever seen. I like to be around people like that.",
"In fact, I wouldn't really call this a Gospel album, I call it more an inspirational album.",
"So I wanted to sing inspirational music, and that's exactly how I approached it - only the words have been changed to declare my relationship with God.",
"Had I not come out with an inspirational CD, you perhaps would have never known that I feel like I feel, that all songs, all the music I've ever done is a gift from God.",
"Deacon Jones has been the most inspirational person in my football career.",
"I am very conscious of who I am as an artist and as an inspirational person.",
"The single most important thing in a child's performance is the quality of the teacher. Making sure a child spends the maximum amount of time with inspirational teachers is the most important thing.",
"I'd like to one day be featured on a list of inspirational people who have made a difference in the world, whether it be helping underprivileged people or putting an end to the poaching of wildlife in Africa.",
"Since we launched the original 'Pop Idol' in England, I've remained close with Simon Fuller. Working as executive producer on 'American idol' for its first seven years not only was an inspirational journey into the heart of American pop culture, it opened my eyes to the untapped potential of the incredibly dynamic young people in this world.",
"President Obama called for a 'we' nation in his Inauguration Address. Art convenes. It is not just inspirational. It is aspirational. It pricks the walls of our compartmentalized minds, opens our hearts and makes us brave. And that's what we need most in our country today.",
"If my writing comes to a halt, I head to the shops: I find them very inspirational. And if I get into real trouble with my plot, I go out for a pizza with my husband.",
"Sport is something that is very inspirational for young people.",
"Lady Gaga is the present and the future. She is the most revolutionary and inspirational artist. She is fearless and daring.",
"By now, you've probably caught on to something: my mother is always standing by with just the right Scripture or inspirational saying to get me through any tough situation.",
"It is such a luxury to open a new book that's highly recommended by friends - either an inspirational yet humorously self-deprecating memoir, or a page-turning piece of fiction.",
"Benazir Bhutto was an inspirational leader and an inspirational woman.",
"When Bill Clinton ran in '92, and I listened to him, and I had of course known of his record from Arkansas, I found him extraordinarily inspirational, and I voted Democratic.",
"My goal in my career is to inspire people, is to get my music out there and have people enjoy it, and have people think of me as an inspirational artist.",
"There is a loftier ambition than merely to stand high in the world. It is to stoop down and lift mankind a little higher.",
"Men must live and create. Live to the point of tears.",
"Our ideals are our better selves.",
"It's a moment that I'm after, a fleeting moment, but not a frozen moment.",
"I am deliberate and afraid of nothing.",
"Too low they build, who build beneath the stars.",
"Show me your hands. Do they have scars from giving? Show me your feet. Are they wounded in service? Show me your heart. Have you left a place for divine love?",
"Once I knew only darkness and stillness... my life was without past or future... but a little word from the fingers of another fell into my hand that clutched at emptiness, and my heart leaped to the rapture of living.",
"I believe that one defines oneself by reinvention. To not be like your parents. To not be like your friends. To be yourself. To cut yourself out of stone.",
"Every charitable act is a stepping stone toward heaven.",
"Joy descends gently upon us like the evening dew, and does not patter down like a hailstorm.",
"I believe it is in my nature to dance by virtue of the beat of my heart, the pulse of my blood and the music in my mind.",
"There are glimpses of heaven to us in every act, or thought, or word, that raises us above ourselves.",
"Think with your whole body.",
"Let each man exercise the art he knows.",
"My mind's my kingdom.",
"We relish news of our heroes, forgetting that we are extraordinary to somebody too.",
"People tell you the world looks a certain way. Parents tell you how to think. Schools tell you how to think. TV. Religion. And then at a certain point, if you're lucky, you realize you can make up your own mind. Nobody sets the rules but you. You can design your own life.",
"And now, this is the sweetest and most glorious day that ever my eyes did see.",
"I arise full of eagerness and energy, knowing well what achievement lies ahead of me.",
"On the recollection of so many and great favours and blessings, I now, with a high sense of gratitude, presume to offer up my sincere thanks to the Almighty, the Creator and Preserver.",
"I would probably work with Drake as he is massively inspirational to me as a writer as well as an artist. If not him, then Susan Boyle!",
"I would say I'm an inspirational guidelines book. You can take my life story or scenarios or songs and relate to them and apply them to your everyday life.",
"Coming to Nashville has been so motivating and inspirational. Just watching people live and breathe their music and create something that they can feel from start to finish.",
"There have been many different artists that have been inspirational. I suppose the question is directed to what was the reason why I went into fantasy illustration.",
"My tastes and inspirational artists were always rather eclectic and diverse.",
"The flow of Guiness into the studio was inspirational as well as nutritive.",
"I've done a lot of albums and I kinda know when I'm onto something that was inspirational for me to record and create, and this was one of those projects where I really enjoyed making the album.",
"The best form of flattery is to be admired, imitated or respected. I've always felt proud our fans look up to us or feel we are inspirational.",
"I think that the reason for my success is that I am really not aspirational. I am inspirational in that the people at home feel like they can really relate to me.",
"I view art as an inspirational tool.",
"I grew up in a bookless house - my parents didn't read poetry, so if I hadn't had the chance to experience it at school I'd never have experienced it. But I loved English, and I was very lucky in that I had inspirational English teachers, Miss Scriven and Mr. Walker, and they liked us to learn poems by heart, which I found I loved doing.",
"Roosevelt's declaration that Americans had 'nothing to fear but fear itself' was a glorious piece of inspirational rhetoric and just as gloriously wrong.",
"I love a lot of the New York bands, but Patti Smith stands out. I just read 'Just Kids' and it's an inspirational, well-written account of an emerging New York artist in the late seventies.",
"I think if there's something one needs to change with oneself, it doesn't have to happen in the New Year. You can do that any time you please - not that it's not a good inspirational tactic for the people that it works for.",
"I think the end goal, hopefully, is to take advantage of the attention I've gotten along the way and use it for good and build some communities, and as I get older I can continue to do things and be surrounded by things that are inspirational to me.",
"Every song you're trying to find something that going to connect in different ways but for me the songs that I'm really drawn to are inspirational, songs that lift you and that everybody can relate to no matter where you're from.",
"The leaders who we admire who have been able to bring great change in the past - Gandhi, Martin Luther King, Nelson Mandela - they're all inspirational religious leaders and smart tacticians. It would be nice to find the Muslim Gandhi, wouldn't it?",
"You always draw inspiration from your family or your parents if they've proven to be inspirational. My mother is someone who's always been inspirational to me.",
"We all obviously need others to look up to, and be inspirational to us. Ford did a great job as far as putting the presidency back where it belonged, getting the trust back after Nixon. And President Reagan has been one of the most influential presidents.",
"Brand is not a product, that's for sure; it's not one item. It's an idea, it's a theory, it's a meaning, it's how you carry yourself. It's aspirational, it's inspirational.",
"I believe in the city as a natural human environment, but we must humanize it. It's art that will re-define public space in the 21st Century. We can make our cities diverse, inspirational places by putting art, dance and performance in all its forms into the matrix of street life.",
"I do a lot of inspirational talks for kids, to motivate them to change their lives and give them hope.",
"I think that's a great opportunity, to pick a script where you can build up a good skill. I think the main thing I look for when I look at scripts is if it's inspirational. If it's something that teenagers can relate to. And is it something that the audience is going to get something out of. If not, then it's really not worth doing.",
"We've been surrounded by images of space our whole lives, from the speculative images of science fiction to the inspirational visions of artists to the increasingly beautiful pictures made possible by complex technologies. But whilst we have an overwhelmingly vivid visual understanding of space, we have no sense of what space sounds like.",
"All my music is inspirational. You just gotta listen to the words and get what you can get out of it.",
"I think, aesthetically, car design is so interesting - the dashboards, the steering wheels, and the beauty of the mechanics. I don't know how any of it works, I don't want to know, but it's inspirational.",
"Better to be called something positive and inspirational than something negative.",
"I wrote '('Til) I Kissed You' about a girl I met in Australia. Her name was Lilian, and she was very, very inspirational. I was married, but... I wrote the song about her on the way back home.",
"I think 'Heroes of Cosplay' will show a lot of the positive things, like how much effort it takes to make a costume. These people on the show aren't taking shortcuts. As long as that effort gets through to the viewers, we will be inspirational. Then there will be people who watch the show that want to get in and hands-on make outfits.",
"I do like alternative rock and rap, but as far as inspirational, then I go full-on orchestra. It fills up your entire being.",
"I want to be an inspirational model. I want people to look at me and say, 'Wow, she looks healthy.'",
"My father, Oliver Hynes, was an educator. He was originally just a teacher, a very good one, but then he was promoted to be in charge of education for the entire area. He was always an inspirational teacher. He was my big personal supporter, always coming here for the Tony Awards. My mother, Carmel, was a homemaker.",
"I think anyone who has a passion for what they love to do, and who pursue it, is inspirational for me.",
"What they have done in Japan, which I find so inspirational, is they've brought the toilet out from behind the locked door. They've made it conversational. People go out and upgrade their toilet. They talk about it. They've sanitized it.",
"Silent pictures show us how we lived and what our attitudes were. And as an art form, they can be wonderfully entertaining and often inspirational.",
"I had hoped when my life was chronicled, it would be an inspirational story.",
"Who would have thought that a tap-dancing penguin would outpoint James Bond at the box office? And deserve to? Not that there's anything wrong with 'Casino Royale.' But 'Happy Feet' - written and directed by George Miller - is a complete charmer, even if, in the way of most family fare, it can't resist straying into the Inspirational.",
"I really think that it's disgusting that Paris is the only place where it is illegal for paps to follow you around. It actually took someone losing their life - Diana, an inspirational woman - and then it changed, but they still won't change it in London! It's horrible!",
"I want to be motivational and inspirational for everybody: my big aim is more women on bicycles.",
"It's as if inside the White House the belief in Obama's inspirational charisma is still such that every time the ugliness of brute politics intrudes, it's a startling revelation.",
"I thought 'Moulin Rouge' was inspirational, and 'Jesus Christ Superstar' I loved.",
"I'm very fond of the British cinema. I'm a big fan of Martin Campbell and Daniel Craig. I actually find Daniel very inspirational, especially on the physical side of things. He really inspired me to get back into shape when I started to add on a few pounds. I think he's a great role model.",
"Business gives you a massive high. Doing a great deal, coming up with an inspirational solution... It's very addictive. But it doesn't last long. In isolation, it's a bit sterile. It doesn't reward the soul.",
"I've lost count of the number of times that I've been approached by strangers wanting to tell me that they think I'm brave or inspirational, and this was long before my work had any kind of public profile.",
"I pull a lot of the stuff that I play off the rhythm tracks - and Keith Richards has been one of the main contributors to my inspirational playing.",
"I think Spain will always remain inspirational, and I think French cuisine will continue to be very French and yet very relevant with its time and keep evolving. But the last thing you want for it is to become too trendy and confusing. It has too much history.",
"This is just rap. I'm not trying to make people think I'm some sort of scientific wizard or inspirational poet.",
"The power of pop culture stories should not be underestimated, and there is an enormous potential for inspirational stories that can have a positive, transformative effect on our lives.",
"'All in With Laila Ali' is educational, inspirational, compelling programming profiling individuals that have reached for the sky, pushed themselves to the limit and did things that you would think were impossible.",
"Inside, I've got a real purist desire and dream about the music. I like the idea of being able to carve out a kind of magical, colourful, artistic, inspirational life. And the reality just turns out to be quite different, working with the business to bring this thing you have created into the world.",
"I always like a woman in power in politics. I think they're pretty inspirational in terms of looks to begin with. It's very calculated.",
"Hopefully, when people see 'Senna', they will understand why this inspirational story needed to be told, why it had to be made as a movie for the big screen, and why it is a film for everyone.",
"I am never without my lyric book. If anything inspirational happens, I have it there so nothing's forgotten.",
"You see countries like India really investing in their space program because they see it as inspirational and good for their economy.",
"The government will see that human spaceflight is useful - for science and the economy - and inspirational.",
"Every video I've made has an inspirational message behind it. Since day one, I thought, 'Okay, I want my audience to be, like, Disney members.' So if that's the case, I have to keep everything rated G.",
"I look up to a strong woman; maybe that's why I fell for Gaga. She works incredibly hard and is very strong and inspirational like Mom, with a great work ethic.",
"My initial goal for the 1984 opening ceremonies was a show that would be majestic, inspirational, and emotional - a 20 goosebump experience.",
"I'm a gay disabled man who has become very successful. I don't get up in the morning and think I'm inspirational; I just get up thinking that I love horses.",
"Thelonious Monk was one of the musicians I most connected with early on. I'm a huge Betty Carter fan, and the way that Abbey Lincoln and Shirley Horn grew immensely from the time they were young is so inspirational.",
"It is so inspirational, to see that in the world of Westeros, men are answering to women, and they are a force to be reckoned with. It's empowering, and it's inspirational as well, because you're just like, 'This is great!'",
"It really is an honor if I can be inspirational to a younger singer or person. It means I've done my job.",
"'Get along, go along' is not an inspirational philosophy, and only God knows how much moral cowardice it has covered up over the years. Serve your time, collect your chits, and cash 'em in for your home state? No, I'd say we could ask for more than that from our senators.",
"I knew, regardless of anything else, singing in front of an orchestra was going to be inspirational. It would feed me.",
"I look forward to making tangible and inspirational contributions to the Houston Technology Center's initiatives. HTC is an engine behind Houston's and Texas' continued growth.",
"What's on my playlist when I'm fighting is not so much hip-hop. Sometimes, it's something more inspirational. I get a chance to think about what I'm fighting for, like, my family. It takes me to that state because a lot of times, it's a spiritual warfare for me.",
"Traveling around the country, meeting fans and hearing their stories in person and on my radio show has reenergized my commitment to creating honest and inspirational content that not only serves my own creative purposes but can help and touch others as well.",
"I think being directed and mentored by someone as inspirational as Paul Feig not only improves my performance but, as a whole, makes it what it is.",
"I had an inspirational teacher at my junior school: Peter Nixon. He was enthusiastic, knowledgeable and slightly scary - a good combination for a teacher.",
"I did an A Level in Theatre Studies and had a really inspirational teacher, and then I just went on to university.",
"Although he's no longer with us, Steve Jobs is still inspirational to me, as he managed to find the balance between right brain/left-brain thinking that is crucial to building a creative technology business.",
"At the end of the day, the one commonality that both Hindi cinema and Hollywood share is that they are full of talented and inspirational people. Outside of this, there are many differences, from the scheduling and rehearsal to promotion and directing techniques.",
"Rap music's been around for too long now to be inspirational. The words are, but the music isn't.",
"Growing up, in church we had the homily; at home it's what I call the 'momily' - the inspirational and instructive mom-isms that every family has.",
"In sports teams, apart from talk of sporting prowess and the imparting of inspirational thought, an extraordinary amount of time is spent discussing, and flaunting, material possessions.",
"I love inspirational R&B, like Mary J. Blige and Jennifer Hudson. I want to do that. That kind of music stays with you.",
"If opportunity doesn't knock, build a door.",
"No act of kindness, no matter how small, is ever wasted.",
"I believe in pink. I believe that laughing is the best calorie burner. I believe in kissing, kissing a lot. I believe in being strong when everything seems to be going wrong. I believe that happy girls are the prettiest girls. I believe that tomorrow is another day and I believe in miracles.",
"If you believe in yourself and have dedication and pride - and never quit, you'll be a winner. The price of victory is high but so are the rewards.",
"A hero is someone who has given his or her life to something bigger than oneself.",
"Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.",
"All you need is the plan, the road map, and the courage to press on to your destination.",
"Every man's life is a fairy tale written by God's fingers.",
"Let us make our future now, and let us make our dreams tomorrow's reality.",
"The bird is powered by its own life and by its motivation.",
"Let your life lightly dance on the edges of Time like dew on the tip of a leaf.",
"It is in your moments of decision that your destiny is shaped.",
"To love means loving the unlovable. To forgive means pardoning the unpardonable. Faith means believing the unbelievable. Hope means hoping when everything seems hopeless.",
"Shoot for the moon and if you miss you will still be among the stars.",
"There are two ways of spreading light: to be the candle or the mirror that reflects it.",
"I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'",
"Turn your face to the sun and the shadows fall behind you.",
"Don't judge each day by the harvest you reap but by the seeds that you plant.",
"If you always put limit on everything you do, physical or anything else. It will spread into your work and into your life. There are no limits. There are only plateaus, and you must not stay there, you must go beyond them.",
"We can't help everyone, but everyone can help someone.",
"No matter what people tell you, words and ideas can change the world.",
"I will love the light for it shows me the way, yet I will endure the darkness because it shows me the stars.",
"When the sun is shining I can do anything; no mountain is too high, no trouble too difficult to overcome.",
"When we seek to discover the best in others, we somehow bring out the best in ourselves.",
"It is never too late to be what you might have been.",
"When you get into a tight place and everything goes against you, till it seems as though you could not hang on a minute longer, never give up then, for that is just the place and time that the tide will turn.",
"Your present circumstances don't determine where you can go; they merely determine where you start.",
"How wonderful it is that nobody need wait a single moment before starting to improve the world.",
"Follow your bliss and the universe will open doors where there were only walls.",
"Your personal life, your professional life, and your creative life are all intertwined. I went through a few very difficult years where I felt like a failure. But it was actually really important for me to go through that. Struggle, for me, is the most inspirational thing in the world at the end of the day - as long as you treat it that way.",
"Thinking: the talking of the soul with itself.",
"God always gives His best to those who leave the choice with him.",
"The power of imagination makes us infinite.",
"I thank you God for this most amazing day, for the leaping greenly spirits of trees, and for the blue dream of sky and for everything which is natural, which is infinite, which is yes.",
"The measure of who we are is what we do with what we have.",
"You must do the things you think you cannot do.",
"There is nothing impossible to him who will try.",
"Tears of joy are like the summer rain drops pierced by sunbeams.",
"Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.",
"Give light, and the darkness will disappear of itself.",
"Happiness is a butterfly, which when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you.",
"Throw your dreams into space like a kite, and you do not know what it will bring back, a new life, a new friend, a new love, a new country.",
"From a small seed a mighty trunk may grow.",
"Be brave enough to live life creatively. The creative place where no one else has ever been.",
"Two roads diverged in a wood and I - I took the one less traveled by, and that has made all the difference.",
"Keep your feet on the ground, but let your heart soar as high as it will. Refuse to be average or to surrender to the chill of your spiritual environment.",
"In a gentle way, you can shake the world.",
"If I have seen further than others, it is by standing upon the shoulders of giants.",
"Whoever is happy will make others happy too.",
"Keep all special thoughts and memories for lifetimes to come. Share these keepsakes with others to inspire hope and build from the past, which can bridge to the future.",
"The fact that I can plant a seed and it becomes a flower, share a bit of knowledge and it becomes another's, smile at someone and receive a smile in return, are to me continual spiritual exercises.",
"Prayer is man's greatest power!",
"Everyone has inside of him a piece of good news. The good news is that you don't know how great you can be! How much you can love! What you can accomplish! And what your potential is!",
"Today is the only day. Yesterday is gone.",
"If we did all the things we are capable of, we would literally astound ourselves.",
"Grace is the beauty of form under the influence of freedom.",
"Memories of our lives, of our works and our deeds will continue in others.",
"Once we believe in ourselves, we can risk curiosity, wonder, spontaneous delight, or any experience that reveals the human spirit.",
"Everyone here has the sense that right now is one of those moments when we are influencing the future.",
"How glorious a greeting the sun gives the mountains!",
"If a man does not keep pace with his companions, perhaps it is because he hears a different drummer. Let him step to the music which he hears, however measured or far away.",
"Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.",
"Tomorrow is the most important thing in life. Comes into us at midnight very clean. It's perfect when it arrives and it puts itself in our hands. It hopes we've learned something from yesterday.",
"Love is a fruit in season at all times, and within reach of every hand.",
"With self-discipline most anything is possible.",
"A champion is someone who gets up when he can't.",
"Your big opportunity may be right where you are now.",
"The things that we love tell us what we are.",
"The limits of the possible can only be defined by going beyond them into the impossible.",
"Only those who have learned the power of sincere and selfless contribution experience life's deepest joy: true fulfillment.",
"What makes the desert beautiful is that somewhere it hides a well.",
"Happiness is the natural flower of duty.",
"The best way out is always through.",
"Find out who you are and be that person. That's what your soul was put on this Earth to be. Find that truth, live that truth and everything else will come.",
"If you accept the expectations of others, especially negative ones, then you never will change the outcome.",
"Give light and people will find the way.",
"When deeds speak, words are nothing.",
"To the mind that is still, the whole universe surrenders.",
"Happiness resides not in possessions, and not in gold, happiness dwells in the soul.",
"Each day provides its own gifts.",
"Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.",
"Out of difficulties grow miracles.",
"Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.",
"The most authentic thing about us is our capacity to create, to overcome, to endure, to transform, to love and to be greater than our suffering.",
"Try to be like the turtle - at ease in your own shell.",
"I am not afraid of tomorrow, for I have seen yesterday and I love today!",
"Thought is the wind, knowledge the sail, and mankind the vessel.",
"When you have a dream, you've got to grab it and never let go.",
"Reach for it. Push yourself as far as you can.",
"Every story I create, creates me. I write to create myself.",
"Miracles are a retelling in small letters of the very same story which is written across the whole world in letters too large for some of us to see.",
"The world is full of magical things patiently waiting for our wits to grow sharper.",
"The only way to discover the limits of the possible is to go beyond them into the impossible.",
"We can change our lives. We can do, have, and be exactly what we wish.",
"Enthusiasm moves the world.",
"What we achieve inwardly will change outer reality.",
"I have always believed, and I still believe, that whatever good or bad fortune may come our way we can always give it meaning and transform it into something of value.",
"What great thing would you attempt if you knew you could not fail?",
"Everything you want is out there waiting for you to ask. Everything you want also wants you. But you have to take action to get it.",
"Belief creates the actual fact.",
"The only journey is the one within.",
"Live your beliefs and you can turn the world around.",
"A #2 pencil and a dream can take you anywhere.",
"As knowledge increases, wonder deepens.",
"Love the moment and the energy of that moment will spread beyond all boundaries.",
"I celebrate myself, and sing myself.",
"Wonder rather than doubt is the root of all knowledge.",
"Let us dream of tomorrow where we can truly love from the soul, and know love as the ultimate truth at the heart of all creation.",
"Let every dawn be to you as the beginning of life, and every setting sun be to you as its close.",
"A compliment is something like a kiss through a veil.",
"Yesterday we obeyed kings and bent our necks before emperors. But today we kneel only to truth, follow only beauty, and obey only love.",
"Every moment and every event of every man's life on earth plants something in his soul.",
"And when I breathed, my breath was lightning.",
"I know why I am here and my only real focused goal is to live each day to the fullest and to try and honor God and be an encouragement to others. What the future holds is firmly in God's hands, and I am very happy about that!",
"Learning how to be still, to really be still and let life happen - that stillness becomes a radiance.",
"The Wright brothers flew right through the smoke screen of impossibility.",
"Your ordinary acts of love and hope point to the extraordinary promise that every human life is of inestimable value.",
"I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.",
"Nothing makes one feel so strong as a call for help.",
"Nothing is worth more than this day.",
"Great hopes make great men.",
"Ideas shape the course of history.",
"Courage, my friends; 'tis not too late to build a better world.",
"Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.",
"I dwell in possibility.",
"From what we get, we can make a living; what we give, however, makes a life.",
"Whatever you vividly imagine, ardently desire, sincerely believe, and enthusiastically act upon... must inevitably come to pass!",
"I've been absolutely terrified every moment of my life - and I've never let it keep me from doing a single thing I wanted to do.",
"We sing inspirational songs, songs of praise and worship, and about how good and how big God is. We are magnifying the Lord.",
"It seems to me we can never give up longing and wishing while we are thoroughly alive. There are certain things we feel to be beautiful and good, and we must hunger after them.",
"Love and desire are the spirit's wings to great deeds.",
"There is nothing stronger in the world than gentleness.",
"Half a century ago, the amazing courage of Rosa Parks, the visionary leadership of Martin Luther King, and the inspirational actions of the civil rights movement led politicians to write equality into the law and make real the promise of America for all her citizens.",
"I said to the almond tree, 'Friend, speak to me of God,' and the almond tree blossomed.",
"God sleeps in the minerals, awakens in plants, walks in animals, and thinks in man.",
"Architecture is not an inspirational business, it's a rational procedure to do sensible and hopefully beautiful things; that's all.",
"Vitality shows in not only the ability to persist but the ability to start over.",
"I believe that if one always looked at the skies, one would end up with wings.",
"I used to make up stuff in my bio all the time, that I used to be a professional ice-skater and stuff like that. I found it so inspirational. Why not make myself cooler than I am?",
"Act like you expect to get into the end zone.",
"'Do What You Gotta Do' is a positive, inspirational song that says no matter what it is; whether you're up against challenges or trying to get your dreams and aspirations met, you should do what whatever you have to do shy of killing yourself or someone else.",
"Without craftsmanship, inspiration is a mere reed shaken in the wind.",
"Noble deeds that are concealed are most esteemed.",
"Most of us have far more courage than we ever dreamed we possessed.",
"It is by acts and not by ideas that people live.",
"And above all things, never think that you're not good enough yourself. A man should never think that. My belief is that in life people will take you at your own reckoning.",
"Light tomorrow with today!",
"Silence is the last thing the world will ever hear from me.",
"To me, the Seventies were very inspirational and very influential... With my whole persona as Snoop Dogg, as a person, as a rapper. I just love the Seventies style, the way all the players dressed nice, you know, kept their hair looking good, drove sharp cars and they talked real slick.",
"Every day we should hear at least one little song, read one good poem, see one exquisite picture, and, if possible, speak a few sensible words.",
"There are thousands of inspirational stories waiting to be told about young women who yearn for a great education. They are stories of struggle and stories of success, and they will inspire others to take action and work to change lives.",
"I have looked into your eyes with my eyes. I have put my heart near your heart.",
"What we need is more people who specialize in the impossible.",
"Of all human activities, man's listening to God is the supreme act of his reasoning and will.",
"We are here to make another world.",
"Of all things visible, the highest is the heaven of the fixed stars.",
"It is not ignorance but knowledge which is the mother of wonder.",
"Our time here is magic! It's the only space you have to realize whatever it is that is beautiful, whatever is true, whatever is great, whatever is potential, whatever is rare, whatever is unique, in. It's the only space.",
"The essential elements of giving are power and love - activity and affection - and the consciousness of the race testifies that in the high and appropriate exercise of these is a blessedness greater than any other.",
"Not on one strand are all life's jewels strung.",
"The most beautiful thing in the world is, of course, the world itself.",
"One of the things that I did before I ran for president is I was a professional speaker. Not a motivational speaker - an inspirational speaker. Motivation comes from within. You have to be inspired. That's what I do. I inspire people, I inspire the public, I inspire my staff. I inspired the organizations I took over to want to succeed.",
"Man never made any material as resilient as the human spirit.",
"For a gallant spirit there can never be defeat.",
"Like the United Nations, there is something inspirational about New York as a great melting pot of different cultures and traditions. And if this is the city that never sleeps, the United Nations works tirelessly, around the clock around the world.",
"Whatever ought to be, can be.",
"Personally, I can't see the appeal in trekking down to D.C. for a networking extravaganza, even if it is built around a special moment in American history. While I find the election of Barack Obama inspirational, I don't have a desire to memorialize it with overly effusive celebration.",
"This CD became something of a personal journey for me. The tone of the whole CD is uplifting and inspirational. It's an upper. We have enough downers in the world.",
"Lee's great gifts are teaching and inspirational guidance, not administration and management.",
"I wanted to do something inspirational for my children.",
"I do love to eavesdrop. It's inspirational, not only for subject matter but for actual dialogue, the way people talk.",
"I don't dislike rappers or hip-hop or people who like it. I went to the Def Jam tour in Manchester in the '80s when rap was inspirational. Public Enemy were awesome. But it's all about status and bling now, and it doesn't say anything to me.",
"You change your life by changing your heart.",
"The glow of one warm thought is to me worth more than money.",
"Hope is but the dream of those who wake.",
"I pray God may preserve your health and life many years.",
"Just don't give up trying to do what you really want to do. Where there is love and inspiration, I don't think you can go wrong.",
"Just as you wouldn't leave the house without taking a shower, you shouldn't start the day without at least 10 minutes of sacred practice: prayer, meditation, inspirational reading.",
"You never know when some small thing will lead to a big idea. Travel is very inspirational - but it's in the ordinary that I find my themes of love and work and family.",
"Ah, but a man's reach should exceed his grasp, Or what's a heaven for?",
"Teachers need to be more inspirational. But it's also up to engineering to make itself more interesting.",
"Be faithful to that which exists within yourself.",
"Hope is some extraordinary spiritual grace that God gives us to control our fears, not to oust them.",
"Faith is love taking the form of aspiration.",
"If you could only love enough, you could be the most powerful person in the world.",
"Mankind is made great or little by its own will.",
"Just what future the Designer of the universe has provided for the souls of men I do not know, I cannot prove. But I find that the whole order of Nature confirms my confidence that, if it is not like our noblest hopes and dreams, it will transcend them.",
"I want to make this world perfect.",
"When Maurice touched a keyboard, it was like something from a movie, magical. He would always give you something from a movie, and you'd go, what did you just play... immediately inspirational writings, amazing. That's what we're going to miss.",
"'Star Wars' is fun, its exciting, its inspirational, and people respond to that. It's what they want.",
"A lot of America is kind of done. People have been making films about it for 100 years. Everything to me feels used up. But Jo-Burg feels unbelievably inspirational to me.",
"I have amazing friends who have led inspirational lives.",
"Books are challenging and inspirational to me.",
"Almost every college playwright or sketch or improv comedian was sort of aware of Christopher Durang - even kids in high school. His short plays were so accessible to younger people and I think that was inspirational to me.",
"I try not to put anything political on the forefront of what I'm trying to do creatively. At the same time, I do think it's wonderful when I hear people say that it's inspirational that I'm an Indian woman on camera. My life is very diverse, and my friends are a diverse group of people.",
"It's inspirational to see someone who is dying smile.",
"If you look at a building by Mies van der Rohe, it might look very simple, but up close, the sheer quality of construction, materials and thought are inspirational.",
"Reading was very important to me as a kid. It was very inspirational to me. I went to a school where that wasn't encouraged so much, but my parents encouraged that, and it has made me part of who I am.",
"I'm not an inspirational quote kind of person.",
"If someone says 'grunge' or 'punk,' you know what the sound is, but if you say 'No Wave,' it's kind of mysterious. That was the most interesting part and should have been the most inspirational thing about it... here's this collective sonic insanity, and none of it sounds anything alike.",
"When I was working at the Sprint store, I got laid off. I was bummed out, but I stayed positive. I used the money I had earned while working there to make my first album. Without that job, maybe 'Corazon Sin Cara' would never had been made. It's a very inspirational story.",
"I grew up in a very spiritual home in a Liberty City neighborhood of Miami, FL. I was raised in the church, and my mother was a very inspirational person in my life.",
"Somewhere, something incredible is waiting to be known.",
"You don't look out there for God, something in the sky, you look in you.",
"I love those who yearn for the impossible.",
"If the doors of perception were cleansed everything would appear to man as it is, infinite.",
"One today is worth two tomorrows.",
"As people are walking all the time, in the same spot, a path appears.",
"Only I can change my life. No one can do it for me.",
"Life is 10% what happens to you and 90% how you react to it.",
"Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
"Good, better, best. Never let it rest. 'Til your good is better and your better is best.",
"He conquers who endures.",
"Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
"Infuse your life with action. Don't wait for it to happen. Make it happen. Make your own future. Make your own hope. Make your own love. And whatever your beliefs, honor your creator, not by passively waiting for grace to come down from upon high, but by doing what you can to make grace happen... yourself, right now, right down here on Earth.",
"It always seems impossible until it's done.",
"Always do your best. What you plant now, you will harvest later.",
"With the new day comes new strength and new thoughts.",
"It does not matter how slowly you go as long as you do not stop.",
"The past cannot be changed. The future is yet in your power.",
"Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.",
"Failure will never overtake me if my determination to succeed is strong enough.",
"Setting goals is the first step in turning the invisible into the visible.",
"You can't cross the sea merely by standing and staring at the water.",
"Quality is not an act, it is a habit.",
"Keep your eyes on the stars, and your feet on the ground.",
"If you can dream it, you can do it.",
"Accept the challenges so that you can feel the exhilaration of victory.",
"Consult not your fears but your hopes and your dreams. Think not about your frustrations, but about your unfulfilled potential. Concern yourself not with what you tried and failed in, but with what it is still possible for you to do.",
"Your talent is God's gift to you. What you do with it is your gift back to God.",
"The secret of getting ahead is getting started.",
"The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.",
"If you fell down yesterday, stand up today.",
"Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step.",
"I want to be motivational and inspirational for everybody: my big aim is more women on bicycles.",
"Give Obama a script he has made his own, and he is the motivational speaker to end all speakers. Tony Robbins cloned with Honest Abe.",
"Our subliminal mental processes operate outside awareness because they arise in these portions of our mind that are inaccessible to our conscious self; their inaccessibility is due to the architecture of the brain rather than because they have been subject to Freudian motivational forces like repression.",
"I was perceived to be a first- to third-rounder. I kind of had a tough junior year and fell to the fifth round. At that time, it was motivational.",
"Be kind whenever possible. It is always possible.",
"You are never too old to set another goal or to dream a new dream.",
"When something is important enough, you do it even if the odds are not in your favor.",
"If you want to conquer fear, don't sit home and think about it. Go out and get busy.",
"Problems are not stop signs, they are guidelines.",
"Never, never, never give up.",
"We may encounter many defeats but we must not be defeated.",
"Don't watch the clock; do what it does. Keep going.",
"A creative man is motivated by the desire to achieve, not by the desire to beat others.",
"Set your goals high, and don't stop till you get there.",
"Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.",
"There is only one corner of the universe you can be certain of improving, and that's your own self.",
"If you're going through hell, keep going.",
"Well done is better than well said.",
"Start where you are. Use what you have. Do what you can.",
"What you get by achieving your goals is not as important as what you become by achieving your goals.",
"Aim for the moon. If you miss, you may hit a star.",
"We should not give up and we should not allow the problem to defeat us.",
"Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist. Be curious.",
"You are not here merely to make a living. You are here in order to enable the world to live more amply, with greater vision, with a finer spirit of hope and achievement. You are here to enrich the world, and you impoverish yourself if you forget the errand.",
"You can never quit. Winners never quit, and quitters never win.",
"The key is to keep company only with people who uplift you, whose presence calls forth your best.",
"Never give up, for that is just the place and time that the tide will turn.",
"In order to succeed, we must first believe that we can.",
"What you do today can improve all your tomorrows.",
"Perseverance is not a long race; it is many short races one after the other.",
"Be Impeccable With Your Word. Speak with integrity. Say only what you mean. Avoid using the word to speak against yourself or to gossip about others. Use the power of your word in the direction of truth and love.",
"Things do not happen. Things are made to happen.",
"Without hard work, nothing grows but weeds.",
"If you don't like how things are, change it! You're not a tree.",
"Expect problems and eat them for breakfast.",
"The way to get started is to quit talking and begin doing.",
"Beginning today, treat everyone you meet as if they were going to be dead by midnight. Extend to them all the care, kindness and understanding you can muster, and do it with no thought of any reward. Your life will never be the same again.",
"Motivation is the art of getting people to do what you want them to do because they want to do it.",
"When you reach the end of your rope, tie a knot in it and hang on.",
"There is no passion to be found playing small - in settling for a life that is less than the one you are capable of living.",
"A good plan violently executed now is better than a perfect plan executed next week.",
"By failing to prepare, you are preparing to fail.",
"Either you run the day or the day runs you.",
"You can't expect to hit the jackpot if you don't put a few nickels in the machine.",
"I know where I'm going and I know the truth, and I don't have to be what you want me to be. I'm free to be what I want.",
"Do you want to know who you are? Don't ask. Act! Action will delineate and define you.",
"Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality. Searching and learning is where the miracle process all begins.",
"Do something wonderful, people may imitate it.",
"We are taught you must blame your father, your sisters, your brothers, the school, the teachers - but never blame yourself. It's never your fault. But it's always your fault, because if you wanted to change you're the one who has got to change.",
"I'd rather attempt to do something great and fail than to attempt to do nothing and succeed.",
"The harder the conflict, the more glorious the triumph.",
"Do not wait to strike till the iron is hot; but make it hot by striking.",
"Knowing is not enough; we must apply. Willing is not enough; we must do.",
"A goal is a dream with a deadline.",
"If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success.",
"Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along.",
"The more man meditates upon good thoughts, the better will be his world and the world at large.",
"The people who influence you are the people who believe in you.",
"No bird soars too high if he soars with his own wings.",
"The ultimate aim of the ego is not to see something, but to be something.",
"Perseverance is failing 19 times and succeeding the 20th.",
"Even if you fall on your face, you're still moving forward.",
"We aim above the mark to hit the mark.",
"Go for it now. The future is promised to no one.",
"I attribute my success to this - I never gave or took any excuse.",
"Opportunity does not knock, it presents itself when you beat down the door.",
"I am not afraid... I was born to do this.",
"Do your work with your whole heart, and you will succeed - there's so little competition.",
"Act as if what you do makes a difference. It does.",
"Pursue one great decisive aim with force and determination.",
"There's a way to do it better - find it.",
"The most effective way to do it, is to do it.",
"Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.",
"Arriving at one goal is the starting point to another.",
"Do the one thing you think you cannot do. Fail at it. Try again. Do better the second time. The only people who never tumble are those who never mount the high wire. This is your moment. Own it.",
"I learned that we can do anything, but we can't do everything... at least not at the same time. So think of your priorities not in terms of what activities you do, but when you do them. Timing is everything.",
"It is very important to know who you are. To make decisions. To show who you are.",
"Every exit is an entry somewhere else.",
"March on. Do not tarry. To go forward is to move toward perfection. March on, and fear not the thorns, or the sharp stones on life's path.",
"I've worked too hard and too long to let anything stand in the way of my goals. I will not let my teammates down and I will not let myself down.",
"If you think you can do it, you can.",
"You simply have to put one foot in front of the other and keep going. Put blinders on and plow right ahead.",
"Small deeds done are better than great deeds planned.",
"The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.",
"You just can't beat the person who never gives up.",
"To be a good loser is to learn how to win.",
"Don't give up. Don't lose hope. Don't sell out.",
"I've found that luck is quite predictable. If you want more luck, take more chances. Be more active. Show up more often.",
"If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.",
"There is nothing deep down inside us except what we have put there ourselves.",
"We make the world we live in and shape our own environment.",
"The will to succeed is important, but what's more important is the will to prepare.",
"I think people who are creative are the luckiest people on earth. I know that there are no shortcuts, but you must keep your faith in something Greater than You, and keep doing what you love. Do what you love, and you will find the way to get it out to the world.",
"Never give in and never give up.",
"Change your life today. Don't gamble on the future, act now, without delay.",
"Deserve your dream.",
"They can conquer who believe they can.",
"Either I will find a way, or I will make one.",
"You need to overcome the tug of people against you as you reach for high goals.",
"Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it. Pry the door open or, if need be, wedge your foot in that door and keep it open.",
"Don't think, just do.",
"You can't build a reputation on what you are going to do.",
"You can't wait for inspiration. You have to go after it with a club.",
"Follow your inner moonlight; don't hide the madness.",
"You have to make it happen.",
"Always desire to learn something useful.",
"When you fail you learn from the mistakes you made and it motivates you to work even harder.",
"Step by step and the thing is done.",
"Determine never to be idle. No person will have occasion to complain of the want of time who never loses any. It is wonderful how much may be done if we are always doing.",
"One finds limits by pushing them.",
"It's always too early to quit.",
"Never complain and never explain.",
"After a storm comes a calm.",
"Learn from the past, set vivid, detailed goals for the future, and live in the only moment of time over which you have any control: now.",
"Set your sights high, the higher the better. Expect the most wonderful things to happen, not in the future but right now. Realize that nothing is too good. Allow absolutely nothing to hamper you or hold you up in any way.",
"You will never win if you never begin.",
"Whatever you want in life, other people are going to want it too. Believe in yourself enough to accept the idea that you have an equal right to it.",
"The first question which the priest and the Levite asked was: 'If I stop to help this man, what will happen to me?' But... the good Samaritan reversed the question: 'If I do not stop to help this man, what will happen to him?'",
"Motivation will almost always beat mere talent.",
"Be gentle to all and stern with yourself.",
"When one must, one can.",
"Wherever you are - be all there.",
"Many are called but few get up.",
"I don't believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be.",
"Never retreat. Never explain. Get it done and let them howl.",
"Begin to be now what you will be hereafter.",
"You must take action now that will move you towards your goals. Develop a sense of urgency in your life.",
"Decide what you want, decide what you are willing to exchange for it. Establish your priorities and go to work.",
"A somebody was once a nobody who wanted to and did.",
"One way to keep momentum going is to have constantly greater goals.",
"There is progress whether ye are going forward or backward! The thing is to move!",
"True happiness involves the full use of one's power and talents.",
"Do whatever you do intensely.",
"Who seeks shall find.",
"No matter how many goals you have achieved, you must set your sights on a higher one.",
"The more things you do, the more you can do.",
"Success is the only motivational factor that a boy with character needs.",
"Your heaviest artillery will be your will to live. Keep that big gun going.",
"Crave for a thing, you will get it. Renounce the craving, the object will follow you by itself.",
"God always strives together with those who strive.",
"Be thine own palace, or the world's thy jail.",
"Set yourself earnestly to see what you are made to do, and then set yourself earnestly to do it.",
"Fear of failure, it's the greatest motivational tool. It drives me and drives me and drives me.",
"I'm thrilled to continue my partnership with U by Kotex for Generation Know while helping to empower girls. I've always been a motivational resource for my younger sisters and hope I can positively impact and inspire other young girls too.",
"The hardships that I encountered in the past will help me succeed in the future.",
"To know oneself, one should assert oneself.",
"I am not a has-been. I am a will be.",
"To begin, begin.",
"One of the things that I did before I ran for president is I was a professional speaker. Not a motivational speaker - an inspirational speaker. Motivation comes from within. You have to be inspired. That's what I do. I inspire people, I inspire the public, I inspire my staff. I inspired the organizations I took over to want to succeed.",
"Poverty was the greatest motivating factor in my life.",
"Don't fight the problem, decide it.",
"The weeds keep multiplying in our garden, which is our mind ruled by fear. Rip them out and call them by name.",
"I went to a motivational training course once, a course of self-discovery, and I found out after a week that my fear - it was not a fear of not being accepted - was a very violent fear of failure.",
"Giving back, doing motivational speeches and stuff like that, that's always made me feel good. If you repeatedly go out there, and you are the change that you want to see, then that's what you are.",
"The more we do, the more we can do.",
"Earl Nightingale has inspired more people toward success and fortune than any other motivational speaker on the planet.",
"Go big or go home. Because it's true. What do you have to lose?",
"I was motivated to be different in part because I was different.",
"Get action. Seize the moment. Man was never intended to become an oyster.",
"Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you.",
"You never know what motivates you.",
"I like motivational books, because I like the go-getting American spirit - your destiny is in your own hands, life is what you make it, don't accept your limitations, jump before you're pushed, leap before you look.",
"I like to put on hardcore when I have to clean my apartment, which I hate to do, but it's motivational. I like old heavy metal when I'm outside working on my car. Music has definite functions for me.",
"Religious speech is extreme, emotional, and motivational. It is anti-literal, relying on metaphor, allusion, and other rhetorical devices, and it assumes knowledge within a community of believers.",
"Hitch your wagon to a star.",
"If you ask me what I came into this life to do, I will tell you: I came to live out loud.",
"Follow your dreams, work hard, practice and persevere. Make sure you eat a variety of foods, get plenty of exercise and maintain a healthy lifestyle.",
"A will finds a way.",
"I've always tried to go a step past wherever people expected me to end up.",
"You create your opportunities by asking for them.",
"Big shots are only little shots who keep shooting.",
"We need to accept that the commandments of God aren't just a long list of good ideas. They aren't 'life hacks' from an Internet blog or motivational quotes from a Pinterest board.",
"Know or listen to those who know.",
"Only the educated are free.",
"From my tribe I take nothing, I am the maker of my own fortune.",
"Either move or be moved.",
"My first book was called, 'Mountain, Get Out of My Way,' where I did an autobiographical sketch, if you will, looking back at myself and looking back at things in my life, and juxtaposing them against things that are happening in other people's lives and trying to be motivational.",
"Leap, and the net will appear.",
"I'm going to write a book, continue acting, continue motivational speaking and just share with people who I am and what I've learned in my second chance of life and pass it on to people in their first chance of life.",
"I don't know what it's like to have a typical father figure. He's not the dad who's going to take me to the beach and go swimming, but he's such a motivational person.",
"The dog that trots about finds a bone.",
"I can, therefore I am.",
"You have to learn the rules of the game. And then you have to play better than anyone else.",
"What is called genius is the abundance of life and health.",
"In motivating people, you've got to engage their minds and their hearts. I motivate people, I hope, by example - and perhaps by excitement, by having productive ideas to make others feel involved.",
"I come to win.",
"The turning point was when I hit my 30th birthday. I thought, if really want to write, it's time to start. I picked up the book How to Write a Novel in 90 Days. The author said to just write three pages a day, and I figured, I can do this. I never got past Page 3 of that book.",
"The wise does at once what the fool does at last.",
"I know not age, nor weariness nor defeat.",
"If you don't ask, you don't get.",
"Do not weep; do not wax indignant. Understand.",
"Always continue the climb. It is possible for you to do whatever you choose, if you first get to know who you are and are willing to work with a power that is greater than ourselves to do it.",
"There is always room at the top.",
"Oh, I would love to be a motivational speaker. I have pulled myself out of a million potholes, and I can see the potholes ahead of me. That doesn't mean that I could always do that so perfectly for my own life. I totally fall in potholes.",
"I really believe that everyone has a talent, ability, or skill that he can mine to support himself and to succeed in life.",
"How do you know you're going to do something, untill you do it?",
"Marvin's Motivational Moments actually started as something that was actually therapeutic for me. I would sit up late at night after my wife passed trying to adjust to being alone.",
"I realized I love motivating and I love empowering and I love inspiring people. I did that as an athlete for 18 years, and I am able to do that as a motivational speaker now as well as doing work on television.",
"If you've got a talent, protect it.",
"My dad is too cute. Every morning, he sends me one motivational quote. I have a folder full of all his quotes.",
"As long as I'm not selling out the people that ride or die with me, I'm glad I'm not an MC. I'm a motivational speaker. I'm not that rapper dude.",
"I started doing motivational tours. I've seen all kinds of people, from the CEOs to the lowest executive, opening up to their fears. We don't introspect as much as we should.",
"To be wholly devoted to some intellectual exercise is to have succeeded in life.",
"One may miss the mark by aiming too high as too low.",
"One day, I got so disgusted that I sat down and wrote a list called 'Justin's list of things to do before he kicks the bucket.' I wrote it for myself and shortened it to 'Justin's Bucket List.' It was there on the wall, not as a story idea but as a motivational tool for myself, which actually ended up working pretty well.",
"I've a great family, two children to take care of. Then, of course, I do commentary for TV. I do speak about various women's issues around the world - like LGBT, motivational speeches. I have a lot on my plate right now. But eventually, yes, I would like to pass on the knowledge and something that I would like to do.",
"I want to build a legacy at the WWE, but I definitely want to continue to grow the Bella Empire. I want it to go beyond the ring. I would love to be a motivational speaker.",
"People always accuse me of being motivational in a way, like it was a bad thing, but that's just how I was raised. My mom raised me in a positive environment, with lots of love in my heart, and that reflects in my music.",
"I've always thought of acting as more of an exercise in empathy, which is not to be confused with sympathy. You're trying to get inside a certain emotional reality or motivational reality and try to figure out what that's about so you can represent it.",
"I'm a motivational speaker.",
"Typically, if you reward something, you get more of it. You punish something, you get less of it. And our businesses have been built for the last 150 years very much on that kind of motivational scheme.",
"I believe that any type of education can be great, but an education about ourselves can create something wonderful. I am a comedian, but people have called me a motivational speaker. I don't really consider myself that at all.",
"Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.",
"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it.",
"Learn to enjoy every minute of your life. Be happy now. Don't wait for something outside of yourself to make you happy in the future. Think how really precious is the time you have to spend, whether it's at work or with your family. Every minute should be enjoyed and savored.",
"There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
"Stay positive and happy. Work hard and don't give up hope. Be open to criticism and keep learning. Surround yourself with happy, warm and genuine people.",
"A dream doesn't become reality through magic; it takes sweat, determination and hard work.",
"Success is the result of perfection, hard work, learning from failure, loyalty, and persistence.",
"Work hard for what you want because it won't come to you without a fight. You have to be strong and courageous and know that you can do anything you put your mind to. If somebody puts you down or criticizes you, just keep on believing in yourself and turn it into something positive.",
"Stay true to yourself, yet always be open to learn. Work hard, and never give up on your dreams, even when nobody else believes they can come true but you. These are not cliches but real tools you need no matter what you do in life to stay focused on your path.",
"It's all about quality of life and finding a happy balance between work and friends and family.",
"Keep your dreams alive. Understand to achieve anything requires faith and belief in yourself, vision, hard work, determination, and dedication. Remember all things are possible for those who believe.",
"Leadership is not about a title or a designation. It's about impact, influence and inspiration. Impact involves getting results, influence is about spreading the passion you have for your work, and you have to inspire team-mates and customers.",
"Work like you don't need the money. Love like you've never been hurt. Dance like nobody's watching.",
"Choose a job you love, and you will never have to work a day in your life.",
"Let the beauty of what you love be what you do.",
"Never stop fighting until you arrive at your destined place - that is, the unique you. Have an aim in life, continuously acquire knowledge, work hard, and have perseverance to realise the great life.",
"A birthday is just another day where you go to work and people give you love. Age is just a state of mind, and you are as old as you think you are. You have to count your blessings and be happy.",
"Success isn't always about greatness. It's about consistency. Consistent hard work leads to success. Greatness will come.",
"The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.",
"To be a champion, I think you have to see the big picture. It's not about winning and losing; it's about every day hard work and about thriving on a challenge. It's about embracing the pain that you'll experience at the end of a race and not being afraid. I think people think too hard and get afraid of a certain challenge.",
"Work hard, stay positive, and get up early. It's the best part of the day.",
"Perseverance is the hard work you do after you get tired of doing the hard work you already did.",
"Follow your passion, be prepared to work hard and sacrifice, and, above all, don't let anyone limit your dreams.",
"Feelings aroused by the touch of someone's hand, the sound of music, the smell of a flower, a beautiful sunset, a work of art, love, laughter, hope and faith - all work on both the unconscious and the conscious aspects of the self, and they have physiological consequences as well.",
"Youth is the gift of nature, but age is a work of art.",
"The greatest thing about where my life is right now is it's very relaxed and chill. I'm just hanging out, being myself and doing my work.",
"There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
"Great things in business are never done by one person. They're done by a team of people.",
"I love those who can smile in trouble, who can gather strength from distress, and grow brave by reflection. 'Tis the business of little minds to shrink, but they whose heart is firm, and whose conscience approves their conduct, will pursue their principles unto death.",
"Making money is art and working is art and good business is the best art.",
"Happiness does not come from doing easy work but from the afterglow of satisfaction that comes after the achievement of a difficult task that demanded our best.",
"Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
"A satisfied customer is the best business strategy of all.",
"If people like you, they'll listen to you, but if they trust you, they'll do business with you.",
"My philosophy is it's none of my business what people say of me and think of me. I am what I am, and I do what I do. I expect nothing and accept everything. And it makes life so much easier.",
"Before you can become a millionaire, you must learn to think like one. You must learn how to motivate yourself to counter fear with courage. Making critical decisions about your career, business, investments and other resources conjures up fear, fear that is part of the process of becoming a financial success.",
"Ideas pull the trigger, but instinct loads the gun.",
"The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency. The second is that automation applied to an inefficient operation will magnify the inefficiency.",
"A passionate belief in your business and personal objectives can make all the difference between success and failure. If you aren't proud of what you're doing, why should anybody else be?",
"Details create the big picture.",
"In the business world, the rearview mirror is always clearer than the windshield.",
"Information technology and business are becoming inextricably interwoven. I don't think anybody can talk meaningfully about one without the talking about the other.",
"A brand for a company is like a reputation for a person. You earn reputation by trying to do hard things well.",
"A business that makes nothing but money is a poor business.",
"There is only one boss. The customer. And he can fire everybody in the company from the chairman on down, simply by spending his money somewhere else.",
"We're all working together; that's the secret.",
"There is always space for improvement, no matter how long you've been in the business.",
"There's nobody in the business strong enough to scare me.",
"Do what you love to do and give it your very best. Whether it's business or baseball, or the theater, or any field. If you don't love what you're doing and you can't give it your best, get out of it. Life is too short. You'll be an old man before you know it.",
"Sales are contingent upon the attitude of the salesman - not the attitude of the prospect.",
"Commitment, belief and positive attitude are all important if you're going to be a success, whether you're in sports, in business or, as in my case, anthropology.",
"Business has only two functions - marketing and innovation."
];
