(function(){var e=void 0,g=true,i=null,j=false;function k(){return function(){}}function l(a){return function(){return this[a]}}function m(a){return function(){return a}}var n,q=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function s(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ba:da;return s.apply(i,arguments)}function ea(a,b){function c(){}c.prototype=b.prototype;a.la=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ga(){}
function ha(a,b,c){switch(typeof b){case "string":ia(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==i){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var f="",h=0;h<d;h++)c.push(f),ha(a,b[h],c),f=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(h=b[f],typeof h!="function"&&(c.push(d),ia(f,c),c.push(":"),ha(a,h,c),d=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ja={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ma=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ia(a,b){b.push('"',a.replace(ma,function(a){if(a in ja)return ja[a];var b=a.charCodeAt(0),f="\\u";b<16?f+="000":b<256?f+="00":b<4096&&(f+="0");return ja[a]=f+b.toString(16)}),'"')};var na={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},oa={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function pa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function qa(a,b){var c="",d=ra(encodeURIComponent(a));d.splice(b||5,d.length);t(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ra(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,f=2562383102,h=271733878,o=3285377520,r=[],p,E,H,R,X,fa=Math.ceil((a.length/4+2)/16),ca=[fa],N=0,D;N<fa;N++){ca[N]=[];for(p=0;p<16;p++)ca[N][p]=a.charCodeAt(N*64+p*4)<<24|a.charCodeAt(N*64+p*4+1)<<16|a.charCodeAt(N*64+p*4+2)<<8|a.charCodeAt(N*64+p*4+3)}N=(a.length-1)*8;a=fa-1;ca[a][14]=Math.floor(N/Math.pow(2,32));ca[a][15]=N&4294967295;for(N=0;N<fa;N++){for(D=0;D<16;D++)r[D]=
ca[N][D];for(D=16;D<80;D++)r[D]=(r[D-3]^r[D-8]^r[D-14]^r[D-16])<<1|(r[D-3]^r[D-8]^r[D-14]^r[D-16])>>>31;a=c;p=d;E=f;H=h;R=o;for(D=0;D<80;D++)X=Math.floor(D/20),X=(a<<5|a>>>27)+(X==0?p&E^~p&H:X==1?p^E^H:X==2?p&E^p&H^E&H:p^E^H)+R+b[X]+r[D]&4294967295,R=H,H=E,E=p<<30|p>>>2,p=a,a=X;c=c+a&4294967295;d=d+p&4294967295;f=f+E&4294967295;h=h+H&4294967295;o=o+R&4294967295}return[c,d,f,h,o]}
function sa(a){var b=q.navigator,c=q.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];t(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=q.performance;d=d.concat([b&&b.now?b.now():"",document.title,q.location.href,u(),pa()]);return d.concat(a||[]).join()}function v(a,b,c){var d=Array.prototype.slice,f=d.call(arguments,2);return function(){return a.apply(b,f.concat(d.call(arguments)))}}
function w(a){return typeof a!=="undefined"}function ta(a){return a.replace(/^www\./,"")}var ua=/^((https?\:)?(\/\/))/i;function va(a){return a.replace(ua,"")}var wa=/^((https?\:)?(\/\/))?[^\/]*/;function xa(a){return a.replace(wa,"")}var ya=/\#.*/;function za(a){return a.replace(ya,"")}var Aa=/\?[^\#]*/;function Ba(a){return a.toLowerCase()}var Ca=/\/+((\?|\#).*)?$/;function Da(a){return a.replace(Ca,"$1")}function Ea(a){return a.replace(Aa,"")}
function Fa(a,b){if(a===b)return 0;var c=i;t([Ba,Da,va,xa,za,Ea],function(d,f){a=d(a);b=d(b);if(a===b)return c=f+1,j});return c}function x(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function Ga(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function Ha(a){return typeof a==="number"}function Ia(a){return typeof a==="string"}function Ja(a){return typeof a==="function"}
function Ka(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function u(){return(new Date).getTime()}function La(a){return encodeURIComponent(a)}function Ma(){return q.location.protocol==="https:"?"https:":"http:"}function t(a,b){if((!!a&&a.constructor===Object)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}function Na(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}
function Oa(a){var b=q.pSUPERFLY_video,a=Na(b,a);if(a>-1)return b[a]}function Pa(a){return a===e?0:u()-a}function Qa(a,b){var c,d,f="c"+Math.round(Math.random()*1E9);d=250;a+=(a.indexOf("?")>-1?"&":"?")+(c||"callback")+"=_cb_call."+f;c=document.createElement("script");var h=Ra(f,c);c.id=f;c.type="text/javascript";c.charset="UTF-8";c.src=a;var o=document.getElementsByTagName("head");if(o=o&&o[0]){var r=q._cb_call||(q._cb_call={});d=setTimeout(Sa(b,h),d);r[f]=Ta(b,h,d);o.appendChild(c)}}
function Sa(a,b){return function(){b();a(e,"TIMEOUT")}}function Ta(a,b,c){return function(d){b(c);a(d)}}function Ra(a,b){return function(c){c&&clearTimeout(c);setTimeout(function(){b&&b.parentNode&&b.parentNode.removeChild(b)},0);var d=q._cb_call,f=j;if(d&&(c?delete d[a]:d[a]=Ua,t(d,function(){f=g;return j}),!f))try{delete q._cb_call}catch(h){q._cb_call=e}}}function Ua(){}
function Va(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,f=b.length;d<=f;d++)c[d]=[d];for(var h=0,o=a.length;h<=o;h++)c[0][h]=h;for(var r,p,E,d=1;d<=f;d++)for(h=1;h<=o;h++)r=d-1,p=h-1,E=c[r][p],b.charAt(r)==a.charAt(p)?c[d][h]=E:(p=c[d][p]+1,r=c[r][h]+1,E+=2,c[d][h]=Math.min(p,r,E));return c[b.length][a.length]}function Wa(a){return a===e?0:u()-a}function y(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}
var Xa,Ya=q.setInterval,Za=q.clearInterval,$a=q.setTimeout,ab=q.clearTimeout;function bb(a,b){return Ya(a,b)}function cb(a){switch(a){case e:return"undefined";case "":return"empty";default:return a}}function db(a){switch(a){case "undefined":break;case "empty":return"";default:return a}};function eb(a,b){var c,b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");var d=[];c=c.getElementsByTagName(b);for(var f=c.length;f--;)c[f].getAttribute(a)&&d.push(c[f]);return d}function fb(a,b,c){c=c||"";if(a===e)a=j;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?j:fb(a.parentNode,b,c)}return a}
function gb(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=eb("data-cb-scroll-element"))&&a.length)return a[0][c];if(Ha(q[b]))return q[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function hb(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function ib(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function jb(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var d=a.ownerDocument.documentElement,f=0,h=w(c)?c+1:-1;Ia(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&f!==h;){if(c(a))return a;a=a.parentNode;f++}return i}
function kb(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function lb(a){a=a||window.event;return!a?i:jb(a.target||a.srcElement,kb,10)}function mb(a,b){var c=document.createElement(a);t(b,function(a,b){c.setAttribute(b,a)});return c};function nb(){this.na={};this.Va=1}function z(a,b,c,d){a.Va++;a.na[b]=a.na[b]||{};a.na[b][a.Va]=[c,d];return a.Va}function ob(a,b){if(Ia(b))a.na[b]=e,delete a.na[b];else if(Ha(b)){var c=g;t(a.na,function(a){t(a,function(f,h){if(parseInt(h,10)===b)return a[h]=e,delete a[h],c=j});return c})}}nb.prototype.xa=function(a,b){if(this.na[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];t(this.na[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
nb.prototype.addEventListener=function(a,b){var c=z(this,a,b);b._cbEventId=c};nb.prototype.removeEventListener=function(a,b){this.na[a]&&this.na[a][b._cbEventId]&&this.na[a][b._cbEventId][0]===b&&ob(this,b._cbEventId)};var A=new nb;var B={};
B.H=function(){B.Qb?B.sb("pageload"):(B.Tc=[{target:q,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:q,event:"resize"},{target:document.body,event:"mousedown"}],B.yb=i,B.Ia=i,B.Pb={},B.Ob={},B.Ac={},B.Bb={},t(B.Tc,function(a){var b=a.event;x(a.target,b,function(a){B.sb.call(B,b,a)})}),z(A,"f",function(){B.sb("focus")}),B.sb("pageload"),x(document.body,"click",function(a){(a=lb(a))&&A.xa("c",a)},g),x(document.body,"contextmenu",function(a){(a=lb(a))&&
A.xa("r",a)}),B.Qb=g)};B.$c=function(){var a,b=B.Ac.keydown;if(b===e)return j;b=u()-b;return b<=(a||15E3)&&b>=0};B.Ya=function(a,b){var c=B.Bb[a];if(!c)return"";var b=b||u(),d,f=0;t(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(f|=1<<d)});c=("0000"+f.toString(16)).slice(-4);return c=="0000"?"":c};B.ae=function(){B.Bb={}};B.qc=100;
B.sb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}B.he(a);if(B.yb===i)B.Nc(a);else if(!B.Ia||na[B.Ia]<na[a]||oa[B.Ia]<oa[a])B.Ia=a};B.he=function(a){var b=u();B.Ac[a]=b;var c=B.Bb[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();B.Bb[a]=c};
B.Nc=function(a){B.yb=$a(B.fd,B.qc);A.xa("a");B.Pb[a]!==i&&ab(B.Pb[a]);B.Ob[a]!==i&&ab(B.Ob[a]);B.Mc(a,B.Pb,na,"i");B.Mc(a,B.Ob,oa,"j")};B.Mc=function(a,b,c,d){b[a]=$a(function(){ab(b[a]);delete b[a];var c=j;t(b,function(){c=g;return j});c||A.xa(d)},c[a]+B.qc)};B.fd=function(){ab(B.yb);B.yb=i;if(B.Ia)B.Nc(B.Ia),B.Ia=i};var pb,qb,rb,sb,tb;(function(){var a,b;t(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof q.document[a]==="boolean")return b=c,j});b!==e&&(sb=a,tb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),rb=b+"visibilitychange")})();var ub=j;function vb(){ub=tb&&q.document[tb]==="prerender"?g:j}function wb(){qb=g;A.xa("f")}function xb(){qb=j;A.xa("b")}
function yb(a,b,c){q.addEventListener?q.addEventListener(a,c,j):q.document.attachEvent&&q.document.attachEvent(b,c)}function zb(){var a=g;q.document.hasFocus&&(a=q.document.hasFocus());var b=j;sb&&(b=q.document[sb]);return a&&!b}function Ab(){zb()?wb():xb()}function Bb(a){vb();if(ub){var b=j,c=function(){b||(vb(),ub||(b=g,a(),q.window.setTimeout(function(){q.document.removeEventListener(rb,c,j)},100)))};q.document.addEventListener(rb,c,j)}else a()};function Cb(){this.k=q._sf_async_config||{};this.uc=v(this.Gc,this)}Cb.prototype.H=function(){this.Ic=0};Cb.prototype.Gc=k();Cb.prototype.fb=function(a){if(!ub){var b=this.uc,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};Cb.prototype.wa=function(){this.uc=i};function Db(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),t(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Eb(a,b){var c="",d=q.location.href.match(/[^?]+[?]([^#]+).*/);if(d){var d=Db(d[1]),f=b||a;d[f]&&(c=d[f])}return encodeURIComponent(c)}function Fb(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Gb(a){var b=[];t(Hb,function(c){var d=a[c];w(d)&&(Object.prototype.toString.call(d)==="[object Array]"?t(d,function(a){b.push(c+"="+a)}):d&&d.constructor===Object?t(d,function(a,c){b.push(c+"="+a)}):((d+"").length||c=="r")&&b.push(c+"="+d))});b.push("_");return b.join("&")}
function Ib(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=q.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var f=Fb(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||d.href,h=f.indexOf("?");h===-1&&(h=f.indexOf("#"));if(h===-1)h=f.length;h=f.lastIndexOf("/",h);a=h===-1?
"/"+a:f.substr(0,h)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Fb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function Jb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function C(a,b,c){a[b]=a[b]||c}function Kb(a,b){for(var c=q[a]||[];c.length;)b(c.shift());q[a]={push:b}}function Lb(a){t(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=Db(b.src.split("?")[1]),C(a,"uid",b.uid),C(a,"domain",b.domain),j})}function Mb(a,b){return a[b]?encodeURIComponent(a[b]):""}function Nb(a){var b={};t(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};var F={};F.cd=function(){try{F.create("_cb_test","1",1);var a=F.F("_cb_test");F.remove("_cb_test");return a==="1"}catch(b){return j}};F.F=function(a){a+="=";var b="";t(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
F.create=function(a,b,c){var d=q._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(u()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};F.remove=function(a){return F.F(a)?F.create(a,"",-86400):""};var G={};G.Y=function(a){var b=q._sf_async_config;if(!a&&b&&b.noCookies)return i;if(G.Y.Hb!==e)return G.Y.Hb;var a=u()+"",c,d;try{if((d=q.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return G.Y.Hb=d}catch(f){}return G.Y.Hb=i};G.F=function(a){var b=G.Y();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&u()>c)?(G.remove(a),""):b.getItem(a)||""};
G.create=function(a,b,c){var d=G.Y();if(d){var f=new Date;f.setTime(u()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",f.getTime())}catch(h){}}};G.remove=function(a){var b=G.Y();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Ob(a){this.ub=a||"";this.gd=G.Y()!==i||F.cd();this.ic=j;Pb(this)}n=Ob.prototype;n.isSupported=l("gd");
function Pb(a){if(!F.F("_cb_ls")){var b=G.Y()!==i,c=F.F("_SUPERFLY_lockout");c&&t(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,g)});var d=F.F("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,g),F.remove("_chartbeat3"));b&&((b=F.F("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,g),(b=F.F("_chartbeat5"))&&a.create("_chartbeat5",b,60,g));F.create("_cb_ls","1",34128E3)}}function Qb(a){var b=a.ic;a.ic=j;return b}
n.create=function(a,b,c,d){a=d?a:this.ub+a;(G.Y()?G:F).create(a,b,c);G.Y()&&F.create(a,b,c)};n.update=function(a,b,c,d,f,h,o){a=d?a:this.ub+a;f=Ia(f)?f:"::";d=(d=this.F(a,g))?d.split(f):[];if(o&&d.length){var r=o(b),p=Na(d,function(a){return o(a)===r});p!==-1&&d.splice(p,1)}d.push(b);for(Ha(h)&&d.length>h&&d.splice(0,d.length-h);d.length>1&&d.join(f).length>4E3;)d.shift();this.create(a,d.join(f),c,g)};
n.F=function(a,b){var a=b?a:this.ub+a,c=(G.Y()?G:F).F(a);if(!c&&G.Y()&&(c=F.F(a))&&F.F("_cb_ls")){this.ic=g;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}G.create(a,c,d)}return c};n.remove=function(a,b){a=b?a:this.ub+a;(G.Y()?G:F).remove(a);G.Y()&&F.remove(a)};function Rb(a){var b=i;if(a&&(b=Sb()))return b;var c=q.location,b=Tb(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Sb(){var a=i;t(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=Ib(b.href),a=Tb(b.pathname)+b.search+b.hash,j});return a}
for(var Ub={},Vb=0;Vb<81;Vb++)Ub["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Vb)]=g;function Wb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Ub[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function Tb(a){if(!Ia(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Wb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function I(a,b){var c=J();return w(b)&&!w(c[a])?b:c[a]}function J(){w(q._cb_shared)||(q._cb_shared={});return q._cb_shared};var K={Wc:{IDLE:0,Vc:1,Uc:2,Db:3},Xc:{IDLE:0,Vc:1,Uc:2,Db:3},pa:0,qa:0};K.H=function(){if(!K.Qb)z(A,"a",K.pd,K),z(A,"i",K.td,K),z(A,"f",K.rd,K),z(A,"b",K.qd,K),z(A,"j",K.sd,K),K.Qb=g};K.J=function(){return K.pa};K.nd=function(){return K.qa};K.pd=function(){K.pa===1?K.Ea(3):K.pa===0&&K.Ea(2);K.qa===1?K.Da(3):K.qa===0&&K.Da(2)};K.td=function(){K.pa===3?K.Ea(1):K.pa===2&&K.Ea(0)};K.sd=function(){K.qa===3?K.Da(1):K.qa===2&&K.Da(0)};K.rd=function(){(K.pa===0||K.pa===2)&&K.Ea(3);(K.qa===0||K.qa===2)&&K.Da(3)};
K.qd=function(){K.pa===3?K.Ea(2):K.pa===1&&K.Ea(0);K.qa===3?K.Da(2):K.qa===1&&K.Da(0)};K.Ea=function(a){K.pa=a;A.xa("s",a)};K.Da=function(a){K.qa=a;A.xa("x",a)};function Xb(a,b){this.Nb=a||e;this.Wb=b||e;this.Pa=this.ua=0;this.zc=v(this.yd,this);this.hc=this.ra=i}n=Xb.prototype;n.H=function(){this.Pa=this.ua=0;this.ra=i;this.hc=z(A,"s",this.$a,this);this.$a(K.J())};n.$a=function(a){Za(this.ra);this.ra=i;if(a===K.Wc.Db)this.ra=Ya(this.zc,1E3)};n.yd=function(){if(this.Nb===e||this.Nb())this.ua++,this.Pa++,this.Wb&&this.Wb()};n.terminate=function(){Za(this.ra);this.ra=i;ob(A,this.hc)};n.wa=function(){this.terminate();this.Wb=this.Nb=e};function Yb(a,b){Xb.call(this,a,b)}ea(Yb,Xb);Yb.prototype.H=function(){this.Pa=this.ua=0;this.ra=i;this.hc=z(A,"x",this.$a,this);this.$a(K.nd())};Yb.prototype.$a=function(a){Za(this.ra);this.ra=i;if(a===K.Xc.Db)this.ra=Ya(this.zc,1E3)};function L(){Cb.call(this);this.Ma=[];this.q=new Ob(this.Pc);this.q.remove("_SUPERFLY_nosample");this.ma=new Xb;this.Ja=new Yb;this.Yb=v(this.cb,this);x(q,"unload",this.Yb);Bb(v(this.H,this))}ea(L,Cb);n=L.prototype;n.ec=g;
n.H=function(){L.la.H.call(this);this.ob=this.Qa=0;this.Fa=u();this.Ca=qa(Zb(this));this.cc=g;this.qb=72E5;if(this.ec){var a=+this.k.sessionLength;if(!isNaN(a))this.qb=a*6E4}a=I("d");if(!a){var a=[],b=this.q.F("_chartbeat2",g);b.length>0&&(a=b.split("."));a.length>5&&(a=[]);var b=u(),c=this.q.F("_cb",g);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var d=b-+(a[1]||0),f=b-+(a[2]||0);J().n=c&&d>18E5&&f<2592E6?0:1;d=a[4];if(!(f=f>18E5))if($b(this))f=j;else{var f=ac(this),f=decodeURIComponent(f),f=bc(f)||f,
h;h=cc(this);h=decodeURIComponent(h);h=bc(h)||h;f=f!==h}if(!d||f)d=qa(Zb(this)),a[4]=d,this.q.remove("_cb_svref",g);f="1";h=a&&+a[2];d=a&&a[3];if(a&&h&&d)if(f=Math.abs((Ka(b)-Ka(h))/864E5)){f=Math.min(f,16)-1;for(h="";f--;)h+=0;f=(d+h+"1").slice(-16)}else f=d;d=f;c||(c=this.k.utoken||qa(Zb(this),3),a[1]=b);a[2]=b;a[3]=d;this.k.utoken=this.hb;this.q.create("_cb",c,34128E3,g);this.q.create("_chartbeat2",a.join("."),34128E3,g);a[0]=c;J().d=a}this.qe=a.join(".");var o;c=+a[1];d=+a[2];if((b=a[3])&&c&&
d)o=(Math.min((Math.abs((Ka(d)-Ka(c))/864E5)||0)+1,16,b.length)-1).toString(16),o+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.yc=o;this.Tb=I("n",1);this.hb=a[0];this.de=a[4];this.ce=cc(this);this.q.create("_cb_svref",cc(this)||"null",1800,g);this.ma.H();this.Ja.H();K.H();B.H();pb||(qb=zb(),rb&&q.document.addEventListener&&q.document.addEventListener(rb,Ab,j),yb("focus","onfocusin",wb),yb("blur","onfocusout",xb),qb&&wb(),pb=g);this.bb=0;this.Zc=z(A,"a",this.Bd,this)};
function dc(a){if(!a.q.F("_SUPERFLY_lockout")&&!ub)a.Ad?a.wb():(a.Ad=g,!q._sf_async_config&&!q._cbq?(a.tb=v(a.wb,a),x(q,"load",a.tb)):a.wb())}n.wb=function(){this.eb=ec();B.H();this.nb=bb(v(this.oa,this),15E3);this.oa()};
n.oa=function(){var a=this.ma.Pa,a=this.k.reading&&+this.k.reading||a>0;if(this.ob<this.Qa&&!a)this.ob++;else{var b;if(Xa===e)b=q.navigator.userAgent,Xa=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Xa;b&&!a?this.ob++:(a?this.Qa=0:this.Gb(),this.ob=0,this.Ma.push(0),this.Ma.length>18&&this.Ma.shift(),this.ec&&u()-this.Fa>=this.qb?this.terminate():this.Ua())}};
n.Gc=function(){this.Ma.push(1);var a=0;t(this.Ma,function(b){a+=b});a<3?(this.cc=g,this.Gb()):(this.terminate(),this.q.create("_SUPERFLY_lockout","1",600))};n.cb=k();n.Bd=function(){var a=fc(this);this.bb=Math.max(this.bb,a)};function fc(a){return Math.floor(gb(!!a.k.scrollElement))}n.Gb=function(){var a=this.Qa;this.Qa=a=a?Math.min(a*2,16):1};n.lb=function(){this.cb();this.terminate()};n.Oc=function(){this.H();dc(this)};
function $b(a){if(a.k.virtualReferrer)return g;if(gc(a))return j;a=document.referrer.indexOf("://"+q.location.hostname+"/");return a!=-1&&a<9}function gc(a){var b=a.k.referrerOverrideQueryParam,c="";t(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),j});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}
function ac(a){a=a.k.virtualReferrer||gc(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=Ib(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=Tb(b.pathname),a=Jb(b)}return encodeURIComponent(a)}function hc(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Zb(a){a=[ac(a),ib("Width"),ib("Height")];return sa(a)}
function ic(a){var b=[],c=a.q.F("_chartbeat4");c&&(t(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.q.remove("_chartbeat4"));return b}function cc(a){a=a.q.F("_cb_svref",g)||ac(a)||"null";a==="null"&&(a="");return a}function bc(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?i:a[1]}function ec(){var a=q.performance&&q.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return Ha(b)&&b?Ha(a)&&a>b?a-b:u()-b:-1}
n.terminate=function(){this.ma.terminate();this.Ja.terminate();ob(A,this.Zc);this.tb!==e&&Ga(q,"load",this.tb);Za(this.nb);J().d=e;J().n=e};n.wa=function(){this.terminate();Ga(q,"unload",this.Yb);this.Yb=this.tb=this.q=this.Ma=this.k=i;this.ma.wa();this.ma=i;this.Ja.wa();this.Ja=i;L.la.wa.call(this)};function jc(a){for(var b=I("m")||[];b.length;)a(b.shift());a={push:a};J().m=a};function kc(a){var b=a.offsetLeft,c=a.offsetTop,d=lc(a);b+=d.x;c+=d.y;for(var f=j,d=a.offsetParent;a&&a!==e&&a!==document.body;){if(a===d)d=lc(a),b+=a.offsetLeft+d.x,c+=a.offsetTop+d.y,d=a.offsetParent;if(mc(a,["position"]).position==="fixed"){f=g;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function mc(a,b){var c={},d,f;q.getComputedStyle?d=q.getComputedStyle(a,i):a.currentStyle?f="currentStyle":a.style&&(f="style");t(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[f][b]});return c}var nc=/matrix(3d)?\((.*)\)/;function lc(a){var b={x:0,y:0},a=mc(a,["transform"]).transform;if(!Ia(a))return b;var c=a.match(nc);if(!c)return b;var a=c[2].split(", "),d;w(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};function oc(){var a=q.location.href,a=a.replace(/-{2,}/g,"-"),a=Ib(a);a.pathname=Tb(a.pathname);return a}
function pc(a){var b=F.F("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var f,h=oc(),o=Jb(h);t(b,function(a,b){var h=a.split(","),p=Va(o,decodeURIComponent(h[0]));if(p===0)return c=h,d=b,j;if(f===e||p<f)f=p,c=h,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+qc(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),h=decodeURIComponent(c[1]),r=c[2];c.splice(0,3);for(var p=c.length/2,E=0;E<p;E++)a.push({ne:b,origin:h,Ra:r,jd:c[E*2],ie:c[E*2+1]});
return a}function qc(a){var b="",c;if(!(a&&a.constructor===Object))return b;a.Dc&&(c=new Date,c.setTime(c.getTime()+a.Dc),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function rc(a){var b=a.topStorageDomain,a=a.domain,c=q.location.hostname;return b?b:sc(c,a)?a:c.replace(/^www\./,"")}function sc(a,b){if(a===b)return g;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return g}
function tc(a,b,c,d){this.ld=a;this.kd=b;this.je=c;this.Ra=d};function uc(a,b){for(var c=b||document.documentElement,d=[],f=i,h=a,o,r,p,E,H,R;h&&h!==c;){o=h.nodeName.toLowerCase();f=h;r=f.nodeName;if((h=h.parentNode)&&h!==document.documentElement){p=h.children;E=0;for(H=0,R=p.length;H<R;H++){if(f===p[H]){o+="["+(1+H-E)+"]";break}p[H].nodeName!==r&&E++}}d.unshift(o)}return d.join("/")};function vc(){this.Pc="_t_";L.call(this)}ea(vc,L);n=vc.prototype;
n.H=function(){vc.la.H.call(this);Lb(this.k);var a=q.location;C(this.k,"mabServer","mabping.chartbeat.net");C(this.k,"title",document.title);C(this.k,"domain",a.hostname);C(this.k,"path",Rb(!!this.k.useCanonical));this.ja=ta(a.hostname);this.k.domain=ta(this.k.domain);this.ge=rc(this.k);this.Xa=this.pb=j;this.vc=[];var b=this,a=pc({domain:"."+this.ge,Dc:6E4,path:"/"});if(a!==i)this.pb=g,t(a,function(a){b.vc.push(new tc(a.origin,a.jd,a.ie,a.Ra))});this.Ec=0;this.xb=i;jc(v(this.xd,this))};
n.Ua=function(){var a=this.ma.ua,b=wc(this),c,d=this;this.pb&&t(this.vc,function(f){c=b+"&x="+f.kd+"&v="+f.je+"&ml="+f.Ra+"&xo="+f.ld+"&e="+a;d.fb(c)});!this.Xa&&this.xb&&xc(this,this.xb);this.Xa=g};n.wb=function(){this.eb=ec();B.H();if(this.pb)this.nb=bb(v(this.oa,this),500);this.oa()};n.oa=function(){var a,b;this.Xa?(a=this.ma.ua,b=this.Ec*15,a-b>=15&&(this.Ua(),this.Ec+=1),a>=45&&this.terminate()):this.Ua()};
function wc(a){var b=a.k;return Ma()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.ja)+"&u="+a.hb+"&c="+Math.round((u()-a.Fa)/600)/100}n.cb=k();n.ee=function(a){var b=a.d,c=i;b!==i&&(c={fc:b.s,Ra:b.g,Cc:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.Xa?xc(this,a):this.xb=a};
function xc(a,b){var c=wc(a),d=b.status,f=b.data;if(d=="s"&&f!==i){var h=v(a.fb,a);f.fc&&f.fc.constructor===Object&&t(f.fc,function(a,b){h(c+"&x="+b+"&v="+a+"&ml="+f.Ra+"&e=-1")});Object.prototype.toString.call(f.Cc)==="[object Array]"&&t(f.Cc,function(a){h(c+"&me=3&ml="+f.Ra+"&x="+a)})}else d=="e"&&a.fb(c+"&me="+b.code)}n.xd=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],f=a.shift();f==="t"?this.ee.apply(this,a):f==="v"&&this.be.apply(this,a)}};
n.lb=function(){J().m=[];w(this.lc)&&this.lc();vc.la.lb.call(this)};n.be=function(a){this.lc=a};n.terminate=function(){this.lc=this.oe=e;this.xb=i;this.Xa=this.pb=e;vc.la.terminate.call(this)};if(!q.pSUPERFLY_mab){var yc=new vc,zc={};zc.evps=v(yc.lb,yc);zc.svps=v(yc.Oc,yc);q.pSUPERFLY_mab=zc;dc(yc)};var Ac,Bc,Cc;
function Dc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);Ec();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=w(e)?e:{},b.src=a,a=mb("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],w(e)?e.appendChild(a):b&&b.appendChild(a)}}
function Ec(){ab(Bc);Bc=e;Ga(q,"message",Dc);Cc&&Cc.parentNode&&Cc.parentNode.removeChild(Cc);Cc=e};function Fc(){var a=q._sf_async_config&&q._sf_async_config.domain;if(a&&!Ac){Ac=g;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);x(q,"message",Dc);Bc=$a(Ec,1E4);var b=w(e)?e:{};b.src=a;a=mb("iframe",b);a.style.display="none";w(e)?e.appendChild(a):document.body&&document.body.appendChild(a);Cc=a}}
function Gc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=G.Y(g),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Fc(),Ga(q,"message",Gc))}};function Hc(){"postMessage"in window&&x(q,"message",v(this.ud,this));L.call(this);Kb("_cbq",v(this.Lc,this))}ea(Hc,L);
Hc.prototype.H=function(){Hc.la.H.call(this);var a=this.hb;J().u=a;a=this.Ca;J().t=a;this.Fb=i;Lb(this.k);a=q.location;C(this.k,"pingServer","ping.chartbeat.net");C(this.k,"title",document.title);C(this.k,"domain",a.hostname);this.k.path=this.k.path?Tb(this.k.path):Rb(!!this.k.useCanonical);this.ja=ta(a.hostname);this.k.domain=ta(this.k.domain);this.ad=z(A,"c",this.Fd,this);this.bd=z(A,"r",this.Gd,this);this.Oa=i};Hc.prototype.Yc=function(a){this.Fb=a};
Hc.prototype.cb=function(){this.q.update("_chartbeat4",["t="+this.Ca,"E="+this.ma.ua,"EE="+this.Ja.ua,"x="+fc(this),"c="+Math.round((u()-this.Fa)/600)/100,"y="+ib("Height"),"w="+hb()].join("&"),60,e,e,1)};var Hb="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_x,_y,_z,_s,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE,sv,sr".split(",");n=Hc.prototype;
n.Ua=function(a){this.Ic++;var b={};b.g=this.k.uid;b.g0=Mb(this.k,"sections");b.g1=Mb(this.k,"authors");b.g2=Mb(this.k,"zone");b.g3=Mb(this.k,"sponsorName");b.g4=Mb(this.k,"type");!this.k.noCookies&&this.q.isSupported()?b.n=this.Tb:b.nc=1;b.c=Math.round((u()-this.Fa)/600)/100;b.E=this.ma.ua;b.EE=this.Ja.ua;var c=fc(this);this.bb=Math.max(this.bb,c);b.x=c;b.m=this.bb;b.y=ib("Height");b.o=ib("Width");b.w=hb();b.b=this.eb>0?this.eb:"";if(this.yc)b.f=this.yc;b[""]=Nb(this.k);b.t=this.Ca;b.V=92;b.tz=(new Date).getTimezoneOffset();
b.sn=this.Ic;b.sv=this.de;b.sr=this.ce;c=this.ma.Pa;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.hb;b.d=encodeURIComponent(this.ja);b.j=Math.round((this.Qa+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.Fa;b.eD=B.Ya("mousedown",d);b.eM=B.Ya("mousemove",d);b.eK=B.Ya("keydown",d);b.eR=B.Ya("resize",d);b.eS=B.Ya("scroll",d);B.ae();B.$c()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=$b(this);if(this.cc){this.cc=j;if(c)this.Oa=Ic(this);
b.i=hc(this);d=this.k.hudTrackable;d!==e&&(b.L=d?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.Oa){if(b.v=encodeURIComponent(this.Oa.path),b.K=Jc(this.Oa),this.Oa.Ub>1)b.l1=this.Oa.Ub}else b.v=ac(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=ac(this);c=cb(b.v);J().v=c;c=cb(b.r);J().r=c;b.A=this.Fb?this.Fb:"";b._c=Eb("utm_campaign",this.k.campaignTag);b._m=Eb("utm_medium",this.k.mediumTag);b._x=Eb("utm_source",this.k.sourceTag);b._y=Eb("utm_content",this.k.contentTag);
b._z=Eb("utm_term",this.k.termTag);this.k.idSync?(c=[],ha(new ga,this.k.idSync,c),c=encodeURIComponent(c.join(""))):c="";b._s=c;b.z=ic(this);b.C=this.k.mobileApp?1:"";b.KK=a?Jc(a):"";b.l=Qb(this.q)?1:"";this.ma.Pa=0;this.fb(Ma()+"//"+this.k.pingServer+"/ping?"+Gb(b))};
n.ud=function(a){var b=this.k,c=b.playerdomain||this.ja;if(va(a.origin)===va(c))if(c=a.data,Ia(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Lc(a));else if(c=="cbdata?"){var c="&u="+I("u"),d="&t="+I("t"),f="&v="+I("v"),h="&r="+I("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+hc(this)+"&referrer="+ac(this)+"&internal="+($b(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ja)+
c+d+f+h+"&utoken="+this.hb;a.source.postMessage(b,"*")}};n.Lc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.Qa=0};function Kc(a){a=a.replace(/-{2,}/g,"-");a=Ib(a);a.pathname=Tb(a.pathname);return a}n.Fd=function(a){Lc(this,a,"c")};n.Gd=function(a){Lc(this,a,"r")};
function Lc(a,b,c){if(a.ec&&u()-a.Fa>=a.qb)a.terminate();else{var d=b.href||"",d=Kc(d);if(d.protocol.indexOf("http")===0){var f=d.hostname!==q.location.hostname,d=Jb(d),h=jb(b,function(a){return a.id}),o=uc(b,h),r="";a.k.moduleAttribute&&(r=(r=fb(b,a.k.moduleAttribute))?r.getAttribute(a.k.moduleAttribute):"",r=r.replace(/::/g,"-").substr(0,40));h?(o&&(o="/"+o),o="*[@id='"+h.id+"']"+o,h=uc(b)):h=o;o=qa(o);h=qa(h);b=kc(b);c={left:b.x,top:b.y,path:a.k.path,href:d,pc:o,Eb:h,oc:"",gc:c,Ub:0,od:a.k.domain,
Sb:r};a.Ua(c);f||a.q.update("_chartbeat5",Mc(c),60,j,e,3,function(a){a=a.split(",");return a[2]+","+a[3]})}}}function Jc(a){return[a.left,a.top,a.pc,encodeURIComponent(a.oc),a.gc,encodeURIComponent(a.href),a.Eb,a.Sb].join("::")}function Mc(a){var b=encodeURIComponent(a.oc),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.pc,b,a.gc,a.Eb,encodeURIComponent(a.od),a.Sb].join(",")}
function Ic(a){var b=a.q.F("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,d,f=i,h,o=Kc(q.location.href),r=Jb(o);t(c,function(a,b){var c=a.split(","),o=Fa(r,decodeURIComponent(c[3]));if(o===0)return d=c,f=b,j;else if(o===i)return g;if(h===e||o<h)h=o,d=c,f=b});if(f===i)return i;c.splice(f,1);a.q.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),href:decodeURIComponent(d[3]),pc:d[4]||
"",oc:"",Eb:d.length>7?d[7]:"",gc:d.length>6?d[6]:"c",Ub:b,Sb:d[9]?d[9]:""}}n.terminate=function(){ob(A,this.ad);ob(A,this.bd);Hc.la.terminate.call(this)};var M="ct",O="s1";function P(a){this.a=a;this.D=this.G=j;this.B=u();this.ha()}n=P.prototype;n.ha=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.on("play",v(this.fa,this));this.a.on("dispose",v(this.Id,this));this.a.ready(v(this.ka,this))};n.ka=function(){this.G=g};n.fa=function(){this.D=g};n.Id=function(){var a=q._cbv;a&&a.push&&a.push(["removePlayer",this.a])};n.O=function(){return this.G&&this.M()!==""};
n.Lb=function(){var a;this.a.cb_configs&&this.a.cb_configs.domain?a=this.a.cb_configs.domain:!a&&q._sf_async_config&&q._sf_async_config.domain&&(a=q._sf_async_config.domain);return a};n.Mb=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&q._sf_async_config&&q._sf_async_config.uid&&(a=q._sf_async_config.uid);return a};n.M=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("name")?a.name:this.a.el().getAttribute("title"))||""};
n.N=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("id")?a.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};n.U=function(){return M};n.P=m("");n.ca=function(){var a=this.a.duration();return y(a)};n.J=function(){return!this.D?O:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};n.X=function(){var a=this.a.currentTime();return y(a)};n.T=m(-1);
n.ba=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("thumbnail")?a.thumbnail:this.a.poster())||""};n.Z=k();n.S=k();n.da=function(){return Wa(this.B)};n.$=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.sections&&(a=q._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};
n.Q=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.authors&&(a=q._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};n.aa=m("BCN");P.prototype.getStrategyName=P.prototype.aa;P.prototype.isReady=P.prototype.O;P.prototype.getHost=P.prototype.Lb;P.prototype.getUid=P.prototype.Mb;P.prototype.getTitle=P.prototype.M;P.prototype.getVideoPath=P.prototype.N;
P.prototype.getContentType=P.prototype.U;P.prototype.getAdPosition=P.prototype.P;P.prototype.getTotalDuration=P.prototype.ca;P.prototype.getState=P.prototype.J;P.prototype.getCurrentPlayTime=P.prototype.X;P.prototype.getBitrate=P.prototype.T;P.prototype.getThumbnailPath=P.prototype.ba;P.prototype.getPlayerType=P.prototype.Z;P.prototype.getAutoplayType=P.prototype.S;P.prototype.getViewStartTime=P.prototype.da;P.prototype.getSections=P.prototype.$;P.prototype.getAuthors=P.prototype.Q;
P.verify=function(a){return a.controlBar!==e};function Q(a){this.Va=this.ja=e;this.G=j;this.Kc=this.sc=-1;this.va=i;this.a=a;this.D=j;this.Zb=g;this.B=u();this.$b="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var d=a[c];if((d.indexOf("chartbeat")>=0||d.indexOf("localhost")>=0)&&d.indexOf(".js")>=0){this.$b=d;break}}if(this.$b){a=Db(this.$b);if(this.ja=a.domain)this.ja=this.ja.replace(/^video@/,"");this.Va=a.uid}a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);
b.getReady()?this.Hc():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,s(this.Hc,this))}n=Q.prototype;
n.Hc=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.sc=Math.round(a)});b.getCurrentVideo(function(a){c.va=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,s(this.Qd,this));b.addEventListener(a.STOP,s(this.Sd,this));b.addEventListener(a.COMPLETE,s(this.Hd,this));b.addEventListener(a.BEGIN,s(this.fa,this));this.G=g};n.Qd=function(a){this.Kc=a.position;this.za=this.Zb=j};n.Sd=function(){this.Zb=g};
n.Hd=function(){this.za=g};n.fa=function(){this.za=j;if(!this.D)this.D=g};n.O=l("G");n.M=function(){var a="";this.va&&(a=this.va.displayName);return a};n.N=function(){var a="";this.va&&(a="video@"+this.ja+"/"+this.va.id);return a};n.U=function(){return M};n.P=m("");n.ca=l("sc");n.J=function(){return!this.D?O:this.za?"s4":this.Zb?"s3":"s2"};n.X=function(){return y(this.Kc)};n.T=m(-1);n.ba=function(){var a="";this.va&&(a=this.va.thumbnailURL);return a};n.Z=k();
n.da=function(){return isNaN(this.B)?0:Pa(this.B)};n.Q=k();n.$=function(){var a;this.va&&(a=this.va.tags);return a};n.S=m("unkn");n.aa=m("BC");n.Lb=l("ja");n.Mb=l("Va");Q.prototype.isReady=Q.prototype.O;Q.prototype.getTitle=Q.prototype.M;Q.prototype.getVideoPath=Q.prototype.N;Q.prototype.getContentType=Q.prototype.U;Q.prototype.getAdPosition=Q.prototype.P;Q.prototype.getTotalDuration=Q.prototype.ca;Q.prototype.getState=Q.prototype.J;Q.prototype.getCurrentPlayTime=Q.prototype.X;
Q.prototype.getBitrate=Q.prototype.T;Q.prototype.getThumbnailPath=Q.prototype.ba;Q.prototype.getPlayerType=Q.prototype.Z;Q.prototype.getViewStartTime=Q.prototype.da;Q.prototype.getAuthors=Q.prototype.Q;Q.prototype.getSections=Q.prototype.$;Q.prototype.getAutoplayType=Q.prototype.S;Q.verify=function(a){return a===window.brightcove};Q.prototype.getStrategyName=Q.prototype.aa;Q.prototype.getHost=Q.prototype.Lb;Q.prototype.getUid=Q.prototype.Mb;function S(){this.a=window.flowplayer();this.D=this.G=j;this.B=u();this.ya=this.Ba=e;this.zb=this.gb="";this.Rb=e;this.ha()}var Nc=/url\(['"]?([^'"\)]*)['"]?\)/;n=S.prototype;
n.wc=function(){if(this.a.conf&&(this.zb=this.a.conf.title?this.a.conf.title:"",this.gb=this.a.conf.poster?this.a.conf.poster:"",this.zb&&this.gb))return g;var a=this.N(),b=eb("name","param"),c=e;t(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===e&&(b=eb("src","video"),t(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=fb(c,"data-swf");if(b===j)return j;var d=b.style.background;if(d){if(d=
d.match(Nc))this.gb=d[1]}else this.gb=b.attributes.poster&&b.attributes.poster.value;this.zb=b.title;if(this.Rb!==e)clearInterval(this.Rb),this.G=g;return g};n.ha=function(){this.a.se?this.ka():this.a.bind("ready",s(this.ka,this));this.a.bind("resume",s(this.fa,this));this.a.re&&this.fa()};n.ka=function(){this.wc()===j?this.Rb=setInterval(s(this.wc,this),1E3):this.G=g};n.fa=function(){if(!this.D)this.D=g};n.O=l("G");n.M=l("zb");n.N=function(){return this.a.video.url||this.a.video.src};n.U=function(){return M};
n.P=m("");n.ca=function(){return this.a.video.duration&&this.a.video.duration*1E3};n.J=function(){return!this.D?O:this.a.pe?"s4":this.a.paused?"s3":"s2"};n.X=function(){return y(this.a.video.time)};n.T=m(-1);n.ba=l("gb");n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:Pa(this.B)};n.$=l("Ba");n.Q=l("ya");n.aa=m("FP");S.prototype.getStrategyName=S.prototype.aa;S.prototype.isReady=S.prototype.O;S.prototype.getTitle=S.prototype.M;S.prototype.getVideoPath=S.prototype.N;
S.prototype.getContentType=S.prototype.U;S.prototype.getAdPosition=S.prototype.P;S.prototype.getTotalDuration=S.prototype.ca;S.prototype.getState=S.prototype.J;S.prototype.getCurrentPlayTime=S.prototype.X;S.prototype.getBitrate=S.prototype.T;S.prototype.getThumbnailPath=S.prototype.ba;S.prototype.getPlayerType=S.prototype.Z;S.prototype.getAutoplayType=S.prototype.S;S.prototype.getViewStartTime=S.prototype.da;S.prototype.getSections=S.prototype.$;S.prototype.getAuthors=S.prototype.Q;S.verify=function(){return!!window.flowplayer};function T(a){this.a=a;this.Cb=this.D=this.G=j;this.B=u();this.ya=this.Ba=e;this.ha()}n=T.prototype;n.ha=function(){this.a.readyState>0&&this.ka();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.addEventListener("canplay",v(this.ka,this));var a=v(this.fa,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",v(this.Yd,this))};n.ka=function(){this.G=g};n.fa=function(){this.D=g;this.Cb=j};
n.Yd=function(){this.Cb=g};n.O=l("G");n.M=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};n.N=function(){return this.a.currentSrc||""};n.U=function(){return M};n.P=m("");n.ca=function(){return y(this.a.duration)};n.J=function(){return!this.D?O:this.a.ended||this.Cb&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.Cb?"s3":"s2"};n.X=function(){return y(this.a.currentTime)};n.T=m(-1);n.ba=function(){return this.a.poster||""};n.Z=k();
n.S=function(){return this.a.autoplay?"auto":"man"};n.da=function(){return Wa(this.B)};n.$=l("Ba");n.Q=l("ya");n.aa=m("H5");T.prototype.getStrategyName=T.prototype.aa;T.prototype.isReady=T.prototype.O;T.prototype.getTitle=T.prototype.M;T.prototype.getVideoPath=T.prototype.N;T.prototype.getContentType=T.prototype.U;T.prototype.getAdPosition=T.prototype.P;T.prototype.getTotalDuration=T.prototype.ca;T.prototype.getState=T.prototype.J;T.prototype.getCurrentPlayTime=T.prototype.X;
T.prototype.getBitrate=T.prototype.T;T.prototype.getThumbnailPath=T.prototype.ba;T.prototype.getPlayerType=T.prototype.Z;T.prototype.getAutoplayType=T.prototype.S;T.prototype.getViewStartTime=T.prototype.da;T.prototype.getSections=T.prototype.$;T.prototype.getAuthors=T.prototype.Q;T.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==i;return b&&!a};function U(a){this.a=a;this.D=this.za=this.G=j;this.B=u();this.ab=j;this.ha()}n=U.prototype;n.ha=function(){function a(a,f){f=s(f,c);if(aa(b.on)=="function")b.on(a,f);else{var h="on"+a.substr(0,1).toUpperCase()+a.substr(1);if(aa(b[h])=="function")b[h](f)}}var b=this.a,c=this;a("ready",this.ka);a("time",this.Ud);a("complete",this.Vd);a("adStarted",this.Sa);a("adPlay",this.Sa);a("adImpression",this.Sa);a("adTime",this.Sa);a("adComplete",this.Vb);a("adSkipped",this.Vb);a("adError",this.Vb)};
n.ka=function(){this.G=g};n.Ud=function(){this.za=j;this.D=g;this.ab=j};n.Vd=function(){this.za=g};n.Sa=function(){this.ab=this.D=g};n.Vb=function(){this.ab=j};n.O=function(){this.a.getState();return this.G||this.a.getState()!==e};n.M=function(){var a=Oc(this);return!a?"":a.title};function Oc(a){if(a.a.getPlaylistIndex===e)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return i;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?i:b[a]}
n.N=function(){var a=Oc(this);return!a?"":a.mediaid||a.file};n.U=function(){return this.ab?"ad":M};n.P=m("");n.ca=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};n.J=function(){if(!this.D)return O;if(this.ab)return"s2";if(this.za)return"s4";var a=this.a.getState();return a&&a.toUpperCase()==="PAUSED"?"s3":"s2"};n.X=function(){var a=this.a.getPosition();return y(a)};n.T=m(-1);n.ba=function(){var a=Oc(this);return!a?"":a.image};n.Z=k();n.da=function(){return isNaN(this.B)?0:Pa(this.B)};
n.Q=k();n.$=k();n.S=m("unkn");n.aa=m("JW");U.prototype.getStrategyName=U.prototype.aa;U.prototype.isReady=U.prototype.O;U.prototype.getTitle=U.prototype.M;U.prototype.getVideoPath=U.prototype.N;U.prototype.getContentType=U.prototype.U;U.prototype.getAdPosition=U.prototype.P;U.prototype.getTotalDuration=U.prototype.ca;U.prototype.getState=U.prototype.J;U.prototype.getCurrentPlayTime=U.prototype.X;U.prototype.getBitrate=U.prototype.T;U.prototype.getThumbnailPath=U.prototype.ba;
U.prototype.getPlayerType=U.prototype.Z;U.prototype.getViewStartTime=U.prototype.da;U.prototype.getAuthors=U.prototype.Q;U.prototype.getSections=U.prototype.$;U.prototype.getAutoplayType=U.prototype.S;U.verify=function(a){return w(a.id)&&w(a.registerPlugin)};function V(a){this.a=a;this.Rc="";this.ia=O;this.Aa=M;this.sa="";this.B=u();this.ha()}n=V.prototype;n.ha=function(){this.a.kBind("playerStateChange.cb",s(this.Xd,this));this.a.kBind("playerUpdatePlayhead.cb",s(this.Pd,this));this.a.kBind("playerPlayEnd.cb",s(this.Wd,this));this.a.kBind("adStart.cb",s(this.Sa,this));this.a.kBind("adEnd.cb",s(this.Cd,this));this.a.kBind("switchingChangeComplete.cb",s(this.Td,this))};
n.Xd=function(a){switch(a){case "playing":this.ia="s2";break;case "buffering":this.ia="s3";break;case "paused":this.ia="s3"}};n.Pd=function(){this.ia="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};n.Wd=function(){this.ia="s4"};n.Sa=function(a){this.Aa="ad";switch(a){case "pre":this.sa="a1";break;case "post":this.sa="a3";break;case "mid":this.sa="a2";break;case "main":this.sa="a5"}};n.Cd=function(){this.Aa=M};n.Td=function(a,b){this.dd=b};
n.O=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=i};n.M=function(){return this.a.evaluate("{mediaProxy.entry.name}")};n.N=function(){if(!this.O())return this.Rc;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.Rc=a)||""};n.U=l("Aa");n.P=l("sa");n.ca=function(){var a=this.a.evaluate("{duration}");return y(a)};n.J=l("ia");n.X=function(){var a=this.a.evaluate("{video.player.currentTime}");return y(a)};n.T=l("dd");
n.ba=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};n.Z=k();n.S=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};n.da=function(){return isNaN(this.B)?0:Wa(this.B)};n.$=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
n.Q=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};n.aa=m("KT");V.prototype.getStrategyName=V.prototype.aa;V.prototype.isReady=V.prototype.O;V.prototype.getTitle=V.prototype.M;V.prototype.getVideoPath=V.prototype.N;V.prototype.getContentType=V.prototype.U;V.prototype.getAdPosition=V.prototype.P;V.prototype.getTotalDuration=V.prototype.ca;V.prototype.getState=V.prototype.J;V.prototype.getCurrentPlayTime=V.prototype.X;V.prototype.getBitrate=V.prototype.T;
V.prototype.getThumbnailPath=V.prototype.ba;V.prototype.getPlayerType=V.prototype.Z;V.prototype.getAutoplayType=V.prototype.S;V.prototype.getViewStartTime=V.prototype.da;V.prototype.getSections=V.prototype.$;V.prototype.getAuthors=V.prototype.Q;V.verify=function(a){return typeof a.kBind=="function"};function W(a){this.rc=e;this.a=a;this.Bc=e;this.G=j;this.Ka=e;this.D=j;this.ya=this.Ba=this.B=e;this.rc=q.OO;this.Bc=this.a.mb;this.B=u();this.ha()}n=W.prototype;
n.ha=function(){var a=this.Bc,b=this.rc.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",s(this.ka,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",s(this.Ed,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",s(this.fa,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",s(this.Dd,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",s(this.Od,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",s(this.Jd,this))};n.ka=function(){this.G=g};
n.Ed=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.Ka=a===0?"a1":Pc(a,b)?"a3":"a2"};n.fa=function(){this.D=g};n.Dd=function(){this.Ka=e};n.Od=k();n.O=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.G=g;return this.G};n.M=function(){var a=this.a.getItem();return a?a.title:""};n.N=function(){return(this.a.getItem()||{}).embedCode||this.a.embedCode||""};n.U=function(){return this.Ka===e?M:"ad"};
n.P=function(){return this.Ka?this.Ka:""};n.ca=function(){var a=this.a.getDuration();return a===-1||isNaN(a)?-1:a*1E3};n.J=function(){if(!this.D)return O;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return Pc(a,b)?"s4":"s2"};function Pc(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}n.Jd=function(){this.Ka=e};
n.X=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};n.T=function(){return this.a.getTargetBitrate()};n.ba=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:Wa(this.B||0)};n.$=l("Ba");n.Q=l("ya");n.aa=m("OO");W.prototype.getStrategyName=W.prototype.aa;W.prototype.isReady=W.prototype.O;W.prototype.getTitle=W.prototype.M;W.prototype.getVideoPath=W.prototype.N;
W.prototype.getContentType=W.prototype.U;W.prototype.getAdPosition=W.prototype.P;W.prototype.getTotalDuration=W.prototype.ca;W.prototype.getState=W.prototype.J;W.prototype.getCurrentPlayTime=W.prototype.X;W.prototype.getBitrate=W.prototype.T;W.prototype.getThumbnailPath=W.prototype.ba;W.prototype.getPlayerType=W.prototype.Z;W.prototype.getAutoplayType=W.prototype.S;W.prototype.getViewStartTime=W.prototype.da;W.prototype.getSections=W.prototype.$;W.prototype.getAuthors=W.prototype.Q;
W.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("adPlaying")};function Y(a){this.a=a;this.ga=i;this.Za="";this.ia=O;this.Aa=M;this.sa="";this.B=u();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}n=Y.prototype;n.zd=function(a){this.ha(a.controller)};
n.ha=function(a){a.addEventListener("OnLoadRelease",v(this.Fc,this));a.addEventListener("OnLoadReleaseUrl",v(this.Fc,this));a.addEventListener("OnReleaseStart",v(this.Rd,this));a.addEventListener("OnMediaPlay",v(this.Ld,this));a.addEventListener("OnMediaStart",v(this.Nd,this));a.addEventListener("OnMediaPause",v(this.Xb,this));a.addEventListener("OnMediaComplete",v(this.Kd,this));a.addEventListener("OnMediaError",v(this.Xb,this));a.addEventListener("OnMediaBuffer",v(this.Xb,this));a.addEventListener("OnMediaPlaying",
v(this.Md,this))};n.Fc=function(a){if(a.data&&a.data.title)this.ga=a.data;if(a.data&&a.data.guid)this.Za=a.data.guid};n.Rd=function(a){t(a.data.clips,v(function(a){if(a=a.baseClip.guid)return this.Za=a,j},this));if(this.Za&&a.data.release&&a.data.release.title)this.ga=a.data.release};n.Ld=function(){this.ia="s2"};n.Nd=function(a){this.ia="s2";a=a.data.baseClip;a.isAd?(this.Aa="ad",this.sa=a.isMid?"a2":"a1"):(this.Aa=M,this.sa="")};n.Xb=function(){if(this.ia!=O)this.ia="s3"};
n.Kd=function(){this.ia="s4"};n.Md=function(a){this.hd=a.currentTime};n.O=function(){return this.ga!=i};n.M=function(){return this.ga.title};n.N=function(){return!this.Za?"":this.Za};n.U=l("Aa");n.P=l("sa");n.ca=function(){return this.ga.duration};n.J=l("ia");n.X=l("hd");n.T=function(){return this.ga.bitrate};n.ba=function(){return this.ga&&this.ga.defaultThumbnailUrl?this.ga.defaultThumbnailUrl:this.ga.pid?"http://link.theplatform.com/s/ngc/"+this.ga.pid+"?format=poster&height=70&width=95":""};
n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:this.B===e?0:u()-this.B};n.$=function(){var a=this.ga.keywords?this.ga.keywords.split(","):[],b=[];t(this.ga.categories?this.ga.categories:[],function(a){b.push(encodeURIComponent(a.name))});t(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};n.Q=k();n.aa=m("TP");Y.prototype.initialize=Y.prototype.zd;Y.prototype.getStrategyName=Y.prototype.aa;Y.prototype.isReady=Y.prototype.O;Y.prototype.getTitle=Y.prototype.M;
Y.prototype.getVideoPath=Y.prototype.N;Y.prototype.getContentType=Y.prototype.U;Y.prototype.getAdPosition=Y.prototype.P;Y.prototype.getTotalDuration=Y.prototype.ca;Y.prototype.getState=Y.prototype.J;Y.prototype.getCurrentPlayTime=Y.prototype.X;Y.prototype.getBitrate=Y.prototype.T;Y.prototype.getThumbnailPath=Y.prototype.ba;Y.prototype.getPlayerType=Y.prototype.Z;Y.prototype.getAutoplayType=Y.prototype.S;Y.prototype.getViewStartTime=Y.prototype.da;Y.prototype.getSections=Y.prototype.$;
Y.prototype.getAuthors=Y.prototype.Q;Y.verify=function(a){return typeof a.controller!=="undefined"};function Qc(a,b){this.a=a;this.Qc=b;this.Na=window.location!=window.parent.location;this.Jc=j;this.fe=u();this.Pc="_v_";this.ta={};L.call(this)}ea(Qc,L);var Rc=q.QUICK_TEST?1E4:6E4,Sc="autoDetect",Tc={le:"title",me:"videopath",ke:"thumbnailpath"},Uc={};n=Qc.prototype;
n.H=function(){this.Tb=(this.Ta=this.q.F("_chartbeat3"))?0:1;this.mc=this.dc=g;this.Jb=j;this.vb=this.ac=this.tc=this.Ga=e;this.La=15E3;this.ib=e;this.jb=this.kb=0;this.Kb=j;this.Zd=this.jc=this.Ab=0;var a=q.location;this.bc=j;if(!this.Ta||this.Ta.length===0)this.Ta=qa(Zb(this),3);this.q.create("_chartbeat3",this.Ta,34128E3);var b;(b=this.Qc)&&Ja(b)?(this.ea=new b(this.a),b=g):b=j;if(b){C(this.k,"pingServer","ping.chartbeat.net");C(this.k,"title",document.title);C(this.k,"domain",a.hostname);C(this.k,
"path",Rb(!!this.k.useCanonical));this.ea.getPlayerType&&C(this.k,"video_type",this.ea.getPlayerType());this.tc=setInterval(v(this.ed,this),1E3);if(this.Na===g)this.rb=v(this.vd,this),x(window,"message",this.rb),this.ib=setInterval(this.$d,1E3);Qc.la.H.call(this)}};n.Gb=k();
n.oa=function(){if(this.ea){if(!Vc(this))this.mc=g;if(!this.mc)return u()-this.Fa>=this.qb&&clearInterval(this.Ga),Qc.la.oa.call(this);if(this.ea.isReady())this.Jb=this.mc=j,this.ac=Wc(this),Xc(this),this.Ga=setInterval(v(this.Ib,this),100),Qc.la.oa.call(this);else if(!this.Jb){this.Jb=g;if(this.Zd++>150)throw"Error: Video strategy never reported its ready state";Yc(this,100)}}};
n.Ua=function(){if(this.ea){var a=this.k,b=this.ea,c=b.getState(),d=Vc(this),f=this.Na?[]:q._cbq||(q._cbq=[]),h=b.getViewStartTime(),o=Zc(this),r=b.getAutoplayType?b.getAutoplayType():e,h=h===-1?-1:h/1E3,o=o?encodeURIComponent(o):e;if(!Uc.path||Uc.path===d||c==="s2"&&Uc.state!=="s2")switch(Uc={path:d,state:c},f.push(["_vi",La($c(this))]),f.push(["_vp",d]),f.push(["_vdd",La(ad(this))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),b.getAdPosition&&f.push(["_vap",
b.getAdPosition()]),f.push(["_vtn",La(Zc(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case O:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=bd(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vcs",this.Kb?"1":"0")+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",h)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",o)+Z("_vaup",r||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.jc)+Z("c",Math.round(Pa(this.fe)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.Ab+"&j="+(this.La/1E3+15)+cd(this)+"&tz="+(new Date).getTimezoneOffset()+(Qb(this.q)?"&l=1":"")+"&_";this.Na===g&&t(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.fb(a)}};function Z(a,b){return b!==e&&b!==""?"&"+a+"="+b:""}n.cb=function(){this.q.update("_cb_cp",this.Ca,60,j,",")};function cd(a){var b=a.q.F("_cb_cp");a.q.remove("_cb_cp");return b?"&D="+b:""}
function dd(a){return a.k.subdomain?a.k.subdomain:ta(q.location.hostname)}function ad(a){var b=a.k,a=a.ea,b=b.videodomain||a.getHost&&a.getHost()||b.domain;return"video@"+(b&&b.replace(/^video@/,""))}function Vc(a){var b=a.ta.videopath;if(b)return b;if(a.k.videoPathHash){if(a=$c(a))return qa(a)}else return a.ea.getVideoPath();return""}function $c(a){return a.ta.title||a.ea.getTitle()}function Zc(a){return a.ta.thumbnailpath||a.ea.getThumbnailPath()}
function bd(a){var b=a.k,c=a.ea,d=c.getUid&&c.getUid()||b.uid,f=La(ad(a)),h="",o=a.eb?"&b="+a.eb:"",r,p=a.k.path;r=a.k.useSubDomains!==j&&p&&p.substr(0,1)==="/"?dd(a)+p:p;var p=c.getSections&&c.getSections(),E=c.getAuthors&&c.getAuthors(),H=b.sections?"&g0="+encodeURIComponent(b.sections):"",R=b.authors?"&g1="+encodeURIComponent(b.authors):"",p=p===e||b.videoPageGroups?H:"&g0="+encodeURIComponent(p.join(",")),E=E===e||b.videoPageGroups?R:"&g1="+encodeURIComponent(E.join(",")),R="",H=Vc(a);if(a.vb===
e)a.vb=H;else if(H!=a.vb)R=Z("D",a.Ca),a.Ca=qa(Zb(a)),a.vb=H,a.kb=0,a.jb=0,a.Ab=0,a.jc=0,a.Kb=ed(a)&&!fd(a),a.dc=g;if(a.dc||R){if(a.Na===j||a.Na===g&&a.Jc===g)a.dc=j;h=($b(a)?"&v=":"&r=")+ac(a)}a.Ab+=a.kb;a.kb=0;a.jc+=a.jb;a.jb=0;Xc(a);var X=H="",fa="",ca="",N="",D="",ka="",la="";if(!a.Na===g||a.bc===g)H="&_vi="+hc(a),X="&_vp="+encodeURIComponent(r),fa="&_vh="+La(dd(a)),ca="&_vdd="+encodeURIComponent(b.domain),a.bc===g?(N=b.u,D=b.t,ka=db(b.v),la=db(b.r)):(N=I("u"),D=I("t"),ka=db(I("v")),la=db(I("r")));
r="";r=Ia(ka)?"&_pv="+ka:Ia(la)?"&_pr="+la:"&_pr=NA";ka="&_pu=";la="&_pt=";ka+=N?N:"NA";la+=D?D:"NA";N=!b.noCookies&&a.q.isSupported();D=c.getStrategyName?c.getStrategyName():"";return Ma()+"//"+b.pingServer+"/ping?h="+f+"&g="+d+"&p="+La(Vc(a))+"&i="+La($c(a))+p+E+"&u="+a.Ta+"&t="+a.Ca+"&x=0&y=0&V=92"+Z("VS",D)+(N?"&n="+a.Tb:"&nc=1")+o+h+R+Z("_vd",c.getTotalDuration())+H+X+fa+ka+la+r+ca}n.Ib=function(){if(ed(this)&&!fd(this))this.Kb=g;var a=Wc(this);if(this.ac!=a)this.ac=a,Xc(this),this.oa()};
function Xc(a){var b=a.La;a.La=ed(a)?a.Ab<60?5E3:15E3:Rc;b!=a.La&&Yc(a,a.La)}function Yc(a,b){clearInterval(a.nb);a.La=b;a.nb=setInterval(v(a.oa,a),b)}function Wc(a){return a.ea.getState()+a.ea.getContentType()}function ed(a){return a.ea.getState()==="s2"||fd(a)}function fd(a){return a.ea.getContentType()==="ad"}n.ed=function(){ed(this)===g&&(this.kb+=1,this.ea.getContentType()===M&&(this.jb+=1))};n.$d=function(){window.parent.postMessage("cbdata?","*")};
n.vd=function(a){if(a.source===window.parent&&(a=a.data,Ia(a)&&a.indexOf("domain=")===0)){this.bc=g;var b={domain:g,uid:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g,u:g,t:g,v:g,r:g},c=this;t(a.split("&"),function(a){var a=a.split("="),f=a[0],a=a[1];b[f]&&(c.k[f]=decodeURIComponent(a))});Ga(window,"message",this.rb);clearInterval(this.ib);this.ib=e;this.Jc=g;this.oa()}};n.setProperty=function(a,b){var c=j,d=this;t(Tc,function(f){if(a.toLowerCase()==f)return d.ta[f]=b,c=g,j});return c};
n.terminate=function(){clearInterval(this.tc);clearInterval(this.ib);clearInterval(this.Ga);Ga(window,"message",this.rb);Qc.la.terminate.call(this)};n.wa=function(){Qc.la.wa.call(this);this.Qc=this.a=this.rb=i};function $(a){this.a=a;this.G=g;this.D=j;this.B=u();this.Ga=this.ya=this.Ba=e;this.Sc=q._sf_async_config.ytApikey;this.Wa=e;gd(this,hd(this));this.ha()}n=$.prototype;n.ha=function(){this.Ga=setInterval(s(this.Ib,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.fa()};n.Ib=function(){if(this.a.getPlayerState()===1)clearInterval(this.Ga),this.Ga=e,this.fa()};n.ka=function(){this.G=g};n.fa=function(){if(!this.D)this.D=g};
function hd(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}function gd(a,b){var c="https://www.googleapis.com/youtube/v3/videos?part=snippet&id="+b+"&key="+a.Sc,d=v(function(){this.Wa={id:b,title:""}},a);if(a.Sc){var f=v(function(a){if(b==hd(this))a?a.error?d():this.Wa={id:b,title:a&&a.items&&a.items[0]&&a.items[0].snippet&&a.items[0].snippet.title||""}:d()},a);Qa(c,f)}else d()}n.O=function(){return this.G&&!!this.Wa};
n.M=function(){return this.Wa&&this.Wa.id===hd(this)?this.Wa.title:""};n.N=function(){return hd(this)||this.a.getVideoUrl()};n.U=function(){return M};n.P=m("");n.ca=function(){var a=this.a.getDuration();return Ha(a)?a*1E3:a};n.J=function(){if(!this.D)return O;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};n.X=function(){var a=this.a.getCurrentTime();return y(a)};n.T=m(-1);n.ba=function(){return"http://img.youtube.com/vi/"+hd(this)+"/default.jpg"};n.Z=k();n.S=k();
n.da=function(){return isNaN(this.B)?0:Pa(this.B)};n.$=l("Ba");n.Q=l("ya");n.aa=m("YT");$.prototype.getStrategyName=$.prototype.aa;$.prototype.isReady=$.prototype.O;$.prototype.getTitle=$.prototype.M;$.prototype.getVideoPath=$.prototype.N;$.prototype.getContentType=$.prototype.U;$.prototype.getAdPosition=$.prototype.P;$.prototype.getTotalDuration=$.prototype.ca;$.prototype.getState=$.prototype.J;$.prototype.getCurrentPlayTime=$.prototype.X;$.prototype.getBitrate=$.prototype.T;
$.prototype.getThumbnailPath=$.prototype.ba;$.prototype.getPlayerType=$.prototype.Z;$.prototype.getAutoplayType=$.prototype.S;$.prototype.getViewStartTime=$.prototype.da;$.prototype.getSections=$.prototype.$;$.prototype.getAuthors=$.prototype.Q;$.verify=function(a){return Ja(a.getDuration)&&Ja(a.getVideoUrl)&&Ja(a.getVideoEmbedCode)};function id(){q._cbv_strategies||(q._cbv_strategies=[]);q._cbv_strategies.push(W);q._cbv_strategies.push(T);q._cbv_strategies.push(S);q._cbv_strategies.push($);q._cbv_strategies.push(U);q._cbv_strategies.push(Q);q._cbv_strategies.push(P);q._cbv_strategies.push(V);q._cbv_strategies.push(Y);this.kc=[];this.ta=[];this.k=q._sf_async_config||{};Kb("_cbv",v(this.wd,this));if(this.k[Sc]!==j)this.md=bb(v(this.xc,this),5E3),this.xc(),setTimeout(v(this.Ha,this),3E4)}
id.prototype.wd=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){jd();return}else if(b==="removePlayer"){kd(this,a[1]);return}else if(b==="setProps"){ld(a[1])||this.ta.push(a[1]);return}}md(this,a)};function md(a,b){var c=j,d=q._cbv_strategies;w(window.jwplayer)&&(b=Ja(b)?b():b);t(d,function(a){if(a.verify(b)===g)return c=a,j});c===j||nd(a,b,c)}
function kd(a,b){var c=a.kc,d=q.pSUPERFLY_video,f=Na(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=Na(d,function(a){return a.a===b});f!==-1&&d.splice(f,1)[0].wa()}function ld(a){if(!w(a))return j;var b=a.player,c=Oa(function(a){return a.a===b});return!w(c)?j:od(c,a)}function od(a,b){var c=j;t(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}
function nd(a,b,c){var d=j;t(a.kc,function(a){if(b===a)return d=g,j});if(!d){c=new Qc(b,c);q.pSUPERFLY_video.push(c);for(var f=a.ta.length-1;f>-1;f--)od(c,a.ta[f])&&a.ta.splice(f,1);dc(c);a.kc.push(b)}}
id.prototype.xc=function(){if(Ja(window.jwplayer)&&w(window.jwplayer())){this.Ha();for(var a=0,b=window.jwplayer(a);w(b.id);)window._cbv.push(b),b=window.jwplayer(++a)}else window.flowplayer?(this.Ha(),window._cbv.push(window.flowplayer)):window.brightcove&&window.experienceJSON?(this.Ha(),window._cbv.push(window.brightcove)):window.videojs?(this.Ha(),a=window.videojs.plugin,Ja(a)&&a("chartbeat",function(a){this.cb_configs=a;window._cbv.push(this)})):window.kWidget?(this.Ha(),window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))})):
window.$pdk?(this.Ha(),window._cbv.push(window.$pdk)):t(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})};id.prototype.Ha=function(){Za(this.md)};
function jd(){function a(){function a(b){q._cbv.push(b.target)}var b=q.YT.Player;t(document.getElementsByTagName("iframe"),function(f){var h=f.src,o=h&&h.indexOf("www.youtube.com/embed/");h&&o>=0&&o<9&&new b(f,{events:{onReady:a}})})}if(q.YT&&q.YT.Player)a();else{var b=q.onYouTubeIframeAPIReady;q.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(q,arguments)}catch(c){}a()}}}};if(window.location==window.parent.location&&!q.pSUPERFLY){var pd=new Hc,qd={};q.pSUPERFLY=qd;var rd=!!zc;qd.virtualPage=function(a,b){if(!ub){var c=q._sf_async_config;c.virtualReferrer=Ma()+"//"+c.domain+c.path;c.path=Tb(a);b&&(c.title=b);pd.lb();rd&&zc.evps();pd.Oc();rd&&zc.svps()}};qd.activity=v(pd.Yc,pd);dc(pd);var sd=G.Y(g);if(sd)if(sd.getItem("_cb_ip")){var td=q.location;(!/^(.+[.])?chartbeat\.com$/.test(td.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(td.pathname))||Fc()}else x(q,"message",
Gc)}q.pSUPERFLY_video||(q.pSUPERFLY_video=[]);new id;})();
