(function(g){var window=this;var Bya=function(a,b){var c=[];g.Nl(b,function(a){try{var b=g.GD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.FD(b)&&c.push(a):c.push(a)},a);
return c},Cya=function(a,b){var c=Bya(a,b);
(0,g.H)(c,function(a){g.GD.prototype.remove.call(this,a)},a)},Q7=function(a,b){g.J0.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.T=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},Dya=function(){var a=g.nH;
Cya(a,a.g.ae(!0))},R7=function(a){g.QH.call(this,"ScreenServiceProxy");
this.ed=a;this.o=[];this.o.push(this.ed.$_s("screenChange",(0,g.A)(this.xU,this)));this.o.push(this.ed.$_s("onlineScreenChange",(0,g.A)(this.MQ,this)))},S7=function(a){g.DH("cloudview",a)},Eya=function(a){S7("setApiReady_ "+a);
g.sa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},T7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Fya=function(a){g.GG[a]&&(a=g.GG[a],(0,g.H)(a,function(a){g.EG[a]&&delete g.EG[a]}),a.length=0)},Gya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},U7=function(){return g.x("yt.mdx.remote.connection_")},V7=function(a){g.sa("yt.mdx.remote.connectData_",a,void 0)},Hya=function(a){g.sa("yt.mdx.remote.currentScreenId_",a,void 0)},W7=function(){return g.x("yt.mdx.remote.currentScreenId_")},
Y7=function(){if(!X7){var a=g.x("yt.mdx.remote.screenService_");
X7=a?new R7(a):null}return X7},Z7=function(a){g.sa("yt.mdx.remote.cloudview.initializing_",a,void 0)},$7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},a8=function(a){S7("setCastInstalled_ "+a);
g.pH("yt-remote-cast-installed",a)},b8=function(a){g.DH("cloudview",a)},Iya=function(a,b){T7().init(a,b)},c8=function(){return!!g.qH("yt-remote-cast-installed")},Jya=function(){S7("dispose");
var a=T7();a&&a.dispose();g.sa("yt.mdx.remote.cloudview.instance_",null,void 0);Eya(!1);g.IG(d8);d8.length=0},Kya=function(){var a=window.document.createElement("a");
g.Uc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Wa(a)},Lya=function(a,b){var c=g.zd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Vc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Mya=function(a){var b=g.DG();
if(b)if(b.clear(a),a)Fya(a);else for(var c in g.GG)Fya(c)},e8=function(){var a=Gya();
a&&a(!1,"No cast extension found")},f8=function(a){return 0<=window.navigator.userAgent.indexOf(a)},g8=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},Nya=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},h8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},j8=function(a){var b=U7();
V7(null);a||Hya("");g.sa("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.H)(i8,function(b){b(a)}),i8.length=0);
b&&!a?g.LG("yt-remote-connection-change",!1):!b&&a&&g.LG("yt-remote-connection-change",!0)},Oya=function(){return g.x("yt.mdx.remote.connectData_")},k8=function(){var a=W7();
if(!a)return null;var b=Y7().he();return g.PH(b,a)},Pya=function(a,b){a8(!0);
Z7(!1);Iya(a,function(a){a?(Eya(!0),g.JG("yt-remote-cast2-api-ready")):(b8("Failed to initialize cast API."),a8(!1),g.rH("yt-remote-cast-available"),g.rH("yt-remote-cast-receiver"),Jya());b(a)})},Qya=function(){return c8()?T7()?T7().getCastSession():(b8("getCastSelector: Cast is not initialized."),null):(b8("getCastSelector: Cast API is not installed!"),null)},Rya=function(){var a=Kya(),b=window.document.getElementById(a),c=b&&g.TF(b,"loaded");
c||b&&!c||(b=Lya(a,function(){g.TF(b,"loaded")||(g.UF(b,"loaded","true"),g.JG(a),g.XE(g.Ba(Mya,a),0))}))},Sya=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},Tya=function(){if(g.pra){var a=2,b=Gya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g8("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",e8,c)}},l8=function(a){if(a>=g.rra.length)e8();
else{var b=g.rra[a],c="chrome-extension://"+b+g.ora;0<=g.d2.indexOf(b)?Nya(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,g8(c,e8)):l8(a+1)}):g8(c,function(){l8(a+1)})}},n8=function(a,b){W7();
k8()&&k8();Hya(a.id);var c=new g.VI(m8,a,h8());c.connect(b,Oya());c.subscribe("beforeDisconnect",function(a){g.LG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){U7()&&(U7(),j8(null))});
j8(c)},o8=function(){var a=g.XH();
if(!a)return null;var b=Y7().he();return g.PH(b,a)},p8=function(a){g.DH("remote",a)},q8=function(){var a=U7();
return!!a&&3!=a.getProxyState()},r8=function(){$7()?T7().stopSession():b8("stopSession called before API ready.");
var a=U7();a&&(a.disconnect(1),j8(null))},Uya=function(){var a=Y7().ed.$_gos();
var b=k8();b&&U7()&&(g.OH(a,b)||a.push(b));return Sya(a)},t8=function(a,b){g.uG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.UB;this.A=this.o=null;this.I=(0,g.A)(this.UO,this);this.F=(0,g.A)(this.Cl,this);this.G=(0,g.A)(this.TO,this);this.J=(0,g.A)(this.hP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Uu,this),Vya(this))):c=3;0!=c&&(b?this.Uu(c):g.XE((0,g.A)(function(){this.Uu(c)},this),0));
var d=Qya();d&&s8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},u8=function(a){return new g.KI(a.B.getPlayerContextData())},Wya=function(a,b,c,d,e){var f=u8(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.OI(f,b,d);g.t(c)&&(g.MI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);v8(a,"setPlaylist",l);e||w8(a,f)},Vya=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Ba(this.eR,a),this))},a)},Xya=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},x8=function(a,b){50>a.C.Mc()&&g.WB(a.C,b)},y8=function(a,b,c){var d=u8(a);
g.MI(d,c);-1E3!=d.g&&(d.g=b);w8(a,d)},v8=function(a,b,c){a.B.sendMessage(b,c)},w8=function(a,b){Xya(a);
a.B.setPlayerContextData(g.PI(b));Vya(a)},s8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.Cl(null));
a.A=b;a.A&&(z8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.Cl(a.A.media[0]))},Yya=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=u8(a);b.contentId!=d.videoId&&z8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.MI(d,a.o.getEstimatedTime());w8(a,d)}else z8("No cast media video. Ignoring state update.")},z8=function(a){g.DH("CP",a)},A8=function(a,b,c){return(0,g.A)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),v8(this,b,c))},a)},Zya=function(a,b,c){var d=!1;
T7()||(a=new g.EI(a,b,c),a.subscribe("yt-remote-cast2-availability-change",function(a){g.pH("yt-remote-cast-available",a);g.LG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){S7("onReceiverSelected: "+a.friendlyName);
g.pH("yt-remote-cast-receiver",a);g.LG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){S7("onReceiverResumed: "+a.friendlyName);
g.pH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){S7("onSessionChange: "+g.LH(a));
a||g.rH("yt-remote-cast-receiver");g.LG("yt-remote-cast2-session-change",a)}),g.sa("yt.mdx.remote.cloudview.instance_",a,void 0),d=!0);
S7("cloudview.createSingleton_: "+d);return d},$ya=function(){var a=0<=g.Ib.search(/\ (CrMo|Chrome|CriOS)\//);
return g.qF||a},B8=function(a,b){$7()?T7().setConnectedScreenStatus(a,b):b8("setConnectedScreenStatus called before ready.")},aza=function(){S7("clearCurrentReceiver");
g.rH("yt-remote-cast-receiver")},bza=function(){if(f8("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Tya();a({command:"cast.sender.init"});return}}if(!window.chrome||f8("Edge"))e8();else if(Tya(),f8("Android")&&f8("Chrome/")&&window.navigator.presentation){a="";var b=g.Nh();55<=b?a="55":50<=b&&(a="50");g8("//www.gstatic.com/eureka/clank"+a+g.ora,e8)}else l8(0)},cza=function(a){a?(g.pH("yt-remote-session-app",a.app),g.pH("yt-remote-session-name",a.name)):(g.rH("yt-remote-session-app"),g.rH("yt-remote-session-name"));
g.sa("yt.mdx.remote.channelParams_",a,void 0)},dza=function(){var a=h8();
if(g.Xb(a)){a=g.WH();var b=g.qH("yt-remote-session-name")||"",c=g.qH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.sa("yt.mdx.remote.channelParams_",a,void 0)}},eza=function(){var a=o8();
a?(p8("Resume connection to: "+g.LH(a)),n8(a,0)):(g.dI(),aza(),p8("Skipping connecting because no session screen found."))},fza=function(a){p8("remote.onCastSessionChange_: "+g.LH(a));
if(a){var b=k8();b&&b.id==a.id?B8(b.id,"YouTube TV"):(b&&r8(),n8(a,1))}else U7()&&r8()},gza=function(){var a=Uya(),b=k8();
b||(b=o8());return g.db(a,function(a){return b&&g.IH(b,a.key)?!0:!1})},hza=function(){var a=g.qH("yt-remote-cast-receiver");
return a?a.friendlyName:null},iza=function(a,b,c,d,e,f){$ya()?Zya(b,e,f)&&(Z7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Pya(a,c):(window.__onGCastApiAvailable=function(b,d){b?Pya(a,c):(b8("Failed to load cast API: "+d),a8(!1),Z7(!1),g.rH("yt-remote-cast-available"),g.rH("yt-remote-cast-receiver"),Jya(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Rya():bza())):S7("Cannot initialize because not running Chrome")},
jza=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Ig(a)||"";b&&(this.port=":"+b);this.domain=g.Hg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Va(a,"10.0")&&(this.o=!1))},C8=function(){var a=gza();
!a&&c8()&&hza()&&(a={key:"cast-selector-receiver",name:hza()});return a},kza=function(){var a=Uya();
c8()&&g.qH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},lza=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.nE("MDX_CONFIG")||b;g.nH&&Dya();g.YH();m8||(m8=new jza(b?b.loungeApiHost:void 0),g.fI()&&(m8.g="/api/loungedev"));i8||(i8=g.x("yt.mdx.remote.deferredProxies_")||[],g.sa("yt.mdx.remote.deferredProxies_",i8,void 0));dza();var c=Y7();if(!c){var d=new g.qI(m8);g.sa("yt.mdx.remote.screenService_",d,void 0);c=Y7();iza(a,d,function(a){a?W7()&&B8(W7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.LG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),
b?b.appId:void 0,b?b.Y2:!1)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.sa("yt.mdx.remote.initialized_",!0,void 0),p8("Initializing: "+g.zg(b)),D8.push(g.HG("yt-remote-cast2-availability-change",function(){g.LG("yt-remote-receiver-availability-change")})),D8.push(g.HG("yt-remote-cast2-receiver-selected",function(){V7(null);
g.LG("yt-remote-auto-connect","cast-selector-receiver")})),D8.push(g.HG("yt-remote-cast2-receiver-resumed",function(){g.LG("yt-remote-receiver-resumed","cast-selector-receiver")})),D8.push(g.HG("yt-remote-cast2-session-change",fza)),D8.push(g.HG("yt-remote-connection-change",function(a){a?B8(W7(),"YouTube TV"):o8()||(B8(null,null),aza())})),a=h8(),b.isAuto&&(a.id+="#dial"),g.AF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),p8(" -- with channel params: "+
g.zg(a)),cza(a),c.start(),W7()||eza())},E8=function(){c8()?T7()?$7()?(S7("Requesting cast selector."),T7().requestSession()):(S7("Wait for cast API to be ready to request the session."),d8.push(g.HG("yt-remote-cast2-api-ready",E8))):b8("requestCastSelector: Cast is not initialized."):b8("requestCastSelector: Cast API is not installed!")},F8=function(a,b,c){g.L.call(this);
this.F=a;this.T=b;this.o=new g.rG(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.gQ);this.o.P(b,"captionschanged",this.SO);this.o.P(b,"captionssettingschanged",this.hD);this.o.P(b,"videoplayerreset",this.Go);this.o.P(b,"mdxautoplaycancel",this.GH);this.N=this.o.P(b,"onVolumeChange",this.CB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.OB,this);c.subscribe("remotePlayerChange",this.Fl,this);c.subscribe("remoteQueueChange",this.Go,this);c.subscribe("autoplayUpNext",this.pB,
this);c.subscribe("previousNextChange",this.LB,this);c.subscribe("nowAutoplaying",this.DB,this);c.subscribe("autoplayDismissed",this.oB,this);this.suggestion=null;this.G=new g.hR(64);this.A=new g.Ft(this.cD,500,this);g.M(this,this.A);this.B=new g.Ft(this.dD,1E3,this);g.M(this,this.B);this.C={};this.J=new g.Ft(this.DD,1E3,this);g.M(this,this.J);this.I=new g.sk(this.PM,1E3,this);g.M(this,this.I);this.L=g.y;this.hD();this.Go();this.Fl()},G8=function(a,b){var c=a.F,d=a.T.ga().lengthSeconds;
c.I=b||0;c.g.X("progresssync",b,d)},mza=function(a){G8(a,0);
a.A.stop();H8(a,new g.hR(64))},J8=function(a,b){if(I8(a)&&!a.D){var c=null;
b&&(c={style:a.T.xi()},g.dc(c,b));a.g.VC(a.T.ga().videoId,c);a.C=u8(a.g).o}},K8=function(a,b){var c=a.T.ag();
c?Wya(a.g,a.T.ga().videoId,b,c.ee(),c.listId.toString()):Wya(a.g,a.T.ga().videoId,b);H8(a,new g.hR(1))},nza=function(a,b){if(b){var c=a.T.yc("captions","tracklist",{fz:1});
c&&c.length?(a.T.Dd("captions","track",b),a.D=!1):(a.T.nl("captions"),a.D=!0)}else a.T.Dd("captions","track",{})},I8=function(a){return u8(a.g).videoId==a.T.ga().videoId},H8=function(a,b){a.B.stop();
var c=a.G;if(!g.nR(c,b)){var d=g.W(b,2);if(d!=g.W(a.G,2)){var e=a.T;g.B1(e.app,d,e.playerType)}a.G=b;oza(a.F,c,b)}},L8=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.sE()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.eX(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);pza(this,g.dW(a))},pza=function(a,b){if(3==a.A.Za()){var c={RECEIVER_NAME:a.A.yc("remote","currentReceiver").name};
c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.wb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.Ga("statustext",c);a.o.show()}else a.o.hide()},M8=function(a){g.ZW.call(this,a);
this.A={key:g.NH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.hR(64);this.I=0;var b=g.XV(a).F;b&&(b=b.A&&b.A.g)&&(b=new Q7(a,b),g.M(this,b));b=new L8(a);g.M(this,b);g.wW(a,b.element,4)},oza=function(a,b,c){a.F=c;
a.g.X("presentingplayerstatechange",new g.sR(c,b))},N8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)r8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga().videoId;if(c||d){var e=a.g.ag();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.dc(k).videoId}else f=[a.g.ga().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.Rz(),0),currentTime:a.g.getCurrentTime()}}else c=null;p8("Connecting to: "+g.zg(b));"cast-selector-receiver"==b.key?(V7(c||null),c=c||null,$7()?T7().setLaunchParams(c):b8("setLaunchParams called before ready.")):!c&&q8()&&W7()==b.key?g.LG("yt-remote-connection-change",!0):
(r8(),V7(c||null),c=Y7().he(),(c=g.PH(c,b.key))&&n8(c,1))}};
g.p(Q7,g.J0);Q7.prototype.I=function(){var a=this.T.yc("remote","receivers");a&&1<a.length&&!this.T.yc("remote","quickCast")?(this.F=g.Fb(a,this.B,this),g.K0(this,(0,g.J)(a,this.B)),a=this.T.yc("remote","currentReceiver"),this.sf(this.B(a)),this.enable(!0)):this.enable(!1)};
Q7.prototype.B=function(a){return a.key};
Q7.prototype.rf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
Q7.prototype.sd=function(a){g.J0.prototype.sd.call(this,a);this.T.Dd("remote","currentReceiver",this.F[a]);this.A.Ub()};
g.D(R7,g.QH);g.h=R7.prototype;g.h.he=function(a){return this.ed.$_gs(a)};
g.h.contains=function(a){return!!this.ed.$_c(a)};
g.h.get=function(a){return this.ed.$_g(a)};
g.h.start=function(){this.ed.$_st()};
g.h.Fp=function(a,b,c){this.ed.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ed.$_r(a,b,c)};
g.h.qp=function(a,b,c,d){this.ed.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.ed.$_ubk(this.o[a]);this.o.length=0;this.ed=null;R7.Z.W.call(this)};
g.h.xU=function(){this.X("screenChange")};
g.h.MQ=function(){this.X("onlineScreenChange")};
var X7=null,d8=[],i8=null,m8=null;g.D(t8,g.uG);g.h=t8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,A8(this,"play")):v8(this,"play"),y8(this,1,g.NI(u8(this))),this.X("remotePlayerChange")):x8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,A8(this,"pause")):v8(this,"pause"),y8(this,2,g.NI(u8(this))),this.X("remotePlayerChange")):x8(this,this.pause)};
g.h.PD=function(a){if(1==this.g){if(this.o){var b=u8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.wb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,A8(this,"seekTo",{newTime:a}))}else v8(this,"seekTo",{newTime:a});y8(this,3,a);this.X("remotePlayerChange")}else x8(this,g.Ba(this.PD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,A8(this,"stopVideo")):v8(this,"stopVideo");var a=u8(this);a.index=-1;a.videoId="";g.LI(a);w8(this,a);this.X("remotePlayerChange")}else x8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=u8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.A)(function(){z8("set receiver volume: "+d)},this),(0,g.A)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.A)(function(){z8("set receiver muted: "+b)},this),(0,g.A)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);v8(this,"setVolume",e)}c.muted=b;c.volume=a;w8(this,c)}else x8(this,g.Ba(this.setVolume,a,b))};
g.h.VC=function(a,b){if(1==this.g){var c=u8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.zg(b.style),g.dc(d,c.o));v8(this,"setSubtitlesTrack",d);w8(this,c)}else x8(this,g.Ba(this.VC,a,b))};
g.h.Tu=function(a,b){if(1==this.g){v8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Uc.id});var c=u8(this);c.audioTrackId=b.Uc.id;w8(this,c)}else x8(this,g.Ba(this.Tu,a,b))};
g.h.OD=function(a,b){if(1==this.g){if(a&&b){var c=u8(this);g.OI(c,a,b);w8(this,c)}v8(this,"previous")}else x8(this,g.Ba(this.OD,a,b))};
g.h.ND=function(a,b){if(1==this.g){if(a&&b){var c=u8(this);g.OI(c,a,b);w8(this,c)}v8(this,"next")}else x8(this,g.Ba(this.ND,a,b))};
g.h.Ax=function(){1==this.g?v8(this,"dismissAutoplay"):x8(this,this.Ax)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.X("proxyStateChange",a,this.g)}t8.Z.dispose.call(this)};
g.h.W=function(){Xya(this);this.B=null;this.C.clear();s8(this,null);t8.Z.W.call(this)};
g.h.Uu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.X("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.XB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.eR=function(a,b){this.X(a,b)};
g.h.UO=function(a){if(!a)this.Cl(null),s8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=u8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)z8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,w8(this,b)}};
g.h.Cl=function(a){z8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Yya(this),this.X("remotePlayerChange")};
g.h.TO=function(a){a?(Yya(this),this.X("remotePlayerChange")):this.Cl(null)};
g.h.hP=function(){var a=Qya();a&&s8(this,a)};
g.h.hc=function(a){g.DH("CP",a)};
var D8=[];g.h=jza.prototype;g.h.hi=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Pg(b+a,{})};
g.h.Su=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Vb:g.Ba(this.sU,c,!0),onError:g.Ba(this.rU,d),Fd:g.Ba(this.tU,d)};b&&(c.Nb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.kF(a,c)};
g.h.sU=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.rU=function(a,b){a(Error("Request error: "+b.status))};
g.h.tU=function(a){a(Error("request timed out"))};g.p(F8,g.L);g.h=F8.prototype;g.h.W=function(){g.L.prototype.W.call(this);this.A.stop();this.B.stop();this.L();this.g.unsubscribe("proxyStateChange",this.OB,this);this.g.unsubscribe("remotePlayerChange",this.Fl,this);this.g.unsubscribe("remoteQueueChange",this.Go,this);this.g.unsubscribe("autoplayUpNext",this.pB,this);this.g.unsubscribe("previousNextChange",this.LB,this);this.g.unsubscribe("nowAutoplaying",this.DB,this);this.g.unsubscribe("autoplayDismissed",this.oB,this);this.g=this.F=null};
g.h.rA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(I8(this)){if(1081!=u8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":u8(this.g).wb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.mj(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.g.Tu(this.T.ga().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":K8(this,this.T.getCurrentTime());break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.g.Tu(this.T.ga().videoId,c)}};
g.h.SO=function(a){this.rA("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.hD=function(){var a=this.T.yc("captions","track");g.Xb(a)||J8(this,a)};
g.h.CB=function(a){if(I8(this)){this.g.unsubscribe("remotePlayerChange",this.Fl,this);var b=Math.round(a.volume);a=!!a.muted;var c=u8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.J.start();this.g.subscribe("remotePlayerChange",this.Fl,this)}};
g.h.gQ=function(){g.Xb(this.C)||nza(this,this.C);this.D=!1};
g.h.OB=function(a,b){this.B.stop();2==b&&this.dD()};
g.h.Fl=function(){if(I8(this)){this.A.stop();var a=u8(this.g);switch(a.g){case 1081:H8(this,new g.hR(8));break;case 1:this.cD();H8(this,new g.hR(8));break;case 1083:case 3:H8(this,new g.hR(9));break;case 0:H8(this,new g.hR(2));this.I.stop();G8(this,this.T.ga().lengthSeconds);break;case 1082:H8(this,new g.hR(4));break;case 2:H8(this,new g.hR(4));G8(this,g.NI(a));break;case -1:H8(this,new g.hR(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},H8(this,new g.hR(128,
a))}a=u8(this.g).o;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,nza(this,a));a=u8(this.g);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.Oe()==a.muted||this.J.isActive()||this.DD()}else mza(this)};
g.h.LB=function(){this.T.X("mdxpreviousnextchange")};
g.h.Go=function(){I8(this)||mza(this)};
g.h.GH=function(){this.g.Ax()};
g.h.pB=function(a){a&&(a=g.kF("/watch_queue_ajax",{method:"GET",ad:{action_get_watch_queue_item:1,video_id:a},Vb:(0,g.A)(this.fS,this)}))&&(this.L=(0,g.A)(a.abort,a))};
g.h.fS=function(a,b){var c=new g.fQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.X("mdxautoplayupnext",c)};
g.h.DB=function(a){(0,window.isNaN)(a)||this.T.X("mdxnowautoplaying",a)};
g.h.oB=function(){this.T.X("mdxautoplaycanceled")};
g.h.PM=function(a,b){-1==u8(this.g).g?K8(this,a):b&&this.g.PD(a)};
g.h.DD=function(){if(I8(this)){var a=u8(this.g);this.o.Ca(this.N);a.muted?this.T.mute():this.T.eg();this.T.setVolume(a.volume);this.N=this.o.P(this.T,"onVolumeChange",this.CB)}};
g.h.cD=function(){this.A.stop();if(!this.g.la()){var a=u8(this.g);a.wb()&&H8(this,new g.hR(8));G8(this,g.NI(a));this.A.start()}};
g.h.dD=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(L8,g.Y);L8.prototype.B=function(a){pza(this,a.state)};g.p(M8,g.ZW);g.h=M8.prototype;g.h.create=function(){lza(g.gO(g.X(this.g)));this.D.push(g.HG("yt-remote-before-disconnect",this.PO,this));this.D.push(g.HG("yt-remote-connection-change",this.oR,this));this.D.push(g.HG("yt-remote-receiver-availability-change",this.MB,this));this.D.push(g.HG("yt-remote-auto-connect",this.mR,this));this.D.push(g.HG("yt-remote-receiver-resumed",this.lR,this));this.MB()};
g.h.load=function(){this.g.Fq();g.ZW.prototype.load.call(this);this.C=new F8(this,this.g,this.o);var a=Oya();a=a?a.currentTime:0;var b=q8()?new t8(U7(),void 0):null;0==a&&b&&(a=g.NI(u8(b)));0!=a&&(this.I=a||0,this.g.X("progresssync",a,void 0));oza(this,this.F,this.F);g.G1(this.g.app,6)};
g.h.unload=function(){this.g.X("mdxautoplaycanceled");this.B=this.A;g.Ze(this.C,this.o);this.o=this.C=null;g.ZW.prototype.unload.call(this);g.G1(this.g.app,5)};
g.h.W=function(){g.IG(this.D);g.ZW.prototype.W.call(this)};
g.h.tl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.rA.apply(this.C,[].concat([a],g.na(c)))};
g.h.rI=function(){return this.loaded?this.C.suggestion:null};
g.h.Tf=function(){return this.o?u8(this.o).Tf:!1};
g.h.hasNext=function(){return this.o?u8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.tM=function(){var a=u8(this.o),b=this.g.ga();return{allowSeeking:this.g.Td(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.G)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.G)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.F?a.B+((0,g.G)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.G)()-a.A)/1E3:a.D}};
g.h.uM=function(){this.o&&this.o.ND()};
g.h.vM=function(){this.o&&this.o.OD()};
g.h.PO=function(a){1==a&&(this.J=this.o?u8(this.o):null)};
g.h.oR=function(){var a=q8()?new t8(U7(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ye(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.Pz(a.videoId,g.NI(a)));this.g.X("videodatachange","newdata",this.g.ga(),3)};
g.h.MB=function(){this.G=[this.A].concat(kza());var a=C8()||this.A;N8(this,a);this.g.za("onMdxReceiversChange")};
g.h.mR=function(){var a=C8();N8(this,a)};
g.h.lR=function(){this.B=C8()};
g.h.sM=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?E8():N8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&E8(),!0):!1}};
g.h.wM=function(){v8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Gd=function(){return!1};g.kX("remote",M8);})(_yt_player);
