(function(d){if(!(/mapquest/.test(location.hostname)||window.bN_cfg&&bN_cfg.upgradeIE===!1)){var b=navigator.userAgent,j;/MSIE [67]/i.test(b)&&!d.documentMode&&!/omBrowser/.test(b)&&(j=function(){try{var b=d.body,p=b.firstChild,e=d.createElement("div");e.innerHTML='<div class="Contact Dave Artz if you have a problem with this banner" style="clear: both; height: 59px; padding:0; margin:0; position: relative; text-align: center"><a href="http://browsers.aol.com/customie/aol/download.html?ocid=ie6_countdown_bannercode"><img src="http'+
(location.protocol==="http:"?"://o":"s://s")+'.aolcdn.com/os/aol/aol-ie6-countdown.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a></div>';b.insertBefore(e.firstChild,p)}catch(n){setTimeout(j,500)}},j())}})(document);
(function(d,b){function j(a){for(var l=[1732584193,4023233417,2562383102,271733878,3285377520],d=a,b=[],f=0,a=0;a<d.length;a++){var k=d.charCodeAt(a);k<128?b[f++]=k:(k<2048?b[f++]=k>>6|192:((k&64512)==55296&&a+1<d.length&&(d.charCodeAt(a+1)&64512)==56320?(k=65536+((k&1023)<<10)+(d.charCodeAt(++a)&1023),b[f++]=k>>18|240,b[f++]=k>>12&63|128):b[f++]=k>>12|224,b[f++]=k>>6&63|128),b[f++]=k&63|128)}d="";for(f=0;f<b.length;f++)d+=String.fromCharCode(b[f]);a=d;k=a.length;a+=String.fromCharCode(128);for(var e=
Math.ceil(32*(a.length/4+2)/512),d=Array(e),b=0;b<e;b++){var j=b*64;d[b]=Array(16);for(f=0;f<16;f++){var o=j+f*4;d[b][f]=0;a.length>=o+1&&(d[b][f]=a.charCodeAt(o)<<24|a.charCodeAt(o+1)<<16|a.charCodeAt(o+2)<<8|a.charCodeAt(o+3))}}d[e-1][14]=k>>>29;d[e-1][15]=k<<3;for(b=0;b<d.length;b++){a=Array(80);for(f=0;f<16;f++)a[f]=d[b][f];for(f=16;f<a.length;f++)a[f]=(a[f-3]^a[f-8]^a[f-14]^a[f-16])<<1|(a[f-3]^a[f-8]^a[f-14]^a[f-16])>>>31;for(var k=l[0],e=l[1],j=l[2],o=l[3],p=l[4],f=0;f<80;f++){var i,n;f<=19?
(i=e&j|~e&o,n=1518500249):f>19&&f<=39?(i=e^j^o,n=1859775393):f>39&&f<=59?(i=e&j|e&o|j&o,n=2400959708):(i=e^j^o,n=3395469782);i=(k<<5|k>>>27)+i+p+n+a[f];p=o;o=j;j=e<<30|e>>>2;e=k;k=i}l[0]=l[0]+k>>>0;l[1]=l[1]+e>>>0;l[2]=l[2]+j>>>0;l[3]=l[3]+o>>>0;l[4]=l[4]+p>>>0}for(b=0;b<l.length;b++)d=("00000000"+l[b].toString(16)).substr(-8),l[b]=d;return l[0]+l[1]+l[2]+l[3]+l[4]}var i=function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},p=function(a){return encodeURIComponent(a.replace(/\r\n|\n|\r|\u0085|\u000C|\u2028|\u2029/g,
" "))},e=/^[\],:{}\s]*$/,n=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,z=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,I=/(?:^|:|,)(?:\s*\[)+/g,M=function(a){var l=1;if(typeof d.bN_cfg==="undefined")l=0;else try{if(b.getElementById){d.bN_cfg.adBlock=!1;var e=b.body,j=e.firstChild,f="bn_ad_tst_"+Math.floor(Math.random()*1E4+1),k=b.createElement("div");k.innerHTML='<div id="'+f+'" class="afs_ads pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links" style="width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;">&nbsp</div>';
e.insertBefore(k.firstChild,j);var i=b.getElementById(f);if(!i||i.innerHTML.length==0||i.clientHeight===0||i.clientWidth===0||i.offsetWidth===0||d.document.body.getAttribute("abp")!==null)d.bN_cfg.adBlock=!0;i.parentNode.removeChild(i);a.set("dL_abp",d.bN_cfg.adBlock?1:0)}}catch(p){l=0}return l};if(!d.Aol)d.Aol={};Aol.bind=function(a,b,d){a.attachEvent?a.attachEvent("on"+b,d):a.addEventListener&&a.addEventListener(b,d,!1)};Aol.unbind=function(a,b,d){a.detachEvent?a.detachEvent("on"+b,d):a.removeEventListener&&
a.removeEventListener(b,d,!1)};Aol.get=function(a,d){d=d||b;return a.charAt(0)==="#"?d.getElementById(a.substr(1)):d.getElementsByTagName(a)};Aol.trim=i;Aol.stripTags=function(a){return a.replace(/<[^>]*>/g,"")};Aol.encode=p;Aol.isArray=function(a){return a.constructor.toString().indexOf("Array")!==-1};Aol.isObject=function(a){return typeof a==="object"};Aol.isString=function(a){return typeof a==="string"};Aol.isFunction=function(a){return typeof a==="function"};Aol.isNumber=function(a){return typeof a===
"number"};Aol.extend=function(){var a=arguments,d,b=a.length,e,f=a[0],k;for(d=1;d<b;d+=1)for(e in k=a[d],k)f[e]=k[e];return f};Aol.toQueryString=function(a,d){var b=[],e,d=d||"&";for(e in a)a.hasOwnProperty(e)&&"undefined"!==typeof a[e]&&b.push(p(e)+"="+p(a[e].toString()));return b.length?d+b.join("&"):""};Aol.parseJSON=function(a){if(typeof a!=="string"||!a)return null;a=i(a);if(d.JSON&&d.JSON.parse){var b={};try{b=d.JSON.parse(a)}catch(j){bN.set("dL_exc",1,1),d.console&&console.log("Unable to parse JSON string: "+
a.toString())}return b}if(e.test(a.replace(n,"@").replace(z,"]").replace(I,"")))return(new Function("return "+a))();d.console&&console.log("Bad JSON: "+a)};Aol.removeUrlParam=function(a,d){var b=a.split("?");if(b.length>=2){for(var e=encodeURIComponent(d)+"=",f=b[1].split(/[&;]/g),k=f.length;k-- >0;)f[k].indexOf(e,0)===0&&f.splice(k,1);a=f.length>0?b[0]+"?"+f.join("&"):b[0]}return a};Aol.getUrlParam=function(a,b){var b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),d=RegExp("[\\?&]"+b+"=([^&#]*)").exec(a);
return d===null?"":decodeURIComponent(d[1].replace(/\+/g," "))};Aol.getCookie=function(a){var d,e,j=b.cookie.split(";");for(d=0;d<j.length;d+=1)if(e=j[d].split("="),i(e[0])===a)return e[1];return""};Aol.setCookie=function(d,e,j,i,f){var k=new Date;f!==void 0&&k.setTime(k.getTime()+f*6E4);b.cookie=d+"="+escape(e)+"; domain="+escape(j)+"; path="+escape(i)+(f===void 0?"":"; expires="+k.toUTCString())};Aol.getCurrentY=function(){var a=b.body?b.body.clientHeight:0;return(d.innerHeight||b.documentElement.clientHeight||
a)+(b.documentElement.scrollTop||d.pageYOffset||0)};Aol.getPageHeight=function(){var d=0,e=0;b.body&&(d=Math.max(b.body.scrollHeight,b.body.offsetHeight,b.body.clientHeight));b.documentElement&&(e=Math.max(b.documentElement.scrollHeight,b.documentElement.offsetHeight,b.documentElement.clientHeight));return Math.max(d,e)};Aol.getPageId=function(){var b="",b=d.location,e=b.hostname,i=decodeURIComponent(e+b.pathname);i.charAt(i.length-1)=="/"&&(i=i.substring(0,i.length-1));b=e;e.length>48&&(b=j(e));
return b+j(i)};Aol.detectAdblock=M;Aol.sendAdblockPing=function(d){M(d)==1&&d.ping("abp")};Aol.loadScript=function(b){var e=new XMLHttpRequest;e.open("GET",b,!1);e.onreadystatechange=function(){if(e.readyState===4){var b=e.response||e.responseText;switch(e.status){case 200:eval.apply(d,[b])}}};e.send(null)}})(window,document);
(function(d,b){window[d]||(window[d]={});var j=b.plugins,i,p,e,n=parseInt;window[d].flashDetect=function(){if(!i)if(j&&(p=j["Shockwave Flash"])){if((e=p.description)&&b.mimeTypes&&b.mimeTypes["application/x-shockwave-flash"]&&b.mimeTypes["application/x-shockwave-flash"].enabledPlugin)e=e.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),i=[n(e.replace(/^(.*)\..*$/,"$1"),10),n(e.replace(/^.*\.(.*)\s.*$/,"$1"),10),/[a-zA-Z]/.test(e)?n(e.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0]}else if(window.ActiveXObject)try{if(p=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))if(e=p.GetVariable("$version"))e=e.split(" ")[1].split(","),i=[n(e[0],10),n(e[1],10),n(e[2],10)]}catch(d){}return i}})("Aol",navigator);
(function(d,b,j){if(!d.bN){var i=function(){return(new Date).getTime()},p=i(),e=Aol.bind,n=Aol.get,z=Aol.trim,I=Aol.stripTags,M=Aol.isArray,a=Aol.isObject,l=Aol.isString,za=Aol.isNumber,ea=Aol.extend,f=Aol.toQueryString,k=Aol.parseJSON,L=Aol.removeUrlParam,fa=Aol.getUrlParam,o=Aol.getCookie,O=Aol.setCookie,P=Aol.getCurrentY,Q=Aol.getPageHeight,Aa=Aol.getPageId,Ba=Aol.detectAdblock,Ca=Aol.sendAdblockPing,s=Aol.encode,Da=[],H,A,J,R=100,ga=b.title,w=b.referrer,t=d.location,B=t.hostname,Ea=screen.width+
"x"+screen.height,F={},E={},S=[],ha=0,Fa=b.documentElement.clientWidth+"x"+b.documentElement.clientHeight,Ga=(new Date).getTimezoneOffset(),T=n("iframe"),ia=1,K=0,U=0,C=0,V=0,W=100,ja=3,X="http://cs600.wpc.alphacdn.net/80B30D/cedexis/img/359c/r20-100KB.png",Y=2,ka=!1,Z=0,$=100,aa=0,v="b-aws.aol.com",N=!1,la=[],ba=0,ma=!1,na="http://gp1.wpc.edgecastcdn.net/00222B/beluga/beacon/beluga_beacon.js",oa=0,pa=!0,Ha=function(){var c=1;try{c=d.devicePixelRatio}catch(b){}return c+""},Ia=function(c,b){if(typeof d.matchMedia==
"undefined")return null;for(var a in b)if(d.matchMedia("("+c+":"+b[a]+")").matches)return b[a]+"";return null},sa=function(){if(!oa&&qa()){var c=Math.round((i()-p)/1E3),c=c>0?c:0;c<900&&m.set("dL_tscp",c,1);m.ping("scroll");oa=1;ra(R)}},ta=function(){var c;if(c=d.s_265){c={dL_ch:c.channel,dL_dpt:c.prop1,dL_sDpt:c.prop2,dL_cmsID:c.prop9,dL_flid:c.prop6,dL_amp:c.prop53,dL_evft:c.eVar14,dL_evfs:c.eVar57,dL_vid:typeof dL_vid!=="undefined"?dL_vid:c.prop62};var b,a,e;for(e in c)if(c.hasOwnProperty(e)&&
(b=c[e])){if(a=m.get(e))if(typeof a!=="undefined"&&a!=""&&(e!="dL_flid"||e=="dL_flid"&&a.trim().length>1))continue;m.set(e,b)}}},ua=function(c,b){var a;return function(){function e(){a=j;c.call(this)}a||(a=d.setTimeout(e,b))}},va=function(){var c=P();C<c&&(C=c,V=Math.round(C/Math.max(C,Q())*100))},wa=function(){pa=b[A]?!1:!0},qa=function(){if(Math.floor(Math.random()*100+1)<=W){var c=P(),c=[["dL_crY",c,1],["dL_crYP",Math.round(c/Math.max(c,Q())*100),1],["dL_mxY",C,1],["dL_mxYP",V,1],["dL_inY",K,1],
["dL_inYP",U,1]];m.set(c);return!0}else return!1},Ja=function(){if(Math.floor(Math.random()*1E4+1)/100<=ja){if(typeof d.performance!=="object")return!1;if(typeof d.performance.timing!=="object")return!1;var c=d.performance.timing,c=[["conn_ms",r(c,"connectEnd","connectStart",!0),!0],["dns_ms",r(c,"domainLookupEnd","domainLookupStart",!0),!0],["resp_ms",r(c,"responseEnd","responseStart",!0),!0],["sconn_ms",r(c,"connectEnd","secureConnectionStart",!0),!0],["net_ms",r(c,"requestStart","navigationStart",
!0),!0],["app_ms",r(c,"responseStart","requestStart",!0),!0],["proc_ms",r(c,"domContentLoadedEventEnd","responseStart",!0),!0],["load_ms",r(c,"domComplete","domContentLoadedEventEnd",!0),!0]];m.set(c);m.ping("rum");return!0}else return!1},Ka=function(){if(typeof d.performance!=="object")return!1;if(typeof d.performance.timing!=="object")return!1;if(typeof d.performance.getEntriesByType!=="function")return!1;if(t.protocol!=="http:")return!1;var c=X+"?"+(new Date).getTime(),b=new XMLHttpRequest;typeof b.withCredentials!==
"undefined"?(b.open("GET",c,!0),b.send(),b.onreadystatechange=function(){if(b.readyState==0||b.readyState==4){var a=b.getResponseHeader("server");a:for(var e=d.performance.getEntriesByType("resource"),h=0;h<e.length;h++){var g=e[h];if(typeof g==="object"&&typeof g.name==="string"&&g.name.toUpperCase()===c.toUpperCase()){for(var e=r(g,"domainLookupEnd","domainLookupStart",!1),h=r(g,"connectEnd","connectStart",!1),f=r(g,"responseStart","startTime",!1),j=r(g,"responseStart","requestStart",!1),i=r(g,
"responseEnd","responseStart",!1),k=e+h+j+i,a=[["rtm_src",g.name.substring(0,g.name.indexOf("?")),!0],["rtm_srv",a,!0],["dns_mu",e,!0],["tcp_mu",h,!0],["ttfb_mu",f,!0],["waiting_mu",j,!0],["content_mu",i,!0],["network_mu",k,!0]],g=2;g<a.length;g++){if(typeof a[g][1]!=="undefined"&&isNaN(a[g][1]))break a;if(a[g][1]<0)break a}m.set("dL_cust01",X,1);m.set(a);m.ping("rtm");break a}}}}):alert("this browser does not support XMLHTTPRequest2")},r=function(c,b,d,a){return typeof c!=="object"?-1:typeof c[b]!==
"number"||typeof c[d]!=="number"?-1:isNaN(c[b])||isNaN(c[d])?-1:a===!0&&(c[b]===0||c[d]===0)?-1:c[b]-c[d]},La=function(){m.ping("onblur");return!0},Ma=function(){m.ping("onfocus");return!0},Na=function(){ha=i()-p;K=P();U=Math.round(K/Math.max(K,Q())*100);C=K;V=U;ia&&function(c,b){var d,a=c.length,h,g,f;for(d=0;d<a;d+=1){f=b.indexOf(".")===-1?d.toString():b+d;try{h=c[d].contentWindow.document,h.__bNframe=f,e(h,"click",m.click),g=n("iframe",h),g.length>0&&arguments.callee(g,f+".")}catch(j){}}}(T,"");
m.set("kb",Math.round(n("html")[0].innerHTML.length/1024))},ca=1,ra=function(c){var b,d=i();do if(b=i(),ca)break;while(b-d<c)},Oa=function(){var c=fa(t,"ncid"),b=fa(t,"icid"),d=[{searchStr:"FBAN",searchIn:navigator.userAgent,refUrl:"http://facebook.app.useragent/"},{searchStr:"Twitter",searchIn:navigator.userAgent,refUrl:"http://twitter.app.useragent/"},{searchStr:"Pinterest",searchIn:navigator.userAgent,refUrl:"http://pinterest.app.useragent/"},{searchStr:"GSA",searchIn:navigator.userAgent,refUrl:"http://gsa.app.useragent/"},
{searchStr:"IMDb",searchIn:navigator.userAgent,refUrl:"http://imdb.app.useragent/"},{searchStr:"Flipboard",searchIn:navigator.userAgent,refUrl:"http://flipboard.app.useragent/"},{searchStr:"FB_IAB",searchIn:navigator.userAgent,refUrl:"http://facebook.app.useragent/"}],c=[{searchStr:"emlblst",searchIn:c,refUrl:"mail://email.campaign/ncid_"+c},{searchStr:"emlblst",searchIn:b,refUrl:"mail://email.campaign/icid_"+b},{searchStr:c,searchIn:c,refUrl:"http://ncid.campaign/ncid_"+c},{searchStr:b,searchIn:b,
refUrl:"http://icid.campaign/icid_"+b}],b=d.length,a=c.length,e,g;for(e=0;e<b;e++)if(g=d[e],g.searchStr.length&&g.searchIn.indexOf(g.searchStr)>-1){m.set("r_useragent",g.refUrl,1);break}for(e=0;e<a;e++)if(g=c[e],g.searchStr.length&&g.searchIn.indexOf(g.searchStr)>-1){m.set("r_campaign",g.refUrl,1);break}},xa=function(c){var b=new Blob(["(function () {'use strict';function ping(url) {try {var req = new XMLHttpRequest(); req.open('GET',url,false); req.withCredentials = true;req.send(); console.log(req.responseText); return req.responseText;} catch(e) { return e.toString();}}; onmessage = function (e) {ping(e.data);}}());"],
{type:"application/javascript"}),a=d.URL.createObjectURL(b),b=new Worker(a);b.onmessage=function(){};b.postMessage(c);setTimeout(function(){d.URL.revokeObjectURL(a)},200)},da=function(c,a){if(typeof d.bN_cfg==="undefined")return!1;var e=i(),j=new Image,h=w,g=b.querySelector("link[rel='canonical']");Oa();e="?ts="+e+"&h="+s(B)+"&v="+m.v+"&r="+s(h)+"&l="+ha+"&k="+(navigator.cookieEnabled?1:0)+"&m="+Ea+"&bd="+Fa+"&tz="+Ga+"&ms="+(e-p)+"&da_pr="+Ha()+"&da_ar="+Ia("device-aspect-ratio",["2/3","40/71","3/4",
"16/9","16/10"]);F.t||(e+="&t="+s(ga));typeof g!=="undefined"&&g!=null&&typeof g.href!=="undefined"&&!F.dL_url&&(e+="&dL_url="+s(g.href));typeof d.bN_cfg!=="undefined"&&d.bN_cfg.x&&(e+="&dL_x=1");j.onload=function(){ca=1};ca=0;A in b&&(wa(),m.set("pgvis",pa?1:0,1));c==="vanity/"&&m.set("pgid",Aa(),1);g=["http"+(t.protocol==="http:"?"://":"s://"),H,"/",c,e,a,f(ea({},F,E))].join("");!N&&(/Chrome/i.test(navigator.userAgent)||/Safari/i.test(navigator.userAgent))&&c=="ping"&&g.indexOf("nm=scroll")!=-1&&
d.Worker?(j=g+"&txt=1&dL_r="+s(t.href),xa(j)):j.src=g;if(N&&typeof v!=="undefined"&&la.indexOf(g)===-1){la.push(g);var k=g.replace(/(^https?\:\/\/)(.*?)(\/.*$)/,"$1"+v+"$3");k.indexOf(v)===-1&&(k=["http"+(t.protocol==="http:"?"://":"s://"),v,"/",c,e,a,f(ea({},F,E))].join(""));(/Chrome/i.test(navigator.userAgent)||/Safari/i.test(navigator.userAgent))&&c=="ping"&&k.indexOf("nm=scroll")!=-1&&d.Worker?(j=k+"&txt=1&dL_r="+s(t.href),xa(j)):setTimeout(function(){(new Image).src=k},0)}E={};!b.all&&c==="click"&&
a.indexOf("%23")===-1&&a.indexOf("javascript%3A")===-1&&a.indexOf("&tag=")===-1&&ra(R)},ya=function(c){var a=Da.toString(),f=RegExp(B+"![0-9]+"),k,c=c||d.bN_cfg||0,h,g,i,l,n=1,s=1;typeof b.hidden!=="undefined"?(A="hidden",J="visibilitychange"):typeof b.mozHidden!=="undefined"?(A="mozHidden",J="mozvisibilitychange"):typeof b.msHidden!=="undefined"?(A="msHidden",J="msvisibilitychange"):typeof b.webkitHidden!=="undefined"&&(A="webkitHidden",J="webkitvisibilitychange");if(c){if(c.d)h=p,p=c.d,m.set("dL_stod",
p-h);c.h&&(a+=c.h.toString());if(c.b)H=c.b;c.x&&(ga="",w=L(w,"q"),w=L(w,"query"),w=L(w,"o_q"),w=L(w,"as_q"));c.p&&m.set(c.p);if(c.w)R=c.w;c.view===0&&(n=0);c.click===0&&(s=0);c.iframes===0&&(ia=0);if(typeof c.scroll!=="undefined")W=c.scroll;if(typeof c.rum!=="undefined")ja=c.rum;if(typeof c.rtm!=="undefined")Y=c.rtm;h=Math.floor(Math.random()*1E4+1)/100;Y>0&&h<=Y&&(ka=!0,h=Math.random(),X=h<1/3?"http://cs600.wac.alphacdn.net/00B30D/sla/perf_check.html":h<2/3?"http://cs600.wpc.alphacdn.net/00B30D/sla/perf_check.html":
"http://adn.b30d.edgecastcdn.net/00B30D/sla/perf_check.html");if(typeof c.adblock!=="undefined")$=c.adblock;if(typeof c.echosrv!=="undefined"&&typeof c.b2!=="undefined")aa=c.echosrv,v=c.b2;h=Math.floor(Math.random()*1E4+1)/100;aa>0&&h<=aa&&(N=!0);if(typeof c.vdms_url!=="undefined")na=c.vdms_url;if(typeof c.vdms!=="undefined")ba=c.vdms;h=Math.floor(Math.random()*1E4+1)/100;ba>0&&h<=ba&&(ma=!0);if(typeof c.engagement!=="undefined")Z=c.engagement,h=Math.floor(Math.random()*100+1),Z>0&&h<=Z&&(e(d,"blur",
La),e(d,"focus",Ma))}if(a.indexOf(B)!==-1){h=B.split(".");g=h.length-1;h=B==="localhost"||/\d{1,3}/.test(h[g])?"aol.com":h[g-1]+"."+h[g];H||(H="b."+h);g=function(c){var b=!0;try{JSON.parse(c)}catch(a){b=!1}return b};for(var r=b.querySelectorAll('script[type="application/ld+json"]'),q=!0,x=!0,z=!0,u=0;u<r.length&&z;u++){try{if(i=r[u].innerText,g(i)&&(l=JSON.parse(i),typeof l["@type"]!=="undefined")){var y=l["@type"].toLowerCase().trim();if(y.includes("article")||y.includes("blogposting")||y.includes("imagegallery"))if(q&&
typeof l.dateModified!=="undefined"&&(m.set("js_dtmod",l.dateModified,1),q=!1),x&&typeof l.keywords!=="undefined"){for(var t=l.keywords,u=0;u<t.length&&x;u++){var D=t[u].toLowerCase().trim();D.indexOf("@sponsor")===0&&(m.set("dL_cmpg",D,1),x=!1)}if(x)for(u=0;u<t.length&&x;u++)D=t[u].toLowerCase().trim(),D.indexOf("@custom")===0&&(m.set("dL_cmpg",t[u],1),x=!1)}}}catch(E){console.log(E.message)}z=q||x}i=o("UNAUTHID");i!==""&&(H="b.aol.com",h!=="aol.com"&&O("UNAUTHID",i,h,"/",4382.904*60));N&&(i=o("T_UNAUTHID"),
l=h,i!==""?(l!=="aol.com"&&O("T_UNAUTHID",i,l,"/",4382.904*60),v=typeof c!=="undefined"&&typeof c.b!=="undefined"?c.b.replace(/^.*?./,"b-aws"):"b-aws.aol.com"):v=typeof c!=="undefined"&&typeof c.b!=="undefined"?c.b.replace(/^.*?./,"b-aws"):"b-aws."+l);k=(k=a.match(f))?parseInt(k[0].replace(B+"!",""),10):0;if(Math.floor(Math.random()*k)===0){e(d,"load",Na);typeof b.addEventListener==="undefined"||typeof b[A]==="undefined"||b.addEventListener(J,wa,!1);W>0&&(e(d,"scroll",ua(va,200)),e(d,"resize",ua(va,
200)),e(d,"unload",sa),/Firefox/.test(navigator.userAgent)||e(d,"beforeunload",sa));s&&e(b,"click",m.click);(a=Aol.flashDetect())&&m.set("fv",a[0]+"."+a[1]);d.adsScr!==j&&m.set("ads_grp",d.adsScr);a=o("_utd");a!==""&&m.set("dL_utd",a);a=o("_vdl");a===""&&(O("_vdl",1,B,"/",4382.904*60),m.set("dL_hnu",1,1));a=Math.floor(Math.random()*100+1);$>0&&a<=$&&typeof d.bN_cfg!=="undefined"&&Ba(m)==0&&setTimeout(function(){Ca(m)},750);var G=0;F.dL_ch&&(G=20);(function Pa(){d.s_265?(ta(),n&&m.view()):G++===20?
(m.set("omniTimeOut",1),n&&m.view()):setTimeout(Pa,500)})();setTimeout(function(){Ja()},2500);ka&&setTimeout(function(){Ka()},2500);ma&&setTimeout(function(){var c=b.createElement("script"),a=b.getElementsByTagName("head")[0];c.src=na;a.appendChild(c)},2500)}}},m={v:60,view:function(c){ta();c&&m.set(c);da("vanity/",c)},click:function(c){var c=c||d.event,a=c.srcElement||c.target||c,e,f=b.body,h=b.documentElement,g,n,p,o,r,t,q="",x="",w=0,u=0,y,B,D=[],A=E.subUrl,G=0,v;e=(y=F.d_clk)!=null?y:E.d_clk;
if(e!=null&&e==1)return!0;if(a){l(a)&&(a=b.getElementById(a));for(e=a;a&&a.nodeName!=="HTML";){g=a.nodeName;y=!1;if(a.className&&typeof a.className==="string"&&(a.className.indexOf("bNp ")==0||a.className.indexOf(" bNp ")>=0||a.className.indexOf(" bNp")==a.className.length-4))y=!0;if(o=a.getAttribute("data-beacon"))o=k(o),(B=o.p)&&D.push(B);if(a.className&&typeof a.className==="string"&&a.className.indexOf("bN")!==-1&&(q+="&tag="+g,(n=a.innerHTML)&&(n=I(n))))n.length>128&&(n=n.substr(0,128)),q+=y?
".X":"."+z(n);if(g==="IMG")q+="&img="+s(a.src),(o=a.alt)&&(q+=y?"&alt=X":"&alt="+s(z(o)));if(g==="A"&&(o=a.href,A!=null&&A.length>0&&(o=A),o)){if(o.indexOf("everydayhealth.com")!==-1){var C=o.match(/aolcat=(\w*)/),H=new Image,C=C?C[1]:"HLT";H.src="http://tacoda.at.atwola.com/rtx/r.gif?cmd="+C+"&si=18294&pi=L&xs=3&pu="+s(o)+"&r=&df=1&v=5.5&cb="+i()}if(y)q+="&ah=X&at=X";else if(q+="&ah="+s(o),(r=a.innerHTML)&&(r=I(r)))q+="&at="+s(z(r))}if(g==="BUTTON"||g==="INPUT"&&(p=a.type)&&(p==="button"||p==="submit"||
p==="image")){q+="&btn="+g;if(p=a.type)q+="."+s(p);if(g=a.name)q+="."+s(g);if(g=a.value)q+=y?".X":"."+s(z(g));if((t=a.innerHTML)&&(t=I(t)))q+=y?".X":"."+s(z(t))}x+=a.id?a.id+"+":"";a=a.parentNode}if(q==""&&e.nodeName=="DIV"&&(q+="&tag="+e.nodeName,(n=e.innerHTML)&&(n=I(n))))n.length>128&&(n=n.substr(0,128)),q+="."+z(n);if(q!==""){if(D.length)for(a=D.length;G<a;G+=1)for(v in n=["plid","plids","lnid","mnid","cid"],D[G])D[G].hasOwnProperty(v)&&(n.indexOf(v)==-1||m.get(v,1)==j)&&m.set(v,D[G][v],1,1);
if(c.pageX||c.pageY)w=c.pageX,u=c.pageY;else if(c.clientX||c.clientY)w=c.clientX+f.scrollLeft+h.scrollLeft,u=c.clientY+f.scrollTop+h.scrollTop;q+="&cx="+w+"&cy="+u;c=e.ownerDocument;if(b!==c){c=c.__bNframe;x+="iframe."+c+"+";a=c.indexOf(".")===-1?T[c]:T[c.substr(0,c.indexOf("."))];do g=a.nodeName,x+=a.id?a.id+"+":"",a=a.parentNode;while(g!=="HTML")}x&&(q+="&id="+s(x.slice(0,-1)));qa();da("click",q)}}},ping:function(c,b,d){a(b)&&(d=b,b=j);(d=d||"")&&m.set(d);var d=b*1E3,e=function(){da("ping","&nm="+
s(c))};S[c]&&clearInterval(S[c]);if(za(b))if(b>0)S[c]=setInterval(e,d);else return;e()},get:function(a,b){return b==1?E[a]:F[a]},set:function(b,d,e,f){var h,g;if(a(b))if(h=b,M(h)){g=0;for(b=h.length;g<b;g+=1)m.set(h[g][0],h[g][1],h[g][2]?1:0)}else{if(h._c)f=e=1,h._c="";for(g in h)h.hasOwnProperty(g)&&m.set(g,h[g],e,f)}else l(b)&&(h=e?E:F,d===""?delete h[b]:f&&h[b]?h[b]+="+"+d:h[b]=d)},init:function(a){a.h=B;ya(a)}};ya();d.bN=m}})(window,document);
if(!Array.prototype.indexOf)Array.prototype.indexOf=function(d,b){b=b||0;if(b>this.length)return-1;for(var j=0;j<this.length;j++)if(this[j]==d&&b<=j)return j;else if(this[j]==d&&b>j)break;return-1};
