/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var u=b.document,z=b.navigator,C="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),G=!1,D=0,E=[],l=[],p=[],s=[],x={},f=0,r=[],k=null,e={},g={},m=null,q,V=[].slice,ga,W,L,t,A,X,M,ha,ia,ja,H,Y,N,O,ka,I,la,ma,na,oa,y,pa,B,P,qa,Z,ra,sa,$,v,ta,aa,Q,R,ua,va,S,wa,ba,ca,xa,da,F,J,K,T,ea,w=function(a){try{return{init:O,hash:N,rules:ua,
hasRules:S,defaults:xa,__qc:function(){return!0}}[a].apply(null,V.call(arguments,1))}catch(c){return!1}};w.evts=0;w.v=2;w.SD=C;w.qpixelsent=[];R=function(a){var c=a?a.length||0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};ca=function(a){(a=a||b._qacct)&&($(s,a)||s.push(a))};$=function(a,c){var d=a.length,b;for(b=0;b<d;b++)if(a[b]===c)return!0;return!1};aa=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};Q=function(a){var c,d;c=aa(a);if("array"===c)return a.slice(0);
if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};S=function(a){return $(p,a)};xa=function(a,c){var d;a&&((d=e[a])&&(c=T(c,d)),c.qacct&&delete c.qacct,e[a]=c)};da=function(a){var c,d;if(t(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?y(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=g[d])?T(c,a):a,g[d]=c);ca(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&da(a[c])};T=function(a,
c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;Z(d,a,c);Z(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};Z=function(a,c,d){var b,U,e,k,g,m;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&(U=c[b],e=d[b],k="",g=!!U&&"string"==typeof U,m=!!e&&"string"==typeof e,g&&(k=U),g&&m&&
(k+=","),m&&(k+=e),a[b]=k)};F=function(){var a=[],c,d;if(!(0<f)){ta();for(c in g)g.hasOwnProperty(c)&&g[c]&&(d=g[c],a.push(d),delete g[c]);1==a.length&&y(a[0]);1<a.length&&y(a)}};J=function(a){var c=[],d,b;for(d=0;d<a.length;d++)b=a[d],S(b)||c.push(b);if(0===c.length)F();else for(d=0;d<c.length;d++)b=c[d],p.push(b),ra(b)};sa=function(){for(var a;r[0]&&("loaded"==r[0].readyState||"complete"==r[0].readyState);)a=r.shift(),a.onreadystatechange=null,k.parentNode.insertBefore(a,k),K()};ra=function(a){var c,
d;c=("https:"===u.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";k=k||u.scripts[0];f++;d=u.createElement("script");"async"in d?(d.src=c,d.async=!1,d.onload=function(){x[a]=0;K()},d.onerror=function(){x[a]=1;K()},k.parentNode.insertBefore(d,k)):d.readyState?(x[a]=2,r.push(d),d.onreadystatechange=sa,d.src=c):(x[a]=4,K())};K=function(){f-=0<f?1:0;F()};ua=function(){var a=!0,c,d,b;if(arguments.length){b=function(c){a?da(c):y(c,!0)};for(c=0;c<arguments.length;c++)d=V.call(arguments[c],
0),d.splice(1,0,b),va.apply(null,d);a=!1;G&&F()}};va=function(a,c){var b=[],h=[],e=c||y,k,g,m,f,fa;if((k=V.call(arguments,2))&&k.length){g=k[0]||R;m=k[1];f=k[2];k=f.length;for(fa=0;fa<k;fa++)b.push(!1),h.push(null);b={p:a,f:b,r:g,c:f,a:m,v:h};S(a)||p.push(a);l.push(b);wa(b,e)}};wa=function(a,c){var b=a?a.c?a.c.length:0:0,h;for(h=0;h<b;h++)(function(b){var d,h;try{d=a.c[b][0],h=a.c[b].slice(1),h.splice(0,0,function(d){a.f[b]=!0;a.v[b]=d;ba(a,c)}),d.apply(null,h)}catch(k){a.f[b]=!0,a.v[b]=!1,ba(a,c)}})(h)};
ba=function(a,c){var b=a.a,h=a.v,k=a.r||R,e,g,m,f,l,n;(e=R(a.f))&&(e=e&&k(h));if(e)for(h=0;h<b.length;h++)try{g=b[h][0];m=1<b[h].length?b[h].slice(1):[];m=m.concat(a.v);f=g.apply(null,m);l={qacct:a.p,event:"rule"};for(n in f)f.hasOwnProperty(n)&&"qacct"!==n&&(l[n]=f[n]);c(l)}catch(q){}};ga=function(){return W(0)!==W(6)?1:0};W=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};L=function(a){return a.replace(/\./g,"%2E").replace(/,/g,
"%2C")};A="function"===typeof encodeURIComponent?encodeURIComponent:L;t=function(a){return"undefined"!=typeof a&&null!=a};X=function(){return Math.round(2147483647*Math.random())};M=function(a){var c="",b=u.cookie,h;if(!b)return c;h=b.indexOf(a+"\x3d");a=h+a.length+1;-1<h&&(c=b.indexOf(";",a),0>c&&(c=b.length),c=b.substring(a,c));return c};ha=function(){var a="",c=H(),b,h,k;if(1===D)return";fpan\x3du;fpa\x3d";b=N(c);for(h=0;h<C.length;h++)if(C[h]===b)return";fpan\x3du;fpa\x3d";b=new Date;h=M("__qca");
if(0<h.length){try{k=+h.split("-")[2],338688E5<b-k&&(u.cookie=["__qca\x3d",h,"; expires\x3d",(new Date(k+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(e){}a+=";fpan\x3d0;fpa\x3d"+h}0===M("__qca").length&&(h="P0-"+X()+"-"+b.getTime(),u.cookie=["__qca\x3d",h,"; expires\x3d",(new Date(b.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""),h=M("__qca"),a=0<h.length?a+(";fpan\x3d1;fpa\x3d"+h):a+";fpan\x3du;fpa\x3d");return a};ia=function(a){u.cookie=a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+
H()};H=function(){var a,c,b,h;a=u.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");h=c.length;if(3>h)return a;b=c[h-1];return 3>b.length?a:a=c[h-2]+"."+b};Y=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};N=function(a){var c;c=Y(2166136261,a);a=Y(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};P=function(a,c,d){var h="",k=b._qacct,m=null,f="webpage",l="load",q={},p,n,k=c?c.qacct||b._qacct:
b._qacct;p=g[k];c?p&&(c=T(c,p)):c=p;k&&delete g[k];if(null!=c)for(n in c)q[n]=!0,c.hasOwnProperty(n)&&"string"===typeof n&&"string"===typeof c[n]&&("uid"===n||"uh"===n?(ka()||(m=N(c[n])),delete c[n]):"qacct"!==n&&(h+=";"+n+a+"\x3d"+A(c[n]),"media"===n&&(f=c[n]),"event"===n&&(l=c[n])));if("string"!==typeof k){if(!t(b._qacct)||0===b._qacct.length)return"";k=b._qacct}if(k&&(p=e[k]))for(n in p)"string"===typeof n&&p.hasOwnProperty(n)&&!q[n]&&(h+=";"+n+a+"\x3d"+A(p[n]),"media"===n&&(f=p[n]),"event"===
n&&(l=p[n]));q=x[k];t(q)||(q=3);h+=";rf"+a+"\x3d"+q;"string"===typeof m&&(c.uh=m,h+=";uh"+a+"\x3d"+A(m));if("webpage"===f&&"load"===l){for(c=0;c<w.qpixelsent.length;c++)if(w.qpixelsent[c]===k&&!d)return"";w.qpixelsent.push(k)}"ad"===f&&(D=1);return";a"+a+"\x3d"+k+h};qa=function(){var a=u.getElementsByTagName("meta"),c="",b,k,e,g;for(b=0;b<a.length;b++){e=a[b];if(1E3<=c.length)return c;t(e)&&t(e.attributes)&&t(e.attributes.property)&&t(e.attributes.property.value)&&t(e.content)&&(k=e.attributes.property.value,
e=e.content,3<k.length&&"og:"===k.substring(0,3)&&(0<c.length&&(c+=","),g=80<e.length?80:e.length,c+=L(k.substring(3,k.length))+"."+L(e.substring(0,g))))}return A(c)};ja=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};ka=function(){var a=!1;t(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==z.doNotTrack||"yes"===z.doNotTrack||"1"==z.msDoNotTrack};y=
function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",k=X(),e="",g="",m="",f="",l="",p="u",n="1",q=0,s=[],r,v,x,y;D=0;t(w.qpixelsent)||(w.qpixelsent=[]);if(t(a))for(r in a)if("string"==typeof a[r]){g=P("",a,c);break}else"object"==typeof a[r]&&null!=a[r]&&(++q,g+=P("."+q,a[r],c));else"string"===typeof _qacct&&(g=P("",null,c));0!==g.length&&(q=z.cookieEnabled?"1":"0","undefined"!=typeof z.javaEnabled&&(p=z.javaEnabled()?"1":"0"),t(b._qmeta)&&(m=";m\x3d"+A(b._qmeta),b._qmeta=null),self.screen&&
(e=screen.width+"x"+screen.height+"x"+screen.colorDepth),v=new Date,x=ga(),y=ha(),b.location&&b.location.href&&(f=A(b.location.href)),u&&u.referrer&&(l=A(u.referrer)),b.self===b.top&&(n="0"),r=qa(),s.push("/pixel;r\x3d"+k+g+y+";ns\x3d"+n+";ce\x3d"+q),s.push(";je\x3d"+p+";sr\x3d"+e+";enc\x3d"+d+";dst\x3d"+x+";et\x3d"+v.getTime()+";tzo\x3d"+v.getTimezoneOffset()+m+";ref\x3d"+l+";url\x3d"+f+";ogl\x3d"+r),E.push(s),B())};pa=function(a){var c=new Image;a=[b.location.protocol,"//pixel.",la(q)?"quantserve.com":
"quantcount.com",a[0],";cm\x3d",ja(q),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&"number"==typeof c.width&&3===c.width&&ia("__qca")}};B=function(){if(q)for(;E.length;)pa(E.shift());else oa()};la=function(a){return!0===a||1===a||1===a||t(a)&&"approved"===a.consent?!0:!1};oa=function(){if(!t(q)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){ma("getConsent","advertising");return}}else if(b.postMessage&&"object"===typeof JSON){na("getConsent",
"advertising");return}q=1}B()};ma=function(a,b){q=PrivacyManagerAPI.callApi(a,"quantserve.com",H(),"truste.com",b);B()};na=function(a,c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:H(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",I,!1);else if(b.attachEvent)b.attachEvent("onmessage",I);else{q=!0;B();return}try{b.top.postMessage(JSON.stringify(d),"*")}catch(k){}m=setTimeout(function(){t(q)||(q=!0,B())},25)};I=
function(a){var c=null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(m),b.removeEventListener?window.removeEventListener("message",I,!1):b.detachEvent&&window.detachEvent("onmessage",I),q=c.PrivacyManagerAPI,B())}};ea=function(){var a=arguments,b,d;v([].slice.call(a));for(d=0;d<a.length;d++)b=a[d],y(b);s.length?J(s.slice(0)):F()};v=function(a){var c=aa(a);if("array"===c)for(c=0;c<a.length;c++)v(a[c]);else"object"===
c&&ca(a.qacct||b._qacct)};ta=function(){var a;b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||y({qacct:b._qacct});if(!w.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&y(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&y(b.ezt[a]);b._qevents={push:ea};b.ezt.push=function(){var a=arguments,d;if(t(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else ea.apply(this,arguments)};w.evts=1}};O=function(){var a;t(b._qevents)||(b._qevents=[]);t(b.ezt)||(b.ezt=[]);
b._qoptions&&(a=Q(b._qoptions),v(b._qoptions),b._qevents.push(a),b._qoptions=null);b.qcdata&&(a=Q(b.qcdata),v(b.qcdata),b._qevents.push(a),b.qcdata=null);b.smarttagdata&&(a=Q(b.smarttagdata),v(b.smarttagdata),b._qevents.push(a),b.smarttagdata=null);w.evts||(b._qevents.push=function(){v([].slice.call(arguments));J(s.slice(0));return[].push.apply(b._qevents,arguments)},b.ezt.push=function(){v([].slice.call(arguments));J(s.slice(0));return[].push.apply(b.ezt,arguments)});v(b.ezt);v(b._qevents);v({qacct:b._qacct});
b._qoptions=null;s.length?J(s.slice(0)):F();G=!0};b.quantserve=b.quantserve||O;w.quantserve=O;return w}(window);
try{__qc("hasRules","p-9E79g-9qXk8bk")||function(b,u,z){var C="twitter:title og:title title author authors article:author article:authors bt:author bt:authors sailthru.author sailthru.authors sailthru.title lv:author lv:authors lv:title".split(" "),G=function(b){return{}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()},D=function(b,e,g){return b?"nc"===b?!e||!g||0>e.indexOf(g):"eq"===b?e===g:"sw"===b?0===e.indexOf(g):"ew"===b?(b=e.length-g.length,e=e.lastIndexOf(g,b),-1!==e&&e===b):"c"===
b?0<=e.indexOf(g):!1:!1},E=function(b){var e=z.createElement("a");e.href=b;return e},l=function(b,e,g){var m;m=u.top===u.self?z.location.host:E(z.referrer).hostname;D(e,m,g)?b(m):b(!1)},p=function(b,e,g){var m;m=u.top===u.self?z.location.pathname:E(z.referrer).pathname;D(e,m,g)?b(m):b(!1)},s=function(b,e,g){e=document.getElementsByTagName("meta");for(var m,f,l=0;l<e.length;l++)if(m=e[l],f=m.getAttribute("name")||m.getAttribute("property"),f==g){f=m.getAttribute("content");e=m=e=void 0;b:{e=void 0;
for(e=0;e<C.length;e++)if(C[e]===g){e=!1;break b}e=!0}if(f)if(e){m=f.split(",");for(e=0;e<m.length;e++)g=m,f=e,l=m[e].replace(/[^\w*]/g," ").replace(/^[\s\ufeff\xA0]+|[\s\ufeff\xA0]+$/g,""),g[f]=l;g=m}else g=f.replace(/[^\w*]/g," ");else g=f;b(g);return}b(!1)},x=function(b){return{labels:b}},f=function(b){return"array"===G(b)?x(b.join(",")):x(""+b)},r=function(b,e){var g=[],f;if("array"===G(e)){for(f=0;f<e.length;f++)g.push(b+"."+e[f]);return x(g.join(","))}return x(b+"."+e)};__qc("rules",[b,null,
[[f,"Lib\u00e9ration.Sports"]],[[p,"c","/sports"],[l,"c","liberation.fr"]]],[b,null,[[f,"Lib\u00e9ration.Le P'tite Lib\u00e9"]],[[l,"c","liberation.fr"],[p,"c","/ptit-libe"]]],[b,null,[[f,"Lib\u00e9ration.Six Plus"]],[[l,"c","liberation.fr"],[p,"c","/data-nouveaux-formats-six-plus"]]],[b,null,[[f,"Lib\u00e9ration.Blogs"]],[[l,"c","liberation.fr"],[p,"c","/blogs"]]],[b,null,[[f,"Lib\u00e9ration.Video"]],[[l,"c","liberation.fr"],[p,"c","/video"]]],[b,null,[[f,"Lib\u00e9ration.Photo"]],[[l,"c","liberation.fr"],
[p,"c","/photographie"]]],[b,null,[[f,"Lib\u00e9ration.Direct"]],[[l,"c","liberation.fr"],[p,"c","/direct"]]],[b,null,[[f,"Lib\u00e9ration.Voyages"]],[[l,"c","liberation.fr"],[p,"c","/voyages"]]],[b,null,[[f,"Lib\u00e9ration.Portrait"]],[[l,"c","liberation.fr"],[p,"c","/portrait"]]],[b,null,[[f,"Lib\u00e9ration.D\u00e9sintox"]],[[l,"c","liberation.fr"],[p,"c","/desintox"]]],[b,null,[[f,"Lib\u00e9ration.Le Journal Du Jour"]],[[l,"c","liberation.fr"],[p,"c","/liseuse/publication"]]],[b,null,[[f,"Lib\u00e9ration.Culture/Next"]],
[[l,"c","next.liberation.fr"]]],[b,null,[[f,"Lib\u00e9ration.Id\u00e9es"]],[[l,"c","liberation.fr"],[p,"c","/debats"]]],[b,null,[[f,"Lib\u00e9ration.Futurs"]],[[l,"c","liberation.fr"],[p,"c","/futurs"]]],[b,null,[[f,"Lib\u00e9ration.Plan\u00e8te"]],[[l,"c","liberation.fr"],[p,"c","/planete"]]],[b,null,[[f,"Lib\u00e9ration.France"]],[[l,"c","liberation.fr"],[p,"c","/france"]]],[b,null,[[r,"Lib\u00e9ration.Categorie D'Article"]],[[s,"exactmatch","article:section"],[l,"c","liberation.fr"]]],[b,null,
[[r,"Mots Cl\u00e9s.Lib\u00e9ration"]],[[s,"exactmatch","keywords"],[l,"c","liberation.fr"]]],[b,null,[[r,"Articles.Lib\u00e9ration"]],[[s,"exactmatch","og:title"],[l,"c","liberation.fr"]]],[b,null,[[r,"Mots Cl\u00e9s.CoteMaison"]],[[s,"exactmatch","news_keywords"],[l,"c","cotemaison.fr"]]],[b,null,[[r,"Mots Cl\u00e9s.L'Express"]],[[s,"exactmatch","news_keywords"],[l,"c","lexpress.fr"]]],[b,null,[[r,"Articles.CoteMaison"]],[[s,"exactmatch","og:title"],[l,"c","cotemaison.fr"]]],[b,null,[[r,"Articles.L'Express"]],
[[s,"exactmatch","og:title"],[l,"c","lexpress.fr"]]])}("p-9E79g-9qXk8bk",window,document)}catch(nfe$$3){}quantserve();try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$4){};