window.SPR=function(){function z(a,d){var c=this;c.H=[];c.A=a||{};c.Mc=b.tc;c.pa=!1;c.lc=d||b.Xb;p.Sb(c.lc);g.a(a[b.qa]);a[b.c]=a[b.c]||q.current[b.c];a[b.url]=a[b.url]||e.ia();a[b.title]||(a[b.title]=e.ha(a[b.url]));if(a[b.url])c.a=function(){if(c.hc())return c.Ob(),c;g[b.error](c.wb());return null},c[b.wc]=function(a){c.ic(a)?c.Pb(a):c.tb(a);return c},c[b.oc]=function(a){c.fc(a)?c.Nb(a):c.sb();return c},c[b.Bc]=function(a){c.jc(a)?c.Qb(a):c.ub();return c},c[b.mc]=function(){c.pa||(c.l(c.da(c.da())),
c[b.Ea](100),c.pa=!0);return c},c[b.Ea]=function(a){if(f.contains(c.H,a))return null;if(f.contains(f.T,a)){var d=c.g();d[b.i]=b.Fa;d[b.Fa]=c.Ya(a);c.l(d)}else g[b.error](b.fb);return c},c.Ya=function(a){var d,n=f.T,e={};if(!f.contains(n,a))g[b.error](b.ra);else if(!f.contains(c.H,a))for(d=0;d<n.length;d+=1){var l=n[d];a>=l&&!f.contains(c.H,l)&&(c.H.push(l),e[l]=!0,g[b.info](b.za+l))}return e},c.l=function(a){p.f(b.h,b.qc,a)},c.Ob=function(){c.l(c.cb())},c.Pc=function(){return q.current},c.g=function(){return v.ba(c.A)},
c.cb=function(){var a=c.g();a[b.i]=b.sc;return a},c.hc=function(){var a;for(a=0;a<r.length;a+=1)if(!c.A[r[a]])return!1;return!0},c.wb=function(){var a,d=[];for(a=0;a<r.length;a+=1)c.A[r[a]]||d.push(r[a]);return b.hb+d.join(", ")},c.Pb=function(a){c.l(c.$b(a))},c.ic=function(a){return a===b.zc||a===b.Ac},c.$b=function(a){var d=c.g();d[b.i]=b.xc;d[b.yc]=a;return d},c.tb=function(a){if(a)g[b.error](a+b.ib);else g[b.error](b.dc)},c.da=function(){var a=c.g();a[b.i]=b.nc;return a},c.Nb=function(a){c.l(c.Va(a))},
c.Va=function(a){var d=c.g();d[b.i]=b.pc;d[b.uc]=a;return d},c.fc=function(a){return!isNaN(a)},c.sb=function(){g[b.error](b.eb)},c.Qb=function(a){c.l(c.ac(a))},c.ac=function(a){var d=c.g();d[b.i]=b.Cc;d[b.vc]=a;return d},c.jc=function(a){return!isNaN(a)&&c.kc(a)},c.kc=function(a){return f.Na(f.Dc,a)},c.ub=function(){g[b.error](b.gb)};else g[b.error](b.W+b.ja)}var b={h:"edge.simplereach.com",version:"1",La:"d8rk54i4mohrb.cloudfront.net",bb:"/n",bc:"/t",qc:"/v",ka:"/event",Ja:"/pixel?bad=true&error=",Kc:"/iframe.html",
Ma:"/container.html",Aa:"000000000000000000000000",W:"SPR-ERROR: ",ja:"100 - Missing url",Fb:"__reach_config",Ka:"cache_buster",xa:"__srret",Da:"__srui",K:"0",zb:"1",ab:"img",Ab:"1px",width:"width",Z:"undefined",error:"error",xb:"off",info:"info",F:"SPR_DEBUG",Yb:"//",X:"string",referrer:"referrer",uid:"uid",o:"callback",f:"jsonp",url:"url",title:"title",c:"pid",ya:"s",r:"r",t:"t",e:"e",x:"x",n:"n",ec:"v",qa:"ignore_errors",Eb:"preview",L:"authors",N:"channels",Y:"tags",v:"date",Lc:"inframe",Jc:"iframe",
Pa:"custom_tracking",Gb:"reach_tracking",B:"ref_url",va:"page_url",Uc:"user_id",vb:"manual_scroll_depth",ga:"content_height",Oc:"rd",Ic:"fb",Ec:"de",pb:"li",Bb:"pi",Oa:"csd",qb:"www.linkedin.com",Cb:"partners-api.pinterest.com",rb:"/countserv/count/share",Db:"/v1/urls/count.json",ra:"[error] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",za:"[info] sending scrollDepth of: ",Mb:"[info] scroll depth not activated, not sending data",Xb:"SimplereachVideo",i:"event_name",hb:"Missing params please provide a ",
ib:" is not a valid start event type.",dc:"Cannot have an undefined start type. Please provide a start type.",eb:"Please pass a valid number",fb:"[error] Invalid quartile please send quartiles of only: 25, 50, 75 or 100",Qc:"[error] Quartile for this video already sent",gb:"Please pass a valid threshold number",rc:"video_id",ob:"length",description:"description",Tc:"thumbnail_url",Rc:"source_url",ua:"networks",tc:"video",wc:"start",oc:"elapsed",mc:"complete",Ea:"quartile",Bc:"elapsedThreshold",sc:"init",
xc:"start",pc:"elapsed",Fa:"quartile",nc:"complete",Cc:"elapsed_threshold",yc:"start_type",zc:"auto",Ac:"click",uc:"seconds_elapsed",vc:"threshold"},f={Kb:function(){return Math.random().toString(36).replace(/[^a-z]+/g,"")},returnValue:function(a){return a},R:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},log:function(a){window.console&&console.log(a)},kb:function(a){return"[object String]"===Object.prototype.toString.call(a)},J:function(a){var b=
{},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b},ta:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},contains:function(a,b){return-1!==(a.join(",")+",").indexOf(b+",")},Na:function(a,b){if(!isNaN(b)&&!this.kb(b))for(var c=0;c<=a.length;c++)if(a[c]===b)return!0;return!1},O:function(a){typeof a===b.X&&(a=a.split(","));if(this.R(a)){for(var d=0;d<a.length;d+=1)typeof a[d]===b.X&&(a[d]=a[d].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}},w:function(){},
ma:function(){return window.location.protocol+"//"},T:[25,50,75,100],Dc:[3,15,30,45]},t={encode:function(a,b){var c=[];if(f.R(a))for(var d=0,h;d<a.length;d+=1)h=a[d],/\[\]$/.test(b)?c.push(encodeURIComponent(b)+"="+encodeURIComponent(h)):c.push(this.encode(h,b+"["+("object"===typeof h?d:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)c.push(encodeURIComponent(b)+"="+encodeURIComponent(a));else for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&(b?c.push(this.encode(a[d],b+"["+d+
"]")):c.push(this.encode(a[d],d)));return c.join("&")},decode:function(a){var d={},c=0,n={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var h=a[c].split("="),e=decodeURIComponent(h[0]),g=d,l=0,m=e.split("]["),k=m.length-1;/\[/.test(m[0])&&/\]$/.test(m[k])?(m[k]=m[k].replace(/\]$/,""),m=m.shift().split("[").concat(m),k=m.length-1):k=0;if(2===h.length)if(h=(h=decodeURIComponent(h[1]))&&!isNaN(h)?+h:h===b.Z?void 0:void 0!==n[h]?n[h]:h,k)for(;l<=k;l+=1)e=""===
m[l]?g.length:m[l],g=g[e]=l<k?g[e]||(m[l+1]&&isNaN(m[l+1])?{}:[]):h;else f.R(d[e])?d[e].push(h):d[e]=void 0!==d[e]?[d[e],h]:h;else e&&(d[e]=void 0)}return d}},u={wa:{},oa:function(a){var b=document.cookie||"",c=this.wa[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=new RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),this.wa[a]=c);return(a=b.match(c))&&decodeURIComponent(a[1])},V:function(a,b,c){var d="";c&&(d="; expires="+c.toGMTString());document.cookie=a+"="+b+d+"; path=/"},Fc:function(a){this.V(a,
"",new Date(1982,5,13))}},q={current:{}},g={la:!1,info:f.w,error:f.log,a:function(){window[b.F]&&(this.la=!0,window[b.F][b.info]&&(this[b.info]=window[b.F][b.info]),window[b.F][b.error]&&(this[b.error]=window[b.F][b.error]))},reset:function(){this.la=!1;this[b.info]=f.w;this[b.info]=f.log},Ub:function(a){var d=document.createElement(b.ab);d.src=f.ma()+b.h+b.Ja+a.message;d.setAttribute(b.width,b.Ab);document.body?document.body.appendChild(d):document.head.appendChild(d)},Vb:function(a){a===b.info?
(this[b.info]=f.log,this[b.error]=f.log):a===b.error?(this[b.info]=f.w,this[b.error]=f.log):(this[b.info]=f.w,this[b.error]=f.w)}},e={K:0,u:{x:0,y:0},P:!0,a:function(){function a(){e.P=document[h]?!1:!0}function b(){e.flush();window.removeEventListener("DOMContentLoaded",b,!1)}function c(){/loaded|interactive|complete/.test(document.readyState)&&(document.detachEvent("onreadystatechange",c),g&&(g=!1,e.flush()))}var e=this;e.K=0;this.yb(window,"mousemove",function(a){e.u={x:a.clientX,y:a.clientY}});
if("undefined"!==typeof document.hidden){var h="hidden";var f="visibilitychange"}else"undefined"!==typeof document.mozHidden?(h="mozHidden",f="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(h="msHidden",f="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(h="webkitHidden",f="webkitvisibilitychange");"undefined"!==typeof document.addEventListener&&"undefined"!==typeof h&&document.addEventListener(f,a,!1);var g=!0;window.addEventListener?window.addEventListener("DOMContentLoaded",
b,!1):document.attachEvent&&document.attachEvent("onreadystatechange",c)},Ga:function(a,b){var c=document.createElement("iframe"),d=document.body;c.setAttribute("name","spr");c.src=a;c.setAttribute("height","1");c.setAttribute("width","1");c.setAttribute("visible","false");c.setAttribute("id","spr-iframe-"+b);c.style.display="none";d||(d=this.b("BODY")[0]);d||(d=this.b("HEAD")[0]);g.info(a);d.appendChild(c);return c},Ra:function(){for(var a=this.b("meta"),b=0;b<a.length;b+=1)if("og:url"===a[b].getAttribute("property"))return a[b].content;
return!1},Qa:function(){for(var a=this.b("link"),b=0;b<a.length;b+=1)if("canonical"===a[b].rel)return a[b].href;return!1},Sa:function(){for(var a=this.b("meta"),b=0;b<a.length;b+=1)if("twitter:url"===a[b].getAttribute("name"))return a[b].content;return!1},Ta:function(){return window.location.protocol+"//"+window.location.hostname+window.location.pathname},ia:function(){return this.Qa()||this.Ra()||this.Sa()||this.Ta()},na:function(){return document.referrer},ha:function(a){for(var b=this.b("meta"),
c=0;c<b.length;c+=1)if("og:title"===b[c].getAttribute("property")||"twitter:title"===b[c].getAttribute("name"))return b[c].content;return document.title||a||!1},Hb:function(a){var b=document.body,c=this.b("BODY")[0],e=this.b("HEAD")[0];b&&b.contains(a)?b.removeChild(a):c&&c.contains(a)?c.removeChild(a):e&&e.contains(a)&&e.removeChild(a);return a},Ha:function(a){var b=this,c=document.createElement("script");c.type="text/javascript";c.setAttribute("async",!0);c.setAttribute("name","spr");c.setAttribute("id",
"spr-script");c.src=a;g.info(a);this.S(function(){setTimeout(function(){b.b("HEAD")[0].appendChild(c)},1)});return c},j:[],ready:/loaded|interactive|complete/.test(document.readyState),flush:function(){var a=this.j.shift();for(this.ready=!0;a;)a(),a=this.j.shift()},S:function(a){this.ready?(this.j.push(a),this.flush()):document.documentElement.doScroll?window.self===window.top?function(){if(!document.uniqueID&&document.expando)return this.j.push(a);try{document.documentElement.doScroll("left"),a()}catch(d){setTimeout(arguments.callee,
0)}}():this.j.push(a):this.j.push(a)},yb:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},xb:function(a,b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},I:function(){return(window.pageYOffset?window.pageYOffset:document.documentElement?document.documentElement.scrollTop:0)-this.K},b:function(a){var b=[],c=0,e;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(document.getElementById(a.substring(1)));
break;case ".":var f=document.getElementsByTagName("*");for(e=" "+a.substring(1)+" ";c<f.length;c+=1)a=(" "+f[c].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(e)&&b.push(f[c]);break;default:b=document.getElementsByTagName(a)}return b}},v={ba:function(a){var d;var c=f.J(a);c[b.L]&&(c[b.L]=f.O(c[b.L]));c[b.N]&&(c[b.N]=f.O(c[b.N]));c[b.Y]&&(c[b.Y]=f.O(c[b.Y]));c[b.v]&&typeof c[b.v]!==b.X&&(c[b.v]=c[b.v].toString());c[b.referrer]=""==c[b.B]?"":this.U(c[b.referrer]);c[b.B]=this.U(c[b.B]);c[b.va]=
c[b.va]||window.location.toString();c[b.uid]?c[b.uid]=c[b.uid]:(d=this.$a())&&(c[b.uid]=d);c[b.url]&&(c[b.url]=this.Lb(c[b.url]),a[b.url]=c[b.url]);return c},U:function(a){""!==a&&(a=a||e.na());return a},$a:function(){return u.oa(b.Da)},Lb:function(a){if(0===a.indexOf("http%253A")||0===a.indexOf("https%253A"))a=decodeURIComponent(a);if(0===a.indexOf("http%3")||0===a.indexOf("https%3"))a=decodeURIComponent(a);return a}},p={callbacks:{},M:"SPR",Sb:function(a){this.M=a},f:function(a,d,c,g,h){g=g||function(){};
h||(h="cb");var k="cb"+f.Kb(),n=this;c[h]=this.M+".API.callbacks."+k;h=f.ma();"file://"===h&&(h="http://");c[b.ec]=b.version;c=t.encode(c);var l=e.Ha(h+a+d+"?"+c);n.callbacks[k]=function(a){setTimeout(function(){l.parentNode.removeChild(l)},0);g(a);try{delete n.callbacks[k]}catch(D){n.callbacks[k]=null}}}},w={Nc:!1,Hc:!0,m:0,Ba:5E3,cc:12E5,interval:null,reset:function(){e.K=e.I();window.clearInterval(this.interval)},track:function(a){var d=this,c;d.interval=setInterval(function(){e.P&&(d.m+=d.Ba);
d.Ca()&&(d.m=0);c=f.J(a);c[b.t]=d.m;c[b.e]=d.jb()?5E3:0;c[b.ya]=e.I();0===c[b.c]&&(c[b.c]=b.Aa);e.P&&!d.Ca()&&d.gc(c)&&0<c[b.e]&&(d.m=0,p.f(b.h,b.bc,c));d.mb=e.u.x;d.nb=e.u.y;d.lb=e.I()},d.Ba)},jb:function(){return!0!==this.Wa?this.Wa=!0:this.mb!==e.u.x||this.nb!==e.u.y||this.lb!==e.I()?!0:!1},Ca:function(){return this.m>=this.cc},gc:function(a){return a[b.url]&&a[b.c]}},k=f.T,y={G:[],data:{},response:null,options:null,Sc:!1,a:function(a,d){this.reset();this.options=d;this.response=a;var c=this;e.S(function(){c.height=
c.Xa();c.D||(c.D=function(){c.ca()});q.current[b.vb]?c.Ib():c.Ia()})},Ia:function(){typeof document.addEventListener!==b.Z?document.addEventListener("scroll",this.D,!1):window.attachEvent("onscroll",this.D);this.ca()},Ib:function(){typeof document.removeEventListener!==b.Z?document.removeEventListener("scroll",this.D,!1):window.detachEvent("onscroll",this.D)},ca:function(){var a=this.Za()+Math.min(document.documentElement.clientHeight,window.innerHeight||0),b=0;a>=this.height?b=k[3]:b=a/this.height*
100;97<=b?this.C(k[3]):b>=k[2]?this.C(k[2]):b>=k[1]?this.C(k[1]):b>=k[0]&&this.C(k[0])},Xa:function(){if(q.current[b.ga])var a=q.current[b.ga];else{a=document.body;var d=document.documentElement;a=Math.max(a.scrollHeight,a.offsetHeight,d.clientHeight,d.scrollHeight,d.offsetHeight)}return a},Za:function(){var a="CSS1Compat"===(document.compatMode||"");return void 0!==window.pageYOffset?window.pageYOffset:a?document.documentElement.scrollTop:document.body.scrollTop},C:function(a){this.data={};if(!f.contains(k,
a))g[b.error](b.ra);else if(!f.contains(this.G,a))if(this.Tb(a),this.response[b.Oa])this.Rb();else g[b.info](b.Mb)},Tb:function(a){var d;for(d=0;d<k.length;d+=1){var c=k[d];a>=c&&!f.contains(this.G,c)&&(this.G.push(c),this.data[c]=!0,g[b.info](b.za+c))}},A:function(){return f.ta({event:"csd",sd:this.data},this.options)},Rb:function(){if(!this.response.error){var a=this.A();p.f(b.h,b.ka,a)}},reset:function(){this.G=[]}},A={ua:[{name:b.pb,$:b.qb,aa:b.rb,o:b.o},{name:b.Bb,$:b.Cb,aa:b.Db,o:b.o}],Jb:function(a,
b){return{url:b}},Zb:function(a,d){return function(c){c={event:b.ya,url:a.url,cid:a.id,pid:a.pid,sn:a.name,data:c};f.ta(c,d);p.f(b.h,b.ka,c)}},s:function(a,b){for(var c=this.ua,d,e=0;e<c.length;e+=1){d=c[e];var g=f.J(a);g.name=d.name;a[d.name]&&p.f(d.$,d.aa,this.Jb(d.name,g.url),this.Zb(g,b),d.o)}}},B={track:function(a){var d=this;0===a[b.c]&&(a[b.c]=b.Aa);p.f(b.h,b.bb,a,function(c){y.a(c,a);if(c.error)g[b.error](b.W+c.error.code+" - "+c.error.message);else c.uid&&d.Wb(c.uid),A.s(c,a)})},Wb:function(a){u.V(b.Da,
a,new Date(2042,5,13))}},x={Gc:{},ea:{},a:function(){try{e.a();var a=window[b.Fb];u.oa(b.xa)?this.sa=!0:this.sa=!1;u.V(b.xa,b.zb,new Date(2042,5,13));this.s(a)}catch(d){e.S(function(){g.Ub(d)})}},s:function(a){q.current=a;this.ea=f.J(q.current);this.ea[b.r]=this.sa;if(a)if(g.a(a[b.qa]),a[b.url]=a[b.url]||e.ia(),a[b.title]||(a[b.title]=e.ha(a[b.url])),a[b.url]){w.reset();var d=v.ba(a);d[b.Eb]||(!1!==a[b.Gb]&&(B.track(d),w.track(d)),!1!==a[b.Pa]&&this.Ua(d))}else g[b.error](b.W+b.ja);else g[b.error]("Params not passed to collect")},
Ua:function(a){a[b.referrer]=a[b.referrer]||e.na();a[b.B]=v.U(a[b.B]);a[b.Ka]=(new Date).getTime();a=t.encode(a);this.fa&&e.Hb(this.fa);this.fa=e.Ga(b.Yb+b.La+b.Ma+"?"+a,b.x)}},r=[b.c,b.rc,b.ob,b.v],C={create:function(a,b){return new z(a,b)},a:function(a,b){return this.create(a,b).a()}};return{Reach:{collect:function(a){x.s(a)}},QS:{decode:t.decode},debug:g,setLogLevel:function(a){g.Vb(a)},API:p,collect:function(a){x.s(a)},decode:t.decode,init:function(){x.a()},iframeCollect:function(){},stop:function(){w.reset()},
scrollDepthReached:function(a){y.C(a)},video:function(a){return C.a(a,p.M)}}}();window.SPR.init();
